### ISSUE TITLE
Documentation to cover treelike for layers

### ISSUE THREAD

**Issue by baggepinnen** [FluxML/Flux.jl#100]
Consider the following layer `Res2` which contains two `Dense` layers in a chain, with the function of the layer being `activation(x + chain(x))`
```julia
struct Res2
    chain
end

Res2(inputwidth,width) = Res2(Chain(Dense(inputwidth,width,swish),Dense(width,inputwidth)))
(r::Res2)(x) = swish.(x .+ r.chain(x))

n = 5
np = 10
m = Chain(
    Dense(n,np,swish),
    Res2(np,np),
    Res2(np,np),
    Res2(np,np),
    Res2(np,np),
    Dense(np,n)
)
```
When I call `params` on the model `m`, the parameters of the `Res2` layers do not show up. Is this a bug or have I misunderstood how to compose layers?

```julia
julia> params(m)
4-element Array{Any,1}:
 param([-0.00680718 -0.00810156 … -0.0130675 -0.0217635; 0.00893031 -0.0112561 … -0.0132078 0.000226305; … ; 0.00464268 0.0015668 … 0.00110918 0.00111789; -0.00921265 -0.00389085 … 0.0112846 -0.00805689])
 param([-0.0169659, -0.0180195, 0.000163538, -0.0111752, 0.013014, 0.00813894, 0.00311244, -0.00264249, -0.00702083, 0.0110054])                                                                            
 param([0.0106695 -0.0045525 … -0.0077128 -0.0104561; -0.0212993 -0.0137948 … 0.00591983 -0.0233666; … ; 0.00780111 0.0193906 … 0.00700548 0.0125713; -0.0177297 -0.00128902 … -0.00923536 9.27876e-5])     
 param([0.00431632, 0.00832052, -0.0134394, -0.00536808, -0.0129291])  
```

**Comment by iblis17** [comment]
try this?
```julia
struct Res2
    chain
end
treelike(Res2)
```

**Comment by baggepinnen** [comment]
Thanks! That seems to do the trick. The documentation does not cover this as far as I can tell so I'll update the issue to a documentation issue.

**Comment by iblis17** [comment]
(hmm, I think `treelike` is internal use only.)

**Comment by baggepinnen** [comment]
If it's for internal use only, what is the recommended way of creating user defined custom layers composed of simpler layers?

**Comment by MikeInnes** [comment]
Yes, this is the right thing to do. The built-in layers like `Dense` are intentionally not supposed to be "special" compared to user-defined layers, so you can freely use them as a template.

Definitely needs more docs, I'll add that when I can.

**Comment by MikeInnes** [comment]
I added a note on `treelike` in https://github.com/FluxML/Flux.jl/commit/e51268caf57cb259a74a6f7f71bc4235b8891d90, which I think is enough to get people going with this. Happy to add more detail if people need it.
