### ISSUE TITLE
Support Colors.jl v0.10 and v0.11

### ISSUE THREAD

**Issue by oschulz** [FluxML/Flux.jl#1002]
Flux is currently blocking updates of Colors.jl.

**Comment by oschulz** [comment]
(Some packages now require Colors.jl >= v0.10, e.g. ProfileSVG)

**Comment by MikeInnes** [comment]
A PR would be great. Ideally we'd update the Colors version in the manifest to make sure CI passes, too.

**Comment by johnnychen94** [comment]
should be closed by #1046

**Comment by oschulz** [comment]
Thanks - sorry, I kinda forgot about the PR.
