### ISSUE TITLE
Cost functions don't show up in documentation

### ISSUE THREAD

**Issue by scimas** [FluxML/Flux.jl#1003]
Even though the cost function documentation is referenced in [`layers.md`](https://github.com/FluxML/Flux.jl/blob/master/docs/src/models/layers.md#cost-functions), it doesn't show up on [fluxml.ai](https://fluxml.ai/Flux.jl/stable/models/layers/).

I'm not sure why that happens, but my guess is the lack of documentation for `mse`, `crossentropy` and `logitcrossentropy`. Perhaps not finding documentation for `mse` makes the documentation building system assume there is no documentation for any of the items in that section.

And with the open issues / PRs about numerical stability of `crossentropy` and `logitcrossentropy` I'm not sure whether you want to document those functions at all.

**Comment by bhvieira** [comment]
I guess they must be exported to appear there?

**Comment by scimas** [comment]
That could be it too.

In that case, IMO, they should be exported or the documentation should be added in by some other means, since there are places in the documentation where some of these functions are used.

**Comment by CarloLucibello** [comment]
will be fixed in #1041
