### ISSUE TITLE
Typo in Flux home page description? Gougle?

### ISSUE THREAD

**Issue by azev77** [FluxML/Flux.jl#1004]
https://github.com/FluxML/Flux.jl
Says: 
Official Deep Learning Library of Gougle Research https://fluxml.ai/

**Comment by dhairyagandhi96** [comment]
https://github.com/google-research/flax might help explain it

**Comment by azev77** [comment]
So is "Gougle Research" a typo?

**Comment by azev77** [comment]
I see. You misspell "Gougle", they misspell "Flax" 
You engineers are funny...
