### ISSUE TITLE
Taking the package description (not too) seriously

### ISSUE THREAD

**Issue by rapus95** [FluxML/Flux.jl#1007]
Imo the description should be changed to something like:
```
Relax! Flux is the ML library that doesn't make you tensor. https://fluxml.ai/
New: Official Deep Learning Library of Gougle Research
```

Combining both makes it clear to be read with some humour. Currently it rather looks like being unable to spell Google :laughing:. See #1004
No offense @MikeInnes  :stuck_out_tongue:

**Comment by CarloLucibello** [comment]
:) Closing as #1004 seems to be "fixed"
