### ISSUE TITLE
freeze parameters

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#1022]
I guess this came out already, but I couldn't find the corresponding issue. 
The question is: how do I freeze (i.e. no gradient computations and updates) some specific parameter in a Flux model?
The best solution that comes to my mind is to implement a dictionary-like `delete!` method for the `Zygote.Params` type, so that freezing the bias term in the first layer of my network would look like this:
```julia
opt = ADAM(η)
ps = params(model)
delete!(ps, model.layers[1].bias)  # <-- Proposed Solution: implement delete! for Zygote.Params
gs = Flux.gradient(ps) do
	ŷ = model(x)
        loss(ŷ, y)
end
Flux.Optimise.update!(opt, ps, gs)
```
Should I make a PR to Zygote? Or is there something better we can do?

**Comment by bhvieira** [comment]
Give a look at `trainable`, it gets the parameters in a callable. With some overloading I think it's possible to get it working.

**Comment by CarloLucibello** [comment]
Problem is I don't want to define custom types, I want to freeze part of a model as it is.

Another possibility is to add a `frozen` mask inside Params

**Comment by bhvieira** [comment]
You can simply not pass the weights into `param` as well, even though it does not sound as the most "programmatic" way of doing it

**Comment by bhvieira** [comment]
This has been mentioned in #1001 as well

**Comment by foldfelis** [comment]
Hello @CarloLucibello , the function `delete!` defined [here](https://github.com/FluxML/Zygote.jl/blob/ac3d3601f7e1e8036774012e5a64f2fa2e79335f/src/compiler/interface.jl#L71) provides a way to remove parameter from `Zygote.Param`. 

I've implemented two APIs that freeze parameter and layers. Please check #1101 out, the detail of usage is mentioned in the document.

**Comment by CarloLucibello** [comment]
with `delete!` we are pretty much covered here. documentation in https://fluxml.ai/Flux.jl/stable/models/advanced/#Freezing-Layer-Parameters-1.
