### ISSUE TITLE
Ways to freeze some part of a functor during training

### ISSUE THREAD

**Issue by xukai92** [FluxML/Flux.jl#1034]
For example, I'd like my NN in which all the bias of convolution layers are freezed to 0s. What should I do?

**Comment by dhairyagandhi96** [comment]
Solved by #873

**Comment by xukai92** [comment]
Great. We shall close this issue after #873 is merged.

**Comment by CarloLucibello** [comment]
related to #1022

**Comment by dhairyagandhi96** [comment]
Closing through #873
