### ISSUE TITLE
Flux compat with Juno?

### ISSUE THREAD

**Issue by caseykneale** [FluxML/Flux.jl#1036]
Trying to upgrade my Juno version to the latest greatest. Flux is holding it back?

https://github.com/FluxML/Flux.jl/blob/fe85a38d78e225e07a0b75c12b55c8398ae3fe5d/Project.toml#L32

```
ERROR: Unsatisfiable requirements detected for package Flux [587475ba]:
 Flux [587475ba] log:
 ├─possible versions are: [0.4.1, 0.5.0-0.5.4, 0.6.0-0.6.10, 0.7.0-0.7.3, 0.8.0-0.8.3, 0.9.0, 0.10.0-0.10.1] or uninstalled
 ├─restricted to versions 0.10.1 by an explicit requirement, leaving only versions 0.10.1
 └─restricted by compatibility requirements with Juno [e5e0dc1b] to versions: [0.4.1, 0.5.0-0.5.4, 0.6.0-0.6.10, 0.7.0-0.7.3, 0.8.0-0.8.3, 0.9.0] or uninstalled — no versions left
   └─Juno [e5e0dc1b] log:
     ├─possible versions are: [0.5.0-0.5.5, 0.6.0, 0.7.0-0.7.2, 0.8.0] or uninstalled
     └─restricted to versions 0.8.0 by an explicit requirement, leaving only versions 0.8.
```
Out of curiousity why does Flux depend on Juno?

**Comment by dhairyagandhi96** [comment]
Ah, prolly easy to do a compat PR to general for this. Thanks for reporting!

We use Juno internally to show a progress bar in the ide

**Comment by caseykneale** [comment]
cool :), yea its not a big deal, just figured you all should know. But - honestly you all would have figured it out later today or early tomorrow :P

**Comment by SebastianM-C** [comment]
For progress logging you don't need to depend on Juno explicitly (see http://docs.junolab.org/latest/man/juno_frontend/#Progress-Meters-1). I think that you could just use `@info` or `@logmsg` with `progress` as argument and make sure that the progress bar is destroyed after it is no longer needed.

**Comment by ChrisRackauckas** [comment]
This is how you do it:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/10efbd7e331f181379118d9e8e4b6a4c5e2216b8/src/solve.jl#L89

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/311726795dabdabe50a8392d753213b6d5d74c2e/src/integrators/integrator_utils.jl#L132-L136

**Comment by caseykneale** [comment]
This appears fixed - should I close the issue?
