### ISSUE TITLE
flip function assumes the input sequence is a Vector or List, it can be Matrix as well. 

### ISSUE THREAD

**Issue by sambitdash** [FluxML/Flux.jl#1042]
The `flip` https://github.com/FluxML/Flux.jl/blob/88b0c65d722697e0890774f1a660df6512bb41fc/src/layers/recurrent.jl#L57

function assumes the input sequences are a list but mostly the data can be in matrix form. Multiplying with a cross-diagonal identity matrix can achieve this effectively. Moreover, Zygote does not support reverse of matrices.

**Comment by bhvieira** [comment]
Surely, but I don't see the point. Can you provide an example where flipping a matrix is necessary/useful?

**Comment by sambitdash** [comment]
In the recurrent network the xs can be a matrix and flip may be needed for all column elements.

**Comment by bhvieira** [comment]
In Flux it can't. Flux expects an array of arrays.

**Comment by sambitdash** [comment]
It's better to have matrices than vector of vectors.

**Comment by bhvieira** [comment]
I mean, that can make sense (specially if the 'timelike' dimension is the first index, due to memory addressing), but it's not the way Flux operates right now.

**Comment by sambitdash** [comment]
Anyway, writing a flip for matrices is just multiplying with cross-diagonal matrix so the workaround is not so hard. But, use of matrices makes the library much better usability is what I felt.

**Comment by bhvieira** [comment]
@sambitdash which dimension of the matrix would you flip though? It makes sense only to flip the time-like dimension. Which one is it? What if you have a batch dimension?

**Comment by sambitdash** [comment]
My problem needed the time dimension flip. But guess dimension as a parameter can be useful.

**Comment by CarloLucibello** [comment]
flip doesn't exist anymore
