### ISSUE TITLE
train!() hasn't been export in Flux.jl

### ISSUE THREAD

**Issue by zhenyuwei99** [FluxML/Flux.jl#1048]
When I tried to use train!() after I add Flux.jl through Pkg, I meet error: "no method match train!()"

When I open the Flux.jl in "./src",  I found this function was not exported in line 19, wondering anything wrong with this function?

**Comment by dhairyagandhi96** [comment]
It's so that generic sounding functions avoid cluttering the namespace. We see it already with `params` when used alongside BenchmarkTools.

**Comment by zhenyuwei99** [comment]
So I need to code "using Flux: train!" in the beginning to use this function right?


> It's so that generic sounding functions avoid cluttering the namespace. We see it already with `params` when used alongside BenchmarkTools.

Thx for ur reply. So I need to code "using Flux: train!" in the beginning to use this function?

**Comment by CarloLucibello** [comment]
yes

**Comment by dhairyagandhi96** [comment]
Closing this now, feel free to open a new issue or repoen this if you feel train needs to be exported
