### ISSUE TITLE
Using Flux.train! with train and test DataLoaders?

### ISSUE THREAD

**Issue by anandijain** [FluxML/Flux.jl#1081]
For similarity to tensorboard and other loggers, I would like to be able to sample from a test `DataLoader` to call in the `evalcb()` or as an argument to `train`:

Example:
```julia
train_loader = DataLoader(x_train, y_train)
test_loader = DataLoader(x_test, y_test)
...
Flux.train!(loss, ps, ncycle(train_loader, 10), opt, cb=test_loader)
or 
Flux.train!(loss, ps, ncycle(train_loader, 10), opt, eval=test_loader)
```
What are easy ways to use two dataloaders with `train`?

Thanks!

**Comment by CarloLucibello** [comment]
you can define a callback function computing metrics on the test loader: 
```julia
function cb()
   for (x,y) in test_loader
       ...
   end 
end
```
or you can bypass entirely the `train!` function in favour of loops, see https://github.com/FluxML/model-zoo/blob/master/vision/lenet_mnist/lenet_mnist.jl
