### ISSUE TITLE
revisit DataLoader api

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#1088]
Add more consistency to the current design between the cases `DataLoader(X)`, `DataLoader(X, Y)`. As stated by @MikeInnes 
"""
It's not good that DataLoader(X) returns batches of X but DataLoader(X, Y) returns a tuples of batches. The special case in train! is not great either, since it's supposed to be simple and obvious.

There are two options here: either have DataLoader(X) return a tuple, or only allow one input but use DataLoader((X, Y)) to return tuples. Then one can write DataLoader((Xs...,)) without ambiguity about what the type will be.

The former might be a good option insofar as it makes it easy to remove the train! special case. It'd also be easy to tell people to write train!(..., zip(loader), ...) to wrap the iterator output in a tuple.
"""

**Comment by cossio** [comment]
Close?
