### ISSUE TITLE
overflow protection in sigmoid does not work

### ISSUE THREAD

**Issue by pevnak** [FluxML/Flux.jl#109]
Hi,
I think that the overflow protection of sigmoid in NNLib/src/activation.jl:10 does not work.
invoking
```
using Flux
o = Flux.param([-90f0,-90f0])
Flux.Tracker.back!(sum(Flux.σ.(o)));
```
returns NaNs in `o.grad`.
I have checked and the sigmoid with protection is not invoked.

**Comment by simonbyrne** [comment]
Try adding the definition:
```
function Flux.σ{T}(x::ForwardDiff.Dual{T})
    w = Flux.σ(ForwardDiff.value(x))
    ForwardDiff.Dual{T}(w, w*(1-w)*ForwardDiff.partials(x))
end
```

@jrevels is there a better way to custom-define derivatives?

**Comment by jrevels** [comment]
> `@jrevels` is there a better way to custom-define derivatives?

There's not an exposed API for it, but the best/simplest way is to add a diffrule for `Flux.σ` via the [DiffRules](https://github.com/JuliaDiff/DiffRules.jl) package, and then call `@eval $(ForwardDiff.unary_dual_definition(Flux, :σ))`.

**Comment by pevnak** [comment]
Works like a charm.
Thank you very much for help!
Best wishes,
Tomas

**Comment by pevnak** [comment]
The solution suggested by @jrevels would require NNlib to be installed, because it has the sigmoid function defined. Is it a sound solution? If DiffRules would serve as a master-package for most auto-diff packages, then yes. Otherwise, it would seems to me that adding piece of code suggested by @simonbyrne would be sufficient and would require DiffRules to depend on NNlib. 
I do not really know a good solution here. Alternatively, to put into DiffRuless something like

```
@define_diffrule ???.sigmoid(x)  = :( w = ifelse(x<-80,0,1/(1+exp(-x))); w*(1-w))
```
but I do not know, if eval suggested by Jarett would work. That eval should be then put into NNlib.

**Comment by MikeInnes** [comment]
This should be fixed with https://github.com/FluxML/NNlib.jl/commit/74e3fa01d6d4aa9d4e4eef3bf48ee93ebe6aada6.
