### ISSUE TITLE
batched_mul causes a 'cannot take the CPU address of a CuArray' error on GPU

### ISSUE THREAD

**Issue by nirmal-suthar** [FluxML/Flux.jl#1090]
I think this issue is similar to [https://github.com/FluxML/Flux.jl/issues/581](https://github.com/FluxML/Flux.jl/issues/581) and [https://github.com/JuliaGPU/CuArrays.jl/issues/264](https://github.com/JuliaGPU/CuArrays.jl/issues/264)
```
julia> using Flux , CuArrays
julia> batched_mul(gpu(rand(1024,3,32)), gpu(rand(3,3,32)))
ERROR: ArgumentError: cannot take the CPU address of a CuArray{Float32,3,Nothing}
Stacktrace:
 [1] unsafe_convert(::Type{Ptr{Float32}}, ::CuArray{Float32,3,Nothing}) at /home/nirmal/.julia/packages/CuArrays/A6GUx/src/array.jl:211
 [2] batched_mul!(::CuArray{Float32,3,Nothing}, ::CuArray{Float32,3,Nothing}, ::CuArray{Float32,3,Nothing}) at /home/nirmal/.julia/packages/NNlib/FAI3o/src/gemm.jl:82
 [3] batched_mul(::CuArray{Float32,3,Nothing}, ::CuArray{Float32,3,Nothing}) at /home/nirmal/.julia/packages/NNlib/FAI3o/src/batched/batchedmul.jl:16
 [4] top-level scope at REPL[2]:1
```

**Comment by mcabbott** [comment]
It looks like the CPU version is getting called on CuArrays. 

What version of NNlib is this on? v0.6.5 https://github.com/FluxML/NNlib.jl/blob/v0.6.5/src/batched/batchedmul.jl calls `batched_gemm!` always, but after that it should only be called for `StridedArray`. 
https://github.com/FluxML/NNlib.jl/blob/master/src/batched/batchedmul.jl#L40 which ought to exclude CuArray (but can you check that? `gpu(rand(2,2,2)) isa StridedArray`).

**Comment by nirmal-suthar** [comment]
> What version of NNlib is this on? v0.6.5 
> 
Yes, even tried on v0.6.6

> (but can you check that? gpu(rand(2,2,2)) isa StridedArray).
> 

```
julia> gpu(rand(2,2,2)) isa StridedArray
true
```
I tried using `] add CuArrays#master` but it showed

ERROR: Unsatisfiable requirements detected for package CUDAdrv [c5f51814]:
 CUDAdrv [c5f51814] log:
 ├─possible versions are: [0.8.0-0.8.6, 0.9.0, 1.0.0-1.0.1, 2.0.0, 3.0.0-3.0.1, 3.1.0, 4.0.0-4.0.4, 5.0.0-5.0.1, 5.1.0, 6.0.0-6.0.1, 6.1.0, 6.2.0] or uninstalled
 ├─restricted to versions 6.0.1-6 by CuArrays [3a865a2d], leaving only versions [6.0.1, 6.1.0, 6.2.0]
 │ └─CuArrays [3a865a2d] log:
 │   ├─possible versions are: 1.7.0 or uninstalled
 │   └─CuArrays [3a865a2d] is fixed to version 1.7.0
 └─restricted to versions 6.0.0 by an explicit requirement — no versions left

**Comment by mcabbott** [comment]
OK, thanks, we should change that `StridedArray`. 

There's a zoo of other packages which I think need to be on master, there's a list here: https://github.com/JuliaGPU/CuArrays.jl/pull/619#issuecomment-596930628

Or you could ask nicely for a release, not sure how much of a pain that is.

**Comment by nirmal-suthar** [comment]
Yes, it worked after running 
` ] add CUDAdrv#master CuArrays#master CUDAnative#master GPUArrays#master CUDAapi#master`

Thanks
