### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by GHTaarn** [FluxML/Flux.jl#1097]
The "end" hyperlink at the bottom of docs/src/apis/backends.md is to a URL that does not exist

**Comment by bhvieira** [comment]
Where does that doc exist though? There's no `apis` folder or `backends.md` file anywhere in the repo I could find

**Comment by GHTaarn** [comment]
Okay, maybe it has been deleted from the master branch then, I am sorry for the disturbance if this is the case. The complete URL is https://github.com/FluxML/Flux.jl/blob/1c317eeefec910170cc72a4fe09ac54e187b3624/docs/src/apis/backends.md

**Comment by bhvieira** [comment]
That's definitely outdated. I had no idea Flux actually had backends other than NNlib 😅

**Comment by bhvieira** [comment]
Backends were removed in https://github.com/FluxML/Flux.jl/commit/536949891d600b3173c962506c9611fed40108f4

**Comment by GHTaarn** [comment]
Okay, then I will close the case, sorry for the disturbance.

**Comment by bhvieira** [comment]
Nah, no need to say sorry. You're helping an open source project, as am I. Thanks for helping!
