### ISSUE TITLE
Can we have array of params?

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#111]
```
σ = param(1.)
b = param(0.)

Σ=[σ b; b σ] 
#>MethodError: Cannot `convert` an object of type TrackedArray{…,Array{Float64,0}} to an object of type Float64
```
Is it possible to have an array of params? 

I think this is distinct from a param(array). For instance, above restricts the matrix to that symmetric form whereas param(array) would allow each entry to be adjusted separately.

**Comment by iblis17** [comment]
I think... you want `cat`?

**Comment by iblis17** [comment]
```julia
Base.cat(dims, A::Flux.Tracker.TrackedArray...) = cat(dims, Flux.Tracker.data.(A)...)
```

**Comment by MikeInnes** [comment]
cat would work for this, although we'd have to define gradients as well. It'd also be nice to fix the above syntax to not give a weird error.

**Comment by oschr** [comment]
There is a weird hack for making it work (gradients will be calculated just fine)

julia> σ = param(1.)
       b = param(0.)
       Σ=[1 0;0 1].*σ+[0 1;1 0].*b
Tracked 2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

(performance hit ofc exists, it's only ~2 slower and will probably won't matter)

The issue is actually similar to https://github.com/FluxML/Flux.jl/issues/114.

It is possible to add bunch of multiple dispatch workarounds like this everywhere (Sorry, I am really new to Julia :( ), but it might be no longer relevant if switch to Cassette happens.

P.S. What seems to be happening is that we want to Tracker.Array to be monadic or something similar.

**Comment by MikeInnes** [comment]
Nice trick. Hopefully it helps perf that you only need to construct sigma once.

Cassette doesn't really change the game here, you'd still need a derivative of `cat` to be implemented; but it'd probably be a fair bit easier to do that.

**Comment by jessebett** [comment]
As you've probably guessed the reason I'm looking for this is mainly because I'm trying to enforce structure in my matrix. 

For example, if I'm trying to enforce a diagonal covariance matrix and have each diagonal entry be a tracked param.
Things I intuitively tried to have work for this example and the errors:

```
diagm([1, 2]) = [1 0; 0 2] 
diagm([param(1),param(2)]) #=> MethodError: no method matching zero(::Type{TrackedArray{…,Array{Float64,0}}})

param([1,2]).*eye(2)

**Comment by jessebett** [comment]
uhhhh, I accidentally closed this >.>

**Comment by jessebett** [comment]
(pretty clearly) what inspired this issue is that I'm trying to enforce matrix structure in my tracked arrays.

For instance, I'd like to have a diagonal covariance matrix, and so I only need the parameters of that diagonal tracked.

As per @oschr's suggestion, this works for this diagonal example:
```
σ = param([1.,5.])
Σ = σ.*eye(2) #=>  Tracked 2×2 Array{Float64,2}:
                                1.0  0.0
                                0.0  5.0
```
Though I do have a question about this method: isn't it inefficient to keep all those off-diagonal terms tracked if I'm intentionally giving the problem a diagonal structure? Is it possible to have them as untracked 0s, or is that worse because now the array has different types in it?

Also, I tried using `diagm` to enforce this structure instead:
```
diagm([param(1.),param(5.)]) # => MethodError: no method matching zero(::Type{TrackedArray{…,Array{Float64,0}}})
```

**Comment by MikeInnes** [comment]
It's actually pretty easy to add support for `diagm` (https://github.com/FluxML/Flux.jl/commit/a4bf5936b0e300f51f2cb8670afe7cf60a72ebd0) – does that get you what you need here?

**Comment by jessebett** [comment]
Adding support for `diagm` helps for this example (thanks).

But I think generally what I was hoping for was structured matrices generally. 

For example, `L =  LowerTriangular(param([1 2; 3 4]))` 
does give us `[1.0 (tracked) 0.0 (tracked); 3.0 (tracked) 4.0 (tracked)]`

But doing something like `L*L'` results in `MethodError: Cannot `convert` an object of type Flux.Tracker.TrackedNumber{Float64} to an object of type Float64`

even though `param([1.0 0.0; 3.0 4.0])*param([1.0 0.0; 3.0 4.0])'` works fine.

I think this might be getting off the topic of this issue at this point. And I don't know how much your new tracked numbers will change the game here. But yes, the key reason for this was to enforce structure in the matrix and optimize on those parameters. Like in the above case, to learn a diagonal covariance matrix. Or in this case now, to learn the parameters of the cholesky decomposition for a full covariance matrix. (Though in the meantime this can be done with tricks like masking)

**Comment by MikeInnes** [comment]
Yes, the tracked numbers make it much easier to support stuff like this – I've pushed a fix to do so. I'm not certain I want to support `Array{TrackedReal}` in general though as it may cause silent AD issues in some cases.

It would be much better to add direct support for things like `LowerTriangular` where possible; you'll probably even find that masking is faster than using `TrackedReal`s, unless they are really this small in real examples.
