### ISSUE TITLE
no method matching apply!

### ISSUE THREAD

**Issue by SebastianCallh** [FluxML/Flux.jl#1111]
Using a custom Optimiser seems to break with `Flux.train!`. 

Construct a custom optimiser by copying [official Descent](https://github.com/FluxML/Flux.jl/blob/df3f904f7c34f095562693b6a9ca67047319dea0/src/optimise/optimisers.jl#L32):
```
mutable struct MyDescent
  eta::Float64
end

function apply!(o::MyDescent, x, Δ)
  Δ .*= o.eta
end

opt = MyDescent(0.01)
apply!(opt, gpu(zeros(3)), gpu(rand(3)))
```
This block outputs
`3-element CuArrays.CuArray{Float32,1,Nothing}:
 0.008076402
 0.005289067
 0.009739006`
and all looks good. However, swapping out regular `Descent `for `MyDescent` in `Flux.train!(loss, ps, train_set, opt)` gives `MethodError: no method matching apply!(::MyDescent, ::CuArrays.CuArray{Float32,4,Nothing}, ::CuArrays.CuArray{Float32,4,Nothing})`

Output of `Pkg.status()`:
-   [fbb218c0] BSON v0.2.5
-   [336ed68f] CSV v0.5.26
-   [3895d2a7] CUDAapi v3.1.0
-   [3a865a2d] CuArrays v1.7.2
-   [a93c6f00] DataFrames v0.20.2
-   [aae7a2af] DiffEqFlux v1.4.0
-   [0c46a032] DifferentialEquations v6.11.0
-   [31c24e10] Distributions v0.22.5
-   [587475ba] Flux v0.10.2
-   [7073ff75] IJulia v1.21.1
-   [429524aa] Optim v0.20.2
-   [1dea7af3] OrdinaryDiffEq v5.29.0
-   [91a5bcdd] Plots v0.29.4
-   [f3b207a7] StatsPlots v0.14.0

From [official documentation](https://fluxml.ai/Flux.jl/v0.10/training/optimisers/#Optimiser-Interface-1) it looks like I did the right thing, but something is clearly off.

**Comment by dhairyagandhi96** [comment]
You probably need `Flux.apply!` as the method definition to add methods to the function. Could clarify in the docs.

**Comment by SebastianCallh** [comment]
Thank you! Looks like it isn't exported, so you have to refer to it as `Flux.Optimise.apply!`. Would you appreciate a PR with the docs changes to the `docs` branch?

**Comment by dhairyagandhi96** [comment]
Absolutely!
