### ISSUE TITLE
gpu function does not fully work on structs within structs

### ISSUE THREAD

**Issue by clintonTE** [FluxML/Flux.jl#1118]
I suppose this could be a feature request for recursive implmentation (maybe optional) if the behavior is as intended. 

```Julia
using Revise, CUDAapi, Flux
import CuArrays
struct MoreParam{Tc<:AbstractVector, Td<:AbstractVector}
  c::Tc
  d::Td
end

struct MWEStruct{Ta<:AbstractVector, Tb<:AbstractVector, Tmoreparam<:MoreParam}
  a::Ta
  b::Tb
  moreparam::Tmoreparam
end

MWEStruct(N) = MWEStruct(rand(N), rand(N), MoreParam(rand(N), rand(N)))

(m::MWEStruct)(x) = x

function mwe(N)
  Flux.@functor MWEStruct
  
  cpustruct = MWEStruct(N)
  println("type of cpu struct: ", typeof(cpustruct))
  gpustruct = cpustruct |> gpu
  println("type of gpu struct: ", typeof(gpustruct))
end

mwe(10)
```

output:
```Julia
type of cpu struct: MWEStruct{Array{Float64,1},Array{Float64,1},MoreParam{Array{Float64,1},Array{Float64,1}}}
type of gpu struct: MWEStruct{CuArray{Float32,1,Nothing},CuArray{Float32,1,Nothing},MoreParam{Array{Float64,1},Array{Float64,1}}}
```

**Comment by DrChainsaw** [comment]
I'm not sure this is what you mean, but it is recursive by default, you just must implement the functor method for MoreParam:

``´julia
julia> Flux.@functor MoreParam

julia> mwe(10)
type of cpu struct: MWEStruct{Array{Float64,1},Array{Float64,1},MoreParam{Array{Float64,1},Array{Float64,1}}}
type of gpu struct: MWEStruct{CuArray{Float32,1,Nothing},CuArray{Float32,1,Nothing},MoreParam{CuArray{Float32,1,Nothing},CuArray{Float32,1,Nothing}}}
```

The default implementation of functor just silently returns nothing which is why you get what you get in your example. 

I sometimes wonder why it does not either defaults to throwing an exception or to returns all fields and the constructor, especially after I have spent half an hour trying to understand why my parameters don't update. Sorry if this was what you meant all along...

**Comment by clintonTE** [comment]
Oh wow, it completely slipped my mind to try `@functor` on `MoreParam`. 

I'm actually running into another issue that might be related to what you are seeing- I'll close this and put it in a separate thread.
