### ISSUE TITLE
SGD exported but not defined

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#1121]
`Flux.Optimise` exports `SGD`, but SGD is not defined anywhere, likely renamed `Descent` at some point. When did that happen? Do we want to remove the SGD export or use it as an alias for Descent? I'm a bit torn here: I like SGD being an easily discoverable common name, but I don't like having two names for the same thing

**Comment by dhairyagandhi96** [comment]
Yes please! That must have been an oversight.

We should remove SGD and only keep Descent

**Comment by sivapvarma** [comment]
Could you link the discussion about the interface change, I think SGD is more informative than Descent.

**Comment by bhvieira** [comment]
> Could you link the discussion about the interface change, I think SGD is more informative than Descent.

Descent is stochastic if you make it so. The difference between GD, SGD and MiniBatchSGD is the number of data you passes to it.

**Comment by bhvieira** [comment]
SGD was deprecated in #379
