### ISSUE TITLE
outdim not defined&dont know how to update flux from 0.90 to 0.10

### ISSUE THREAD

**Issue by duyanran** [FluxML/Flux.jl#1154]
sorry that i am new to flux and julia ,so my questions might be stupid 
can someone help me ?
thanks!!
![image](https://user-images.githubusercontent.com/56710672/80671960-e6a1f280-8add-11ea-8731-954c8c1a36ce.png)
![image](https://user-images.githubusercontent.com/56710672/80672039-22d55300-8ade-11ea-9729-40d61e224fe7.png)

**Comment by CarloLucibello** [comment]
probably there is some package blocking the update. You can understand which one by forcing the update with
```julia
pkg> add Flux#v0.10.4
```
