### ISSUE TITLE
ADADelta not training parameters

### ISSUE THREAD

**Issue by masaers** [FluxML/Flux.jl#1158]
I tried training (using `train!`) a model (simple `Chain` of `Dense` layers) with `ADADelta` in Flux v0.10.4, and the parameters did not update. Same model trained just fine with `ADAGrad` and `Descent`. I also tried explicitly setting rho both high (0.95) and low (0.01) without seeing any updates.

I'm not familiar enough with the package to give more detained info, just starting out with both Julia and Flux.

I'm running Julia 1.4.1 and training on CPU only (no GPU).

**Comment by ltjkoomen** [comment]
I believe it would help if you could provide a minimal example of the problem, so other people can easily replicate the issue.

**Comment by scimas** [comment]
I just checked the ADADelta `apply!` function in the process of writing a PR (looking at the tests) and yes, ADADelta does absolutely nothing, it just keeps setting the gradient to zero (not approximately zero, absolutely zero). I will need to check what actual calculation it is supposed to do.

This also leads me to question how the `Optimise` testset is passing at all with ADADelta.

Doesn't really need MWE, but here it is anyway:
```julia
using Flux, Flux.Optimise
using Flux: Params

w1 = rand(1, 5)
w2 = rand(1, 5)
loss(x) = Flux.Losses.mse(w1 * x,  w2 * x)
opt = ADADelta()

x = rand(5)
grads = gradient(() -> loss(x), Params([w1]))

# First apply! should set internal state
Optimise.apply!(opt, w1, grads[w1])
@info grads[w1] # zeros

# Should be non-zero now
grads = gradient(() -> loss(x), Params([w1]))
Optimise.apply!(opt, w1, grads[w1])
@info grads[w1] # still zeros, and continues to be zeros
```

**Comment by scimas** [comment]
Okay, looking through the ADADelta paper and the blame history, 29832aca92748721594ea18067de2ba2ad5a077f seems to be the commit that broke it.

@DhairyaLGandhi tagging you because looks like you contributed the working code originally and also because the `Optimise` testset probably needs better testing.

**Comment by DhairyaLGandhi** [comment]
I would run the test from the suite manually and report the results. Why would adding the epsilon alter the results?

**Comment by scimas** [comment]
From the ADADELTA paper regarding calculation of Δx: "... the same constant ϵ is added to the numerator RMS as well. This constant serves the purpose both to start off the first iteration where `Δx₀ = 0` and to ensure progress continues to be made even if previous updates become small."
