### ISSUE TITLE
Loading/saving weights

### ISSUE THREAD

**Issue by staticfloat** [FluxML/Flux.jl#117]
I want to copy weights from one model to another; using `params(model)` I can extract the weights from my model as Tracked Arrays, but how do I load them into another model with a compatible architecture?

**Comment by iblis17** [comment]
please checkout this https://github.com/FluxML/model-zoo/pull/9/files#diff-8202c03a6fbf45333458edba779c58e4R5

**Comment by staticfloat** [comment]
I see, so we just `p[:] = ...` for each `p` in `params()`.  That makes sense.  Thanks.
