### ISSUE TITLE
Define `.<` for tracked arrays

### ISSUE THREAD

**Issue by staticfloat** [FluxML/Flux.jl#118]
```
julia> y_test_hat .< 0.9
ERROR: type Bool has no field value
Stacktrace:
 [1] _collect(::BitArray{1}, ::Base.Generator{BitArray{1},Flux.Tracker.##4#5}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:454
 [2] (::Flux.Tracker.Broadcasted{BitArray{1}})() at /root/.julia/v0.6/Flux/src/tracker/lib.jl:98
 [3] tracked_broadcast(::Function, ::TrackedArray{…,Array{Float64,1}}) at /root/.julia/v0.6/Flux/src/tracker/lib.jl:108
 [4] broadcast(::Function, ::TrackedArray{…,Array{Float64,1}}) at ./broadcast.jl:434
```

**Comment by iblis17** [comment]
I don't think we need this; we do not need to record `.<` for auto diff stuff.
`y_test_hat.data` is enough.

**Comment by staticfloat** [comment]
What happens if I want to define something like a "masking" layer, such that I have `mask!(x, threshold) = x[x .< threshold] = 0` or something like that?  I then have to special-case this layer based on whether or not `x` is a normal array or a tracked array?

**Comment by iblis17** [comment]
> I then have to special-case this layer based on whether or not x is a normal array or a tracked array?

If you need special gradient handling, define them like this.
https://github.com/FluxML/Flux.jl/blob/cab235a57863558aa060a28776f8934d5a0a0ed4/src/tracker/lib.jl#L58-L69

If not, just use normal array

**Comment by staticfloat** [comment]
Ah, I didn't realize that TrackedArrays were automagically peeled when being passed to the forward pass of layers.  My bad.

**Comment by MikeInnes** [comment]
For that specific case you can probably do something like `Flux.value(xs)` to make sure it's not tracked. But it'd be good for us to support non-differentiable broadcasts in general.

I think tracked arrays should "do the right thing" wherever possible, even when it's not a differentiable operation, although that won't be feasible in full generality until Cassette is around.

**Comment by MikeInnes** [comment]
There's another case where this same issue comes up, e.g. if you do `Dense(in, out, x -> 0)`.

**Comment by MikeInnes** [comment]
@staticfloat this is fixed on master, but note that you can't do in-place masking like that. You can do `x .* x .< threshold`. (It also occurs to me that this expression would have worked before that fix, as it's all done in one pass.)
