### ISSUE TITLE
Bug: lower degree polynomial substitute in gradient chain!

### ISSUE THREAD

**Issue by deahhh** [FluxML/Flux.jl#1188]
using Flux
f(x) = 3x^2 + 2x + 1;
df(x) = gradient(f, x)[1]; 
d2f(x) = gradient(df, x)[1]; 
d2f(2) == 6
f(x) = x;
df(2)==1
d2f(2) == 6

**Comment by dhairyagandhi96** [comment]
The case is that the backwards pass had already been computed (and referenced) with the first `f`. I think you want to redefine `df` and `d2f` here.

**Comment by deahhh** [comment]
@dhairyagandhi96 
try the follow code!

using Flux
f(x) = 3x^2 + 2x + 1;
df(x) = gradient(f, x)[1];
d2f(x) = gradient(df, x)[1];
d2f(2) == 6
f(x) = x;
df(2)==1
d2f(2) == 6
df(x) = gradient(f, x)[1]
d2f(x) = gradient(df, x)[1]
d2f(2)

**Comment by bhvieira** [comment]
```
using Flux
f(x) = 3x^2 + 2x + 1;
df(x) = gradient(f, x)[1];
d2f(x) = gradient(df, x)[1];
d2f(2) == 6
d2f(0) == 6
d2f(Inf) == 6 #this one will return a float though
```

**Comment by deahhh** [comment]
> The case is that the backwards pass had already been computed (and referenced) with the first `f`. I think you want to redefine `df` and `d2f` here.

Yes, I found the first f(x) will be substitute automatically, df(x) too, but d2f(x). I tried that, d3f(1) == 0.0, while d3f(x) = gradient(d2f, x)[1], f(x) = 2x^2+1. But, d2f(1) == nothing, while d2f(x) = gradient(df, x)[1], df(x) = gradient(f, x)[1],  f(x) = 2x.
