### ISSUE TITLE
CUDA.jl

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1194]
Installing `CUDA` and then `Flux` (in this order) leaves me with version `0.8.3` of Flux.

I'd guess we have to modify this line:

https://github.com/FluxML/Flux.jl/blob/ddd0f4e747347555894f71ae275ac3906fc87b9e/Project.toml#L33

To be compatible with the new CUDA.jl?

https://discourse.julialang.org/t/psa-cuda-jl-replacing-cuarrays-jl-cudanative-jl-cudadrv-jl-cudaapi-jl-call-for-testing/40205

**Comment by ToucheSir** [comment]
Closing as out of date now that the CUDA.jl transition is well in the rearview mirror.
