### ISSUE TITLE
RNN state dimension with batches

### ISSUE THREAD

**Issue by baggepinnen** [FluxML/Flux.jl#121]
If a model including an RNN layer has been called with batch size `n`, it can not be called with a batch size `m!=n` unless `reset!` is called on the model first. This is due to the cell state being initialized as a vector, but one called with a batch of size > 1, it's being broadcasted to a matrix.

**Comment by MikeInnes** [comment]
Right, once you've called an RNN with `n` inputs, it has to store `n` hidden states to map to those inputs. If you then call it with some other number, we can't know what the hidden state is supposed to be.

We could handle this by auto-resetting, but I think it's probably better just to give a good error message (rather than silently doing the wrong thing in some cases).

**Comment by baggepinnen** [comment]
Then I'm probably confused regarding `truncate` and `reset`. If I'm doing GD as opposed to SGD, am I supposed to call `truncate` or `reset` in between epochs?

**Comment by MikeInnes** [comment]
One way to look at it is that `truncate!` is effectively an optimisation. It allows you to treat one long sequence as chunks of short sequences. Whereas `reset!` completely erases the hidden state, which you want when you are passing a *new* sequence into the RNN that has no relation to previous inputs / data.

Does that clear things up?

**Comment by baggepinnen** [comment]
Ok, so `reset!` should be called when operating on the entire sequence in a batch, since the internal state should start from zero in the beginning of a sequence? My use case is time-series modelling where I have a time-series I want to fit a model to. It is not very long, so I can easily fit the whole sequence into a single batch. If I would split the sequence into subsequences that are adjacent to each other, `truncate!` would be the right thing to do in between batches to speed things up, and `reset` would be called when all sub sequences are processed once, before the next epoch starts?

**Comment by MikeInnes** [comment]
Yeah that's right. See for example the char-rnn model as well, which is a very similar setup.

**Comment by darsnack** [comment]
I think this can be closed. Seems like using `reset!` is still the right thing to do, and I vote for error instead of auto-reset.
