### ISSUE TITLE
Non-descriptive arg in `Conv`: why `filter` intead of `size`?

### ISSUE THREAD

**Issue by bhvieira** [FluxML/Flux.jl#1212]
One of `Conv` parameters is now called `filter` (after #873 was merged.
In my opinion, `size` better described what Flux expects to be supplied by the user: the size of the kernel. Now it reads `filter`, which, to me, sounds like Flux expects the user to supply the actual kernel here, not its size.
If others think it's fine, then I'm ok with that too.

**Comment by levimcclenny** [comment]
Curious where you see this? The source and Flux.jl docs say ```size``` from what I'm seeing, unless you're seeing this somewhere else:

https://github.com/FluxML/Flux.jl/blob/7a32a703f0f2842dda73d4454aff5990ade365d5/src/layers/conv.jl

Keras uses ```kernel_size``` which seems really clear to me.

**Comment by dhairyagandhi96** [comment]
`filter_size` seemed a bit long, but essentially is the intended reading of it. Happy to change it to a nicer / better descriptive name, of course.

@levimcclenny you can go to the drop-down on the bottom of the table of contents and select `dev` to get the dev docs of the unlreleased version.

**Comment by levimcclenny** [comment]
Ah I see now, looking at the example I think it's reasonably clear what the argument is, but without the example could be somewhat confusing. Personal opinion, obviously.
