### ISSUE TITLE
Char RNN errors

### ISSUE THREAD

**Issue by shubhangperiwal** [FluxML/Flux.jl#1215]
batches and chunk are not defined

**Comment by CarloLucibello** [comment]
this is not an informative error report, please provide a MWE or close

**Comment by shubhangperiwal** [comment]
https://fluxml.ai/Flux.jl/v0.2/examples/char-rnn.html

getseqs(chars, alphabet) =
  sequences((onehot(Float32, char, alphabet) for char in chars), nunroll)
getbatches(chars, alphabet) =
  batches((getseqs(part, alphabet) for part in chunk(chars, nbatch))...)
The above functions do not work (either deprecated or non functional)

readstring function is non functional.

**Comment by dave7895** [comment]
This is from the docs at `v0.2`. An up-to-date version can be found in the [model zoo](https://github.com/FluxML/model-zoo), more specifically [here](https://github.com/FluxML/model-zoo/tree/master/text/char-rnn).

**Comment by DhairyaLGandhi** [comment]
I think we can close this since char rnn is stable now
