### ISSUE TITLE
Setting input or output layer size to a float in the Dense constructor should error

### ISSUE THREAD

**Issue by oxinabox** [FluxML/Flux.jl#1217]
This lead to a very confusing bug when I was loading network settings from a file and parsing that file wrong.

If you pass any float in you get a `Dense(1, 1)`

```
julia> Dense(10, 100)
Dense(10, 100)

julia> Dense(10, 100.0)
Dense(1, 1)

julia> Dense(10.0, 100)
Dense(1, 1)
```

**Comment by dhairyagandhi96** [comment]
Related/ kind of dup of https://github.com/FluxML/Flux.jl/issues/1199

**Comment by oxinabox** [comment]
This is a dup of #1199
(it actually the same issue, from the same even I forgot that that one was openned already)
