### ISSUE TITLE
Matrix times OneHotVector product does not check dimensions

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1223]
```
randn(3,7) * Flux.OneHotVector(2,5)
```

That should raise a `DimensionMisMatch` error, since it's multiplying a 3x7 matrix times a vector with 5 elements.

We should do some dimensions checking here:

https://github.com/FluxML/Flux.jl/blob/9ebbe8cb4c3102829454e68f62f4a01342197ba1/src/onehot.jl#L14

**Comment by maerory** [comment]
Addressed in https://github.com/FluxML/Flux.jl/pull/1230,

Hope you would take a look!

**Comment by cossio** [comment]
@maerory Thanks! But maybe better to separate that into two distinct PRs? It's usually better that each PR addresses one thing.

**Comment by maerory** [comment]
@cossio Oops, sorry for my confusion. I will make it into a single PR.

**Comment by maerory** [comment]
@cossio This is now implemented!
