### ISSUE TITLE
Create additional pooling layers

### ISSUE THREAD

**Issue by dnabanita7** [FluxML/Flux.jl#1224]
This issue is in for better co-ordination of the [FluxModels.jl](https://github.com/darsnack/FluxModels.jl) which can be used as a benchmark for Flux.jl. As explained by @darsnack in [this issue](https://github.com/darsnack/FluxModels.jl/issues/1), I will be creating the following pooling layers.

- [x] AdaptiveMeanPool
- [x] AdaptiveMaxPool

**Comment by darsnack** [comment]
Great! A couple of notes:
- AvgPool is implemented in Flux as MeanPool
- You will want your implementation to call any [pooling primitives from NNlib.jl](https://github.com/FluxML/NNlib.jl/blob/master/src/pooling.jl) when appropriate

**Comment by dnabanita7** [comment]
Oh, I should remove AvgPool then.

**Comment by darsnack** [comment]
And probably want to name the layer AdaptiveMeanPool for consistency.

**Comment by dnabanita7** [comment]
shall i make required changes in the NNlib.jl and create adaptivemaxpool and adaptivemeanpool backends too? I will add two functions there only.

**Comment by darsnack** [comment]
I don’t think that’s necessary. Adaptive pooling does the same operation as regular pooling except that the filter window is adjusted dynamically to account for input image size.

The pooling functions in NNlib.jl accept a `PoolDims` object. Your layers in Flux should create this object based on the desired output size when `layer(x)` is called. Then pass that object to NNlib.

**Comment by avik-pal** [comment]
Fixed by #1239
