### ISSUE TITLE
Neural Networks for Image Segmentation 

### ISSUE THREAD

**Issue by ocissor** [FluxML/Flux.jl#1228]
I was searching for Image segmentation models like UNet,PSPNet,LinkNet but I couldn't find them in model zoo so I was thinking of Implementing them in Julia.Please let me know if it is desirable.

**Comment by AStupidBear** [comment]
https://github.com/dhairyagandhi96/UNet.jl

**Comment by ocissor** [comment]
But what about the other networks are they also implemented

**Comment by AStupidBear** [comment]
I didn't see those yet. You may translate implementations in tensorflow or pytorch to Julia by yourself.

**Comment by ocissor** [comment]
okay great I will do that.

**Comment by dhairyagandhi96** [comment]
There is also an implementation of Inception family of models and YOLO at
ObjectDetector.jl

**Comment by CarloLucibello** [comment]
we could add some references to external packages to the model zoo. In any case, closing this since it's not an issue with Flux, but fill free to open a corresponding issue in the model zoo

**Comment by ocissor** [comment]
@CarloLucibello I have implemented PSPNet and made the pull request, just waiting for some update on it.
