### ISSUE TITLE
Multi-dimensional onehot

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1229]
Could we generalize onehot encoding in Flux to more than one or two dimensions? In general, we can have an `N` dimensional binary array, where the first dimension always has exactly one bit on and the rest are off. This represents a onehot encoding of an `N-1` dimensional array where each entry is a category.

An application is a sequence of length `L` where each site can be one of `q` letters. Then one sequence can be onehot encoded as a `q * L` matrix. But to encode a batch of `B` sequences, we need a multi-dimensional `q * L * B` array.

One possible implementation: https://github.com/cossio/OneHot.jl/blob/master/src/array.jl.

I can make a PR if people agree this can be useful in general.

**Comment by CarloLucibello** [comment]
I think this could be useful. Maybe extending the current implementation 
https://github.com/FluxML/Flux.jl/blob/19b45b49d351fc530ab1022eab10c7c5507880f8/src/onehot.jl#L16
to something like
```julia
struct OneHotArray{A<:AbstractArray{OneHotVector, N-1}, N} <: AbstractArray{Bool, N}
...
```
?
