### ISSUE TITLE
how to restrain each element of weights to be nonnegative？

### ISSUE THREAD

**Issue by duyanran** [FluxML/Flux.jl#1250]
Hello，
I‘d like to build a neural network with some layer of its weight elements are nonnegative（ICNN），but I couldn’t find related docs to do so. Or I  have to write a code to set negative parameters to be zero or abs every iteration?
new to flux, really need some  guidance, thanks！！

**Comment by AStupidBear** [comment]
Use `relu` and `mask`.

```julia
M .* relu.(W)
```

where M is the mask which determines whether connections, and W should be initialized to be positive.

**Comment by duyanran** [comment]
> Use `relu` and `mask`.
> 
> ```julia
> M .* relu.(W)
> ```
> 
> where M is the mask which determines whether connections, and W should be initialized to be positive.

thanks for your kindly reply!
but i don't know what exactly to do and what "mask" really is (i didn't find the usage of this in julia as a function or something), could you please give me a example or link ?

**Comment by AStupidBear** [comment]
See https://github.com/frsong/pycog and read the corresponding paper

**Comment by duyanran** [comment]
> See [Train excitatory-inhibitory recurrent neural networks for cognitive tasks](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004792)

thanks a lot~~~~

**Comment by CarloLucibello** [comment]
you could also use e custom layer that perform `exp.(layer.W) * x`  in the forward pass

**Comment by duyanran** [comment]
> you could also use e custom layer that perform `exp.(layer.W) * x` in the forward pass

thanks for your kind reply !
