### ISSUE TITLE
ERROR: Can't differentiate foreigncall expression

### ISSUE THREAD

**Issue by cody-rucker** [FluxML/Flux.jl#1257]
I have run into an issue when trying to take second derivatives of a chain of dense affine layers with respect to the input. 

 'u = Chain(
       Dense(1,5, σ),
       Dense(5, 1))`

There is no issue with taking a single derivative

`du(x) = gradient(() -> sum(u(x)), params(x))`

but if I try differentiating again, 

`ddu = gradient(params(x)) do
        sum(du(x)[x])
        end`

I get [ERROR: Can't differentiate foreigncall expression](https://gist.github.com/cody-rucker/a407c4d757b253ed9a77f2cb9862147b) . I would like to use flux to differentiate functions with respect to the input and later be able to compute the gradient with respect to the neural net parameters. I have been able to do this if I explicitly define all functions with respect to the input and each parameter but would like to use Flux's Chain() and Dense() functions. Should Flux be able to do this or am I reaching too far here? I am new to all this and trying to figure it out so I  apologize  if this has a straightforward solution that I am not getting.

**Comment by rbitr** [comment]
@cody-rucker I found this searching for exactly the same problem. Were you able to solve this?

**Comment by cody-rucker** [comment]
No, I just ended up symbolically differentiating the NN and coding that up instead of using AD.

**Comment by stasti** [comment]
i have the same issue. it worked with Flux v0.8.3

**Comment by stasti** [comment]
i have this issue too.
