### ISSUE TITLE
Stopping condition callbacks

### ISSUE THREAD

**Issue by ChrisRackauckas** [FluxML/Flux.jl#127]
It would be nice if the callback could handle stopping conditions. For example, I could see it taking in the current weights and the current loss, and splitting back a boolean for whether or not to continue. Then it would be like:

```julia
evalcb = (weights,cur_loss) -> (@show(loss(xinv, yinv)); cur_loss < 5e-6)
```

would let the training halt on a condition.

**Comment by MikeInnes** [comment]
Good idea. I've implemented this as an extension of callbacks; you can just return `:stop` and it'll do so.

I don't think we need to pass information about the model to the callback, because you can just close over it.
