### ISSUE TITLE
Expose the RNGs used in initialization to the user

### ISSUE THREAD

**Issue by ablaom** [FluxML/Flux.jl#1274]
It seems that there is currently no interface point for users to specify the random number generators used in Flux, unless they write their own initialisers. For reproducibility this would be good to add.

Maybe something like `glorot_uniform(rng::AbstractRNG, dims...)=...`, etc

**Comment by CarloLucibello** [comment]
We should do this. Meanwhile, the current way to ensure reproducibility is to seed the global rng

**Comment by johnnychen94** [comment]
`glorot_uniform(rng::AbstractRNG, dims...)` looks good.

I assume we don't want to expose these to layers, for example, we don't want to do `Conv(...; rng=Random.default_rng())`, right?

**Comment by CarloLucibello** [comment]
> I assume we don't want to expose these to layers, for example, we don't want to do Conv(...; rng=Random.default_rng()), right?

We could expose it if anyone feels it is needed. @ablaom what's your use-case? You think we should add  a `rng` keyword to layers or you are happy enough with #1292 ?

**Comment by ablaom** [comment]
Thanks for this. I think the extra convenience proposed could be added later if the status quo proves annoying.
