### ISSUE TITLE
Recurrent layers can't use Zeros() as bias

### ISSUE THREAD

**Issue by DrChainsaw** [FluxML/Flux.jl#1279]
Not something I need, but maybe good to have for consistency.

Reason is that hidden state and bias must be of the same type and I guess that having the hidden state as Zeros kinda defeats the purpose of the layer. 

Might be workaroundable by using another initialization of the hidden state as the hidden state of the cell is only used by Recur when creating it, but I haven't bothered to try it.

**Comment by DhairyaLGandhi** [comment]
Probably just add a type annotation there that adds a union. Worth trying.

**Comment by DrChainsaw** [comment]
Maybe even better to get rid of the hidden state in the cells as it appears to be redundant: #1089
