### ISSUE TITLE
Failed to load Flux on windows machine 

### ISSUE THREAD

**Issue by yogeshnakrani9** [FluxML/Flux.jl#1306]
julia> using Flux
Downloading artifact: CUDA110
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (504) Gateway Timeout."
At line:12 char:1
+ $webclient.DownloadFile("https://pkg.julialang.org/artifact/4747fe73a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

I am having above error on my windows machine while loading Flux module

**Comment by YorkerCoder** [comment]
So i tested it out on linux and it worked straight out of the box, but I did find a way to make it work on Windows. If you explicitly `] add CUDA` it seems to work out.

**Comment by CarloLucibello** [comment]
I'll close this assuming the issue doesn't persist, feel free to reopen in case it does
