### ISSUE TITLE
Basic example in docs fails

### ISSUE THREAD

**Issue by grero** [FluxML/Flux.jl#1311]
I wanted to use Flux for a simple gradient descent optimisation, as in this example from the docs:

```julia
using Flux

W = rand(2, 5)
b = rand(2)

predict(x) = (W * x) .+ b
loss(x, y) = sum((predict(x) .- y).^2)

x, y = rand(5), rand(2) # Dummy data
l = loss(x, y) # ~ 3

θ = params([W, b])
grads = gradient(() -> loss(x, y), θ)
```

However, I ran into a couple of errors with this example. One is that `gradient` is apparently no longer exported, so I had to change the last line to `grads = Flux.Optimise.gradient(() -> loss(x, y), θ)`. When I did that, I got the following error, though:

```julia
julia> grads = Flux.Optimise.gradient(() -> loss(x, y), θ)
ERROR: MethodError: no method matching back!(::Float64)
Closest candidates are:
  back!(::Any, ::Any; once) at /Users/roger/.julia/packages/Tracker/32Vek/src/back.jl:75
  back!(::Tracker.TrackedReal; once) at /Users/roger/.julia/packages/Tracker/32Vek/src/lib/real.jl:14
  back!(::TrackedArray) at /Users/roger/.julia/packages/Tracker/32Vek/src/lib/array.jl:68
Stacktrace:
 [1] gradient_(::var"#15#16", ::Tracker.Params) at /Users/roger/.julia/packages/Tracker/32Vek/src/back.jl:4
 [2] gradient(::Function, ::Tracker.Params; nest::Bool) at /Users/roger/.julia/packages/Tracker/32Vek/src/back.jl:164
 [3] gradient(::Function, ::Tracker.Params) at /Users/roger/.julia/packages/Tracker/32Vek/src/back.jl:164
 [4] top-level scope at REPL[41]:1
```

This is using Flux version 0.11.0.

**Comment by DhairyaLGandhi** [comment]
This seems to be using a very old version of flux, indicated by the error having to do with `back!` and the call to Tracker ine stacktrace. I would double check the environment. Also, you shouldn't need to call into `Flux.Optimise` to get to `gradient`, `Flux.gradient` should be sufficient

**Comment by grero** [comment]
You are absolutely right; I was using an older version. I think something may have failed to update properly. Anyway, sorry for the noise : )
