### ISSUE TITLE
ADAMW Optimise has no field eta

### ISSUE THREAD

**Issue by luboshanus** [FluxML/Flux.jl#1316]
Hi,
when I'm trying to update `eta` parameter in the optimiser it works perfectly with `ADAM`, but not with `ADAMW`. Since, I'm not that strong in struct and its heritage through functions. `ADAMW` has not got its one struct with `eta` parameter as `ADAM` does.

I think that it should have something like:

```julia 
mutable struct ADAMW
  eta::Float64
  beta::Tuple{Float64,Float64}
  decay::Float64       # my guess
  state::IdDict
end
```

It is here: https://github.com/FluxML/Flux.jl/blob/2b1ba184d1a58c37543f4561413cddb2de594289/src/optimise/optimisers.jl#L440-L459

Or I might be mistaken and it would be appreciated if anyone could explain how to update `eta` when using `ADAMW()`.

**Comment by darsnack** [comment]
`ADAMW` is actually a composed optimizer with `ADAM` followed by `WeightDecay`: https://github.com/FluxML/Flux.jl/blob/2b1ba184d1a58c37543f4561413cddb2de594289/src/optimise/optimisers.jl#L461

`Optimiser(opt1, opt2, opt3, ...)` is a sequence of optimizers that can be accessed using index notation. So in your case, you need to access the `ADAM` optimizer in the sequence and update `eta`. This can be done using
```julia
opt = ADAMW()
opt[1].eta = 0.1 # set eta to 0.1
```

**Comment by darsnack** [comment]
@luboshanus If there no more questions, then we can close this issue?
