### ISSUE TITLE
Importing Custom Datasets

### ISSUE THREAD

**Issue by speed-wagon** [FluxML/Flux.jl#1326]
Hello, Im wondering what is the intended method of importing new datasets

I've just finished making a CNN for the MNIST dataset, which was very intuitive as the dataset could be accessed easily via FLux.Data.MNIST.

I want to move onto a dataset of more complicated images. I have downloaded many images of cats and dogs for classification via Kaggle and I want to import those into my Flux project.

The images vary in size, and the image label is in the file name.

I want to be able to do Flux.Data.MyNewDataset.images(:train) 

What is the best way to achieve this? Am I over complicating things? and is it possible for documentation to be expanded to support this?

**Comment by CarloLucibello** [comment]
Currently, you have to load and concatenate  the images as julia arrays, the Images.jl package could be of help. We should make this process easier at some point. 

See also https://github.com/lorenzoh/DataLoaders.jl
