### ISSUE TITLE
Error while pre-compIling Flux in Julia v1.4.2 on windows 10

### ISSUE THREAD

**Issue by yewalenikhil65** [FluxML/Flux.jl#1328]
Hello,
I am facing following error while pre-compiling Flux in Julia v1.4.2 on windows 10.
If anyone could point me how to fix this error ? I do have VS C++ redistributale installed already

julia> using Flux
┌ Error: Could not load CUTENSOR; please file an issue (if on Windows, be sure to install the VS C++ redistributable first)
│   exception =
│    could not load library "C:\Users\Nikhil\.julia\artifacts\804435c7dbe9d002d6caa0a8b3596d11a6faa778\bin\cutensor.dll"
│    The specified module could not be found.
│    Stacktrace:
│     [1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
│     [2] dlopen at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
│     [3] use_artifact_cutensor(::VersionNumber) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:318
│     [4] use_artifact_cuda() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:179
│     [5] __init_dependencies__() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:355
│     [6] __runtime_init__() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:110
│     [7] (::CUDA.var"#609#610"{Bool})() at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:32
│     [8] lock(::CUDA.var"#609#610"{Bool}, ::ReentrantLock) at .\lock.jl:161
│     [9] _functional(::Bool) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:26
│     [10] functional(::Bool) at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:19
│     [11] functional at C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\src\initialization.jl:18 [inlined]
│     [12] __init__() at C:\Users\Nikhil\.julia\packages\Flux\05b38\src\Flux.jl:53
│     [13] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:697
│     [14] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:781
│     [15] _require(::Base.PkgId) at .\loading.jl:1006
│     [16] require(::Base.PkgId) at .\loading.jl:927
│     [17] require(::Module, ::Symbol) at .\loading.jl:922
│     [18] eval(::Module, ::Any) at .\boot.jl:331
│     [19] eval_user_input(::Any, ::REPL.REPLBackend) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:86
│     [20] macro expansion at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:118 [inlined]
│     [21] (::REPL.var"#26#27"{REPL.REPLBackend})() at .\task.jl:358
└ @ CUDA C:\Users\Nikhil\.julia\packages\CUDA\dZvbp\deps\bindeps.jl:320

**Comment by avik-pal** [comment]
This seems to be an issue with https://github.com/JuliaGPU/CUDA.jl/. Could you open an issue there?

**Comment by yewalenikhil65** [comment]
issue re-solved. Thanks for pointing me :)
