### ISSUE TITLE
Flux.destructure doesn't preserve RNN state

### ISSUE THREAD

**Issue by avik-pal** [FluxML/Flux.jl#1329]
As pointed out here https://github.com/SciML/DiffEqFlux.jl/issues/391#issuecomment-680127253, when reconstructing `Recur`, the state values are reverted to the initial state. A simple solution would be to do

```julia
mutable struct MyRecur{T}
  cell::T
  init
  state
end

function (m::MyRecur)(xs...)
  h, y = m.cell(m.state, xs...)
  m.state = h
  return y
end

Flux.@functor MyRecur

Flux.trainable(r::MyRecur) = Flux.trainable(r.cell)
```

EDIT: This doesn't work as expected

**Comment by DhairyaLGandhi** [comment]
Worth a PR, although it needs to be compatible with reset as well, so we don't move things off the GPU accidentally. In which case, are the arguments to functor doing anything?
