### ISSUE TITLE
deprecate treelike 

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1339]
```julia
using Flux
using Flux: @treelike
struct Cat{T}
    layers::T
end
@treelike Cat
```

> LoadError: UndefVarError: functorm not defined
> in expression starting at In[17]:6
> 
> Stacktrace:
>  [1] @treelike(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at /home/cossio/.julia/packages/Flux/05b38/src/functor.jl:58
>  [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
>

**Comment by chengchingwen** [comment]
`@treelike` is deprecated, use `@functor` instead.

https://github.com/FluxML/Flux.jl/blob/master/src/functor.jl#L56

**Comment by cossio** [comment]
Then we should have a deprectaion message_

**Comment by DhairyaLGandhi** [comment]
We can deprecate it, since it already got a soft deprecation. But it might
have been an artifact of the Functors.jl refactor.

**Comment by RajGhugare19** [comment]
Hey! I would like to take up this issue. Can anyone tell me what to do ?

**Comment by CarloLucibello** [comment]
`@treelike` has been removed
