### ISSUE TITLE
Controlling the parameters W ,in Chain(Dense(),Dense()) neural network

### ISSUE THREAD

**Issue by yewalenikhil65** [FluxML/Flux.jl#1342]
Hello, 

I wish to control the behaviour of model while training , based on a constraint on parameters that,

All the parameters (all elements of weight matrix W ) in input layer should stay positive while training the model.

Is this possible currently using Flux ?

**Comment by CarloLucibello** [comment]
This is similar to #942 

I suggest you create a custom dense layer, where you reparametrize the weight  as `W = exp.(A)`, where `A` contains the parameters you actually train

**Comment by yewalenikhil65** [comment]
Hi,
I was referring to more like following
https://machinelearningmastery.com/how-to-reduce-overfitting-in-deep-neural-networks-with-weight-constraints-in-keras/

**Comment by CarloLucibello** [comment]
closing as similar to #1389
