### ISSUE TITLE
conflicts with many packages

### ISSUE THREAD

**Issue by clad26** [FluxML/Flux.jl#1343]
![Screenshot from 2020-10-02 15-50-36](https://user-images.githubusercontent.com/51269425/94914060-f1ffac80-04c7-11eb-96b7-2ecbf30e0e37.png)
![Screenshot from 2020-10-02 15-56-40](https://user-images.githubusercontent.com/51269425/94914063-f4620680-04c7-11eb-8c40-02461734f5b3.png)

Adding Flux downgrades many packages and I can't use CUDA.jl as the 2nd latest version is incompatible with the latest version of CUDA

**Comment by ToucheSir** [comment]
https://discourse.julialang.org/t/cuda-jl-2-0-per-thread-streams-float16-cusparse-clean-up/47630

CUDA.jl 2.0 was just released. As noted in the announcement, it's going to take a bit before dependent packages like Flux are updated to use it. All of the packages downgraded in your second screenshot are dependencies of CUDA.jl, so there don't appear to be any other conflicts.

**Comment by clad26** [comment]
@ToucheSir 
Its just that versions below 2.0 of CUDA.jl don't support CUDA 11.1.... 
So without updating CUDA.jl, I can't use CUDA...
Also, CUDA is big in size, so downgrading my own version of CUDA might not really be a good idea
I'll patiently wait for Flux to be compatible with CUDA.jl

**Comment by ToucheSir** [comment]
CUDA.jl will download its own copy of all the CUDA libraries by default (based on your driver, I believe). In other words, assuming you're not using a brand new Ampere GPU that is _only_ compatible with CUDA 11.1, it should work on your system regardless of what CUDA toolkit version is installed.

**Comment by CarloLucibello** [comment]
this should be solved
