### ISSUE TITLE
Inconsistency of ADAGrad for matrices

### ISSUE THREAD

**Issue by theogf** [FluxML/Flux.jl#1346]
So I am not sure if this is the expected behavior or if it could be an issue:
The `ADAGrad` optimiser is basically given by `eta * (eps + diag(G))^(-1/2) * Δ`, where `G = sum(Δ *Δ')` with some `t` indices missing there and there:)
When `Δ` is a `Vector` the current implementation matches this behaviour: https://github.com/FluxML/Flux.jl/blob/5d9b2caf3291ca415e59c595dd7a4085951a02a2/src/optimise/optimisers.jl#L325-L330

However if `Δ` is a matrix shouldn't the behavior be different? With `(eps + diag(G))^(-1/2)` being applied as a matrix multiplication?

**Comment by CarloLucibello** [comment]
Since only the diagonal part of G is needed, the implementation is fine, see
https://medium.com/konvergen/an-introduction-to-adagrad-f130ae871827
