### ISSUE TITLE
Join ONNX initiative

### ISSUE THREAD

**Issue by juliohm** [FluxML/Flux.jl#135]
Just sharing this initiative as it can be another way to make Flux.jl more visible:

https://github.com/onnx/onnx

The idea is that any model built with other frameworks could be loaded into Flux.jl, and vice-versa.

**Comment by jekbradbury** [comment]
It's a static graph IR, so there would be two primary ways to support it: exporting a trace (e.g. like this https://github.com/chainer/chainer/pull/3572) or importing a graph and interpreting it (nobody else has done this yet, but it would be fairly similar to ONNX imports for static graph frameworks like Caffe2 https://github.com/onnx/onnx-caffe2/blob/master/onnx_caffe2/backend.py).
However, ONNX is most heavily focused on large, static, performance-sensitive computer vision networks (think big ResNets etc.) and this is the area where Flux probably has the least comparative advantage right now.

**Comment by juliohm** [comment]
I will close this issue for now, thank you for the clarification @jekbradbury.

**Comment by MikeInnes** [comment]
We may as well leave this open; it's not a priority but it'd be neat if someone feels like taking a crack.

**Comment by MikeInnes** [comment]
Some progress on this over at [ONNX.jl](https://github.com/FluxML/ONNX.jl/), and I used this for [this model](https://github.com/FluxML/Metalhead.jl/blob/master/src/vgg19.jl). It's not terribly user-friendly right now, but the output isn't bad for 100 lines of compiler code :)

**Comment by juliohm** [comment]
@MikeInnes can we close this one since there is work in progress already?

**Comment by MikeInnes** [comment]
Yeah, we may as well track anything further in that repo.
