### ISSUE TITLE
Array{TrackedArray} to TrackedArray

### ISSUE THREAD

**Issue by baggepinnen** [FluxML/Flux.jl#136]
When doing complicated indexing operations one often ends up with an `Array` of `TrackedArray`. `back!` does not like this array (error below) and while one could call `back!` on each element in turn, it would be nice if one could somehow convert the `Array{TrackedArray}` to a `TrackedArray` with dimension equal to the sum of the dimensions of the Array and initial TrackedArrays
```julia
LoadError: MethodError: no method matching back!(::Array{TrackedArray{…,Array{Float64,0}},1})
Closest candidates are:
  back!(!Matched::Flux.Tracker.TrackedArray{T,0,A} where A where T) at /local/home/fredrikb/.julia/v0.6/Flux/src/tracker/back.jl:47
  back!(!Matched::Flux.Tracker.TrackedArray, !Matched::Any) at /local/home/fredrikb/.julia/v0.6/Flux/src/tracker/back.jl:43
```

**Comment by iblis17** [comment]
`vcat`  your Array of TrackedArray into a single , and `back!` will work as normal. IIRC we support `vcat`
for backword.
```
julia> [W, W′]
2-element Array{TrackedArray{…,Array{Float64,1}},1}:
 param([0.519709, 0.832627, 0.872897, 0.830876, 0.37545, 0.487066, 0.558372, 0.118471, 0.105571, 0.512368])   
 param([0.190725, 0.325138, 0.511466, 0.0843766, 0.246159, 0.478105, 0.881696, 0.361668, 0.0161546, 0.227831])

julia> vcat([W, W′]...);
```

**Comment by baggepinnen** [comment]
That does seem to work, but here's another case that's not
```julia
julia> res
TrackedArray{…,Array{Float64,1}}[2]
Tracked 3-element Array{Float64,1}:
Tracked 3-element Array{Float64,1}:

julia> hcat(res...)
MethodError: Cannot `convert` an object of type TrackedArray{…,Array{Float64,0}} to an object of type Float64
```

**Comment by iblis17** [comment]
yeah, `hcat` and generate `cat` are not implemented yet.
I have this
https://github.com/FluxML/Flux.jl/issues/111#issuecomment-346522574

But we still need to take care the `back!` path

**Comment by MikeInnes** [comment]
Thing is, we shouldn't really have cases where slicing returns an array of tracked scalars, since that's going to be really slow anyway. Ideally we'd overload all indexing to return contiguous tracked arrays.

@baggepinnen can you mention the kind of indexing you're doing to cause this?

**Comment by baggepinnen** [comment]
I was most likely doing some computation element wise in a loop, can't seem to find exactly what I was doing. My use case was deep Q learning, where I created an array of tracked scalar Q-values. In the pseudo code below, I have tried to work around the issue
```julia
Q : R -> R
y = # some target value for Q
Qs = Q(s) # These are now tracked
e = [y[t] - Qs[action2ind(a[t]),t] for t = eachindex(y)] # Generate error, this will be an array of tracked scalars
for e in e
   Flux.back!(e) # I would like to back propagate this error vector, but it's not a traked array, rather an array of tracked scalars
   opt()
end
```

**Comment by MikeInnes** [comment]
Ok, what you could do there is `Flux.back!.(e)` or `Flux.back!.(e, grad)`. You only need to call `opt()` once as the gradients will be accumulated.

It would indeed be nice to just cat them though. Closing this in favour of #142 where we can track that.

**Comment by MikeInnes** [comment]
I think we have ways to deal with this now (e.g. Tracker.collect).
