### ISSUE TITLE
Unnecessary allocations when using LayerNorm

### ISSUE THREAD

**Issue by racinmat** [FluxML/Flux.jl#1361]
LayerNorm is calling `normalise(x, dims=1)`, which is calling `mean`, which  is general for multiple dimensions and uses `unique`, which calls `push!` under the hood.

Having e.g. following implementation instead results in better results:
```julia
using BenchmarkTools
@btime Flux.normalise(r, dims=1) setup=(r=rand(Float32, 1000, 100, 10))
@btime normalise_one_dim(r, dims=1) setup=(r=rand(Float32, 1000, 100, 10))

@btime Flux.normalise(r, dims=1) setup=(r=rand(Float32, 100, 100, 10))
@btime normalise_one_dim(r, dims=1) setup=(r=rand(Float32, 100, 100, 10))

@btime Flux.normalise(r, dims=1) setup=(r=rand(Float32, 100, 10, 10))
@btime normalise_one_dim(r, dims=1) setup=(r=rand(Float32, 100, 10, 10))
```
prints
```
1.483 ms (17 allocations: 3.83 MiB)
1.441 ms (12 allocations: 3.83 MiB)
140.800 μs (17 allocations: 404.08 KiB)
141.900 μs (12 allocations: 407.55 KiB)
14.299 μs (17 allocations: 41.78 KiB)
14.301 μs (12 allocations: 41.67 KiB)
```

should I make PR for this?

Also, we have use-cases where we are doing some tricks aroung garbage collector but in order to make them work we want to avoid `push!` inside the code, this would help for such usecases.

**Comment by mcabbott** [comment]
Those numbers seem suspiciously fast, is `sizes` defined elsewhere?
```


If you're optimising this, and assuming that `norm` doesn't have any special behaviour like avoiding overflow, then this is a bit quicker:
```
julia> function normalise3(x::AbstractArray; dims::Int, ϵ=oftype(first(x), 1e-5))
         μ = sum(x, dims=dims)
         σ = std(x, dims=dims, corrected=false)
         s = 1 ./ ((σ .+ ϵ) .* size(x,dims))
         return (x .- μ) .* s
       end;

julia> @btime normalise4(r, dims=1)  setup=(r=rand(Float32, 100, 1000));
  143.475 μs (11 allocations: 403.48 KiB)

julia> @btime normalise_one_dim(r, dims=1)  setup=(r=rand(Float32, 100, 1000));
  154.510 μs (12 allocations: 407.55 KiB)

julia> @btime normalise3(r, dims=1)  setup=(r=rand(Float32, 100, 1000));
  144.007 μs (12 allocations: 407.55 KiB)
```

**Comment by racinmat** [comment]
Yes, my bad, I made a typo and used different sizes. But I still get higher speed and less allocations.

**Comment by mcabbott** [comment]
But why are you timing arrays of Int64?

**Comment by racinmat** [comment]
Because I drank dumb-fuck juice, updating benchmarks.

**Comment by CarloLucibello** [comment]
the little performance increase doesn't seem to be worth the added complication
