### ISSUE TITLE
Docs Basic typo/code-error after 'Stacking It Up'

### ISSUE THREAD

**Issue by davidljung** [FluxML/Flux.jl#1363]
Following the Basic section of the docs (docs/src/models/basics.md), I get to the first step of the section "Stacking It Up" and it says to enter:
```
layer1 = Dense(10, 5, σ)
# ...
model(x) = layer3(layer2(layer1(x)))
```
But, I get a REPL redefinition error for layer1, then on the next line, layer3 is undefined.
Since I'm just taking the tutorial I can't be sure, but should the assignment be for layer3?  (if so, I'm not sure the dimensions are correct either - should it be 2,2? - or maybe it was intended to redefine layer1, but layer3 was missed..).

Thanks.

**Comment by ToucheSir** [comment]
I believe that code examples is meant to be illustrative and not executed, hence why all the definition of layer2-3 are elided behhind the `# ...` comment. Perhaps that comment should be expanded or both layers could be defined to match the following example (list of layers)?

**Comment by davidljung** [comment]
As the first paragraph says "It's a good idea to try pasting these examples in the Julia terminal.", maybe a comment to make that clearer would be helpful.
