### ISSUE TITLE
Gradient is NaN under certain conditions, when using CUDA.jl

### ISSUE THREAD

**Issue by jonas-eschmann** [FluxML/Flux.jl#1382]
Hi, 
I have spent quite some time tracking down a nasty bug that seems to make gradients NaN occasionally when using CUDA.jl.
It occurs when taking the square during the gradient calculation and casting the `.^2` like `.^Float32(2)`.  To reproduce create following file: 
```
using Flux
using CUDA
using Statistics
CUDA.allowscalar(false)

model = Chain(
    Dense(64, 1)
) |> gpu

x = CUDA.randn(64, 1)
grad = Flux.gradient(Flux.params(model)) do
    mean(model(x) .^ Float32(2))
end
println(grad)

if any([sum(isnan.(grad[p] |> cpu)) > 0 for p in Flux.params(model)])
    throw("NaN found")
end
```

https://gist.github.com/jonas-eschmann/18b3f6e5a6a96b28382f9e4030056d0e#file-test-jl 

Then start a Julia REPL and execute `for _ in 1:100 include("src/Test.jl") end` as this error doesn't always come up. It only comes up when including the file again, looping over the gradient calculation seems to not reliably break it. When you change `mean(model(x) .^ Float32(2))` to `mean(model(x) .^ 2)` it should work reliably.  Another thing I noticed is, that when you put  `mean(model(x) .^ 2.0` the compiler will complain about `scalar getindex is disallowed`. Sure this can be mitigated by setting `CUDA.allowscalar(true)` (which then luckyly leads to an error because pow can not work with Float32 and Float64) but I think it is far from expected behaviour, that a scalar access would be generated in that situation (probably more of an issue with CUDA.jl)

I am running:
```
Julia 1.5.2 (Windows 10)
Flux v0.11.1
CUDA v1.3.3
```

Hopefully, someone with in-depth under the hood knowledge can reproduce this and find the root cause

**Comment by jeremiedb** [comment]
I cannot help with the actual root cause, but I also encountered this issue when trying to debug a rework of RNNs. 
It seems to only happen in situations where negative numbers are squared using Float32(2). So my understanding is that for some reason, the underlying representation of Float32(2) randomly happens to not be exactly 2, resulting in an error from attempting to operate on complex numbers.  Not sure if it's a bug per se, but there at least seems to be different handling of such situation between cpu and CUDA

CPU: 
```julia
julia> (randn(5)) .^ Float32(1.9999)
ERROR: DomainError with -0.02549230310645607:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
 [1] throw_exp_domainerror(::Float64) at .\math.jl:37
 [2] ^ at .\math.jl:888 [inlined]
 [3] ^ at .\promotion.jl:343 [inlined]
 [4] _broadcast_getindex_evalf at .\broadcast.jl:648 [inlined]
 [5] _broadcast_getindex at .\broadcast.jl:621 [inlined]
 [6] getindex at .\broadcast.jl:575 [inlined]
 [7] macro expansion at .\broadcast.jl:932 [inlined]
 [8] macro expansion at .\simdloop.jl:77 [inlined]
 [9] copyto! at .\broadcast.jl:931 [inlined]
 [10] copyto! at .\broadcast.jl:886 [inlined]
 [11] copy at .\broadcast.jl:862 [inlined]
 [12] materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(^),Tuple{Array{Float64,1},Float32}}) at .\broadcast.jl:837
 [13] top-level scope at REPL[16]:1
```

CUDA: 

```julia
cu(randn(5)) .^ Float32(1.9999)
5-element CuArray{Float32,1}:
 NaN
   0.05387642
 NaN
   5.087487
   1.3750497
```

**Comment by jonas-eschmann** [comment]
Thanks for the response! That clarifies the issue. I did not think about numerical issues that lead to taking roots of negative numbers at all in this context but it makes a lot of sense now
