### ISSUE TITLE
LSTM "succeeds" on data with incompatible dimensions

### ISSUE THREAD

**Issue by tbenst** [FluxML/Flux.jl#1396]
I don't see how the following code should possibly be able to return values, given that the LSTM requires 2 input channels and broadcasting should never be able to satisfy this since `seq` has dimensions of prime numbers. Am I missing something fundamental?

```julia
using Flux
seq = rand(5,7,13)
m = LSTM(2,3)
out = m.(seq) # no error?!

##
m = Dense(2,3)
out = m.(seq) # errors as expected
```

**Comment by jeremiedb** [comment]
The above broadcasting is effectively returning a garbage result. 
The underlying reason such call doesn't fail is that there is no restriction for a Vec or Mat as input to the RNN cell, which should perhaps be added as safeguard. 

What's happening by making the `m.(seq)` broadcasting call is that 455 scalars  (5*7*13) are individually passed to the RNN cell. 
And it happens that the operations performed by the RNN/LSTM cell can in effect handle the calculation over a scalar input, although it's clearly not a proper usage of the cell: 
```
m = RNN(2,3)
julia> m(1.1)
3×2 Array{Float64,2}:
 -0.715264  -0.78425
  0.714594   0.821187
  0.650443   0.574614
```

What you actually want to do when using the broadcast over a RNN cell, is to pass a `Vector` containing the 2D matrix representing each timestep, not a 3D Array. For further explanations about the underlying design, you can refer to the end of this issue: https://github.com/FluxML/Flux.jl/issues/1360.

**Comment by ToucheSir** [comment]
This now errors as expected, though the stacktrace is noiser than it could be because of all the type params involved.
