### ISSUE TITLE
deeplearn.js

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#140]
Would be very cool to export Flux models to the browser easily; and the best option to do so is probably https://deeplearnjs.org/.

Not sure how best to do this as yet. Code-tracing approaches (i.e. grab the graph generated by the AD) would be easy to implement, but sacrifice some high-level information like recurrence (which I believe deeplearn.js can express).

**Comment by amellnik** [comment]
For anyone else who's watching this --Mike has a WIP here: https://github.com/FluxML/FluxJS.jl

**Comment by MikeInnes** [comment]
Since that project is working well now I think we can close this.
