### ISSUE TITLE
Non-reproducible example in documentation

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [FluxML/Flux.jl#1403]
In the documentation [here](https://github.com/FluxML/Flux.jl/blob/8fb94be4a682fe6879368d55c26e50359c049703/src/layers/basic.jl#L147), it appears that the dimensions don't match.

```
julia> import Flux

julia> m = Flux.Dense(10, 5)
Dense(10, 5)

julia> Flux.outdims(m, (5, 2)) == (5,)
ERROR: DimensionMismatch("input size should equal to (10,), got (5, 2)")
Stacktrace:
 [1] outdims(::Flux.Dense{typeof(identity),Array{Float32,2},Array{Float32,1}}, ::Tuple{Int64,Int64}) at /home/sid/.julia/packages/Flux/05b38/src/layers/basic.jl:152
 [2] top-level scope at REPL[10]:1

julia> 
```

**Comment by gxyd** [comment]
I think I agree with you, do you think a good solution would be to change that line to something like:
```jl
outdims(m, (10, 100)) == (5,)
```
WDYT?

**Comment by gxyd** [comment]
Would we want to take https://github.com/FluxML/Flux.jl/issues/1403 into account while fixing this issue?

**Comment by DhairyaLGandhi** [comment]
Yes that would be fine

**Comment by Sid-Bhatia-0** [comment]
`outdims(m, (10, 100)) == (5,)`

Sounds good to me.
