### ISSUE TITLE
Flux.LSTM() returns a sequence of states

### ISSUE THREAD

**Issue by deveshjawla** [FluxML/Flux.jl#1406]
Hi guys,
I noticed that by default the LSTM layer returns a sequence of states instead of just the last value. Like in Keras one could set return_sequcnes=False to get only the last output, does flux also offer that?
![Screenshot from 2020-11-25 23-55-37](https://user-images.githubusercontent.com/42186026/100389511-d9c28e80-302d-11eb-80ee-173f06419f44.png)

**Comment by bhvieira** [comment]
You can simply take the last value with array indexing. In your example: `l(a)[end]`

**Comment by deveshjawla** [comment]
yes, I figured. But would be nice to have functionality built-in. I was looking into the source code, it doesn't seem to provide any kwargs such that one could set return_sequences=false. Unless I am obviously missing something there, I would probably implement this functionality myself.

**Comment by bhvieira** [comment]
I didn't catch it at first, but in your example, what you actually have is a Batch. The return value is equal to a single timestep of a LSTM

**Comment by deveshjawla** [comment]
If in that case, if we reshape to (features,timesteps,batches) and we feed it as one batch, it gives nonsensical results, as can be seen here:
![Screenshot from 2020-11-27 09-02-13](https://user-images.githubusercontent.com/42186026/100425355-56398980-308f-11eb-96bf-5636f08f918e.png)

**Comment by deveshjawla** [comment]
Another minimal example shows that if we feed a batch of 1 sample, it still returns a sequence equal to the length of timesteps.
![Screenshot from 2020-11-27 08-58-13](https://user-images.githubusercontent.com/42186026/100425601-d5c75880-308f-11eb-9ca6-0e0c7fd0095a.png)

**Comment by deveshjawla** [comment]
I believe, as an easy fix, one could also plug (x->x[:,end]) in the Chain so that the succeeding layers are fed only the last state.
```Chain(LSTM(n,m), x -> x[:,end], Dense(m,p))```

**Comment by bhvieira** [comment]
Each time you call the LSTM is a timestep. You can use broadcasting, but not in the way you used.
You'd need to broadcast the LSTM forward pass over an array distributed in time, i.e. each array is a timestep.
So `a = [randn(2,10) for _ in 1:20]` would be an input, with batchsize 10 and 20 timesteps.
Then you'd call `l.(a)`, broadcasting the LSTM forward pass over the array in time.
To keep the last element and apply a Dense layer to it, it would be simply `d(l.(a)[end])`

Another, very Julian, possibility would be mapslice, with time as the last dimension (good for memory management, IIRC), but I'm not sure how well is mapslice works with Zygore right now. @DhairyaLGandhi and @CarloLucibello could comment on that I think.

**Comment by deveshjawla** [comment]
Seems quite confusing and unconventional. If I have 1 timeseries of 2 categorical values like `rand([1,-1],100)` and I make it onehot and reshape it to (2,1,100) then what will the input dimensions of an LSTM layer? If I use LSTM(2,1) then it gives nonsensical output like here:
![Screenshot from 2020-11-28 16-09-36](https://user-images.githubusercontent.com/42186026/100518859-a2222680-3194-11eb-87ea-c87ddfb3c507.png)

**Comment by bhvieira** [comment]
You shouldn't reshape it if you want to broadcast. You should keep each timestep as an array (Input size X Batch size), and then broadcast over that.

**Comment by deveshjawla** [comment]
Ok thanks. It gives good output now. So just to get this straight, 1 timeseries of 2 categorical values becomes a time-series of 2 features when we make it onehot? And therefore the LSTM layer should have indim=2(features)?
