### ISSUE TITLE
delete!() function doesn't freeze the paramters in weight matrix

### ISSUE THREAD

**Issue by yewalenikhil65** [FluxML/Flux.jl#1416]
Training following NN , and using delete! function as shown below doesn't help in freezing the parameters. 
Does it only work on all elements of weight matrices and biases as whole ? Any idea of how to freeze the elements of weights/biases while training ?
```julia
m = Chain( Dense(4,5,softmax) , Dense(5,4) )
ps = Flux.params(m)  # params
ps[1][3,3] = 1.0;
ps[3][3,3] = -1.0;
ps[1][end,end] = 1.0;
ps[3][end,end] = -1.0;

delete!(ps, m[1].W[3,3])             # freezing these elements to 1.0 and -1.0
delete!(ps, m[1].W[end,end])
delete!(ps, m[2].W[3,3])
delete!(ps, m[2].W[end,end])

delete!(ps, m[2].b) #
```

**Comment by CarloLucibello** [comment]
you can only freeze a whole array, not single elements. If you want to freeze a subset of the elements, one possibility is to define your custom Dense layer where you apply a mask in the forward pass. Another possibility is to revert the elements to the previous state after the update

**Comment by CarloLucibello** [comment]
I'm closing this since it is not something we will likely support in the flux's interface
