### ISSUE TITLE
Conv with non homogenous array eltypes gives confusing error message

### ISSUE THREAD

**Issue by femtomc** [FluxML/Flux.jl#1421]
```julia
ERROR: LoadError: MethodError: no method matching Flux.Conv(::Array{Float64, 4}, ::Vector{Float32}, ::typeof(identity); stride=1, pad=0, dilation=1)
Closest candidates are:
  Flux.Conv(::F, ::A, ::V, ::Tuple{Vararg{Int64, N}}, ::Tuple{Vararg{Int64, M}}, ::Tuple{Vararg{Int64, N}}) where {N, M, F, A, V} at /home/mccoy/.julia/packages/Flux/q3zeA/src/layers/conv.jl:71 got unsupported keyword arguments "stride", "pad", "dilation"
  Flux.Conv(::AbstractArray{T, N}, ::Union{AbstractVector{T}, Flux.Zeros}, ::Any; stride, pad, dilation) where {T, N} at /home/mccoy/.julia/packages/Flux/q3zeA/src/layers/conv.jl:105
  Flux.Conv(::Tuple{Vararg{Integer, N}}, ::Pair{var"#s150", var"#s149"} where var"#s149"<:Integer where var"#s150"<:Integer, ::Any; init, stride, pad, dilation, weight, bias) where N at /home/mccoy/.julia/packages/Flux/q3zeA/src/layers/conv.jl:132
```
when using

```julia
Conv((5, 5), 10 => 20, identity; init = glorot_uniform64),
```

**Comment by CarloLucibello** [comment]
Conv was expecting homogeneous weights and bias (e.g. Float32). We should relax this or give some informative error

**Comment by gxyd** [comment]
(Correct me if I'm wrong) I was thinking about the two, and from https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Conversion-vs.-Construction . If we do relax this, that would mean a conversion from `Float32` to `Float64` of a (possibly) large array to take place, which might encourage its use that way.

Better go with simply throwing an informative error?

**Comment by DhairyaLGandhi** [comment]
I feel like the error message can be improved to not be a footgun, but other than that erring on the side of caution is good. Of course none of the machinery expects the same eltypes.

The second method in the stack trace also points at the missing eltypes
