### ISSUE TITLE
Iris Dataset is out of date

### ISSUE THREAD

**Issue by yenson-lau** [FluxML/Flux.jl#1433]
```
julia> size(Iris.labels())
[ Info: Downloading iris dataset.
┌ Error: Download failed: curl: (22) The requested URL returned error: 404 Not Found
└ @ Base download.jl:43
ERROR: failed process: Process(`curl -s -S -g -L -f -o /tmp/jl_QQSLzI https://cache.julialang.org/https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data`, ProcessExited(22)) [22]
```

Clicking on the link shows
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>84eddb2d9ba65f2651e4fe16b56eb2dc5d316ac081cd5a94b528d437a640e387/iris.data</Key>
<RequestId>2B65439A61A08FA3</RequestId>
<HostId>Oys8EBiliIochT8P9Dh2laZtVnIkjGbLRNuODRv7j5P0aFDHefSaP8bGdqo06494cyNJhDFgEos=</HostId>
</Error>
```

**Comment by AsafManela** [comment]
I think this is a more general problem with the caching mechanism. It also happens with MNIST.

**Comment by ToucheSir** [comment]
All of the `Flux.Data` datasets are now deprecated. Use https://github.com/JuliaML/MLDatasets.jl instead, IIRC it doesn't go through the (often problematic) cache.

**Comment by staticfloat** [comment]
The cache was indeed confused and I've kicked it over, but I agree, it's best not to use that server.  That server is going to go down eventually, it's much better to use MLDatasets.jl or to build artifacts for small things like MNIST or Iris.

**Comment by DhairyaLGandhi** [comment]
Master punts users to those routes, but we need a deprecation path for them

**Comment by DhairyaLGandhi** [comment]
Closing this for now.
