### ISSUE TITLE
Implement sparse initialization

### ISSUE THREAD

**Issue by atiyo** [FluxML/Flux.jl#1450]
In the PyTorch parity issue (https://github.com/FluxML/Flux.jl/issues/1431#issue-771272811) it's pointed out that PyTorch supports sparse initialization where Flux doesn't. Raising this issue to avoid taking that thread too far off-topic.

I'm happy to implement sparse initialization if it would be helpful.

The PyTorch implementation currently works only for 2d tensors (https://pytorch.org/docs/stable/_modules/torch/nn/init.html#sparse_). Mimicking this implementation seems straightforward.

Would Flux want to generalise beyond 2d? If so, what is the correct way to do so?

The PyTorch implementation sets a fixed proportion of each column to zero. On multi-dimensional generalisation possibility: setting a fixed proportion of the the last dimension of an `AbstractArray` to zero. But whether this is a meaningful thing to do might depend on the context?

**Comment by DhairyaLGandhi** [comment]
Would appreciate a pr!

The most straightforward thing to do would be to start with a simple implemention that mimics pytorch behavior and subsequently generalise it

**Comment by atiyo** [comment]
Addressed by PR above.
