### ISSUE TITLE
CMUDict vs cmudict in path

### ISSUE THREAD

**Issue by davidavdav** [FluxML/Flux.jl#146]
Hello,  

I am getting this error running the model zoo example phonemes:
```
julia> include("0-data.jl")
ERROR: LoadError: SystemError: opening file /Users/david/.julia/v0.6/Flux/src/data/../../deps/CMUDict/cmudict: No such file or directory
```
I suppose you tested this on a [case-insensitive filesystem](https://www.cio.com/article/2868393/linus-torvalds-apples-hfs-is-probably-the-worst-file-system-ever.html)? 

I can resolve the problem by adding a soft link in the deps directory.

**Comment by MikeInnes** [comment]
Good catch, thanks. This should have been caught by CI earlier but I messed up the test :)
