### ISSUE TITLE
Document conv data handling, especially for 1d 

### ISSUE THREAD

**Issue by AriMKatz** [FluxML/Flux.jl#1465]
From slack:

> So I the Flux docs are not great for non-image data w.r.t. Conv. If you want to do a 1D convolution, Conv expects a 3D input. This is more explicit in the NNlib docstring and the Flux one (https://fluxml.ai/Flux.jl/stable/models/nnlib/#Convolution-1).
> :point_up:
> 1
> 
> 
> Kyle Daruwalla  3 days ago
> As for the ordering of that 3D input…I’m not sure. I would expect it to be NCovariates x Ntime x NBatch, but the docs nor the source code does a great job of explaining that. Maybe @Brian Chen or @Andrew Dinhobl who have worked with time series data can chime in.
> :+1:
> 1
> 
> 
> Kyle Daruwalla  3 days ago
> Definitely, you shouldn’t have to conform your time series data to match WHCN format. There is some other format…I just don’t know what it is.
> 
> Brian Chen  3 days ago
> Yup, that's the way to go. I like to think of it as lopping the first dimension off WHCN, so channels and batch are still 2nd last and last respectively
> 
> Brian Chen  3 days ago
> So in this case it would be NTime x NCovariates X NBatch (which incidentally is the exact opposite of PyTorch because of batch first vs batch last)
> 
> Brian Chen  3 days ago
> I'm not sure if a spectrogram makes sense for your data, but if it can be represented that way you could make use of 2d convs
> 
> Jon Alm Eriksen  3 days ago
> @Brian Chen,  am I understanding you correctly in that if I provide a 3D tensor to Chain, with a filter tuple of one element, then it convolves along the first dimension only?
> :heavy_check_mark:
> 1
> 
> 
> Jon Alm Eriksen  3 days ago
> @Brian Chen Many thanks!
> 
> Jon Alm Eriksen  3 days ago
> You can think of my data as a specrogram-ish with complex data values, but I think that the 1D convolution is the only thing that makes sense
> 
> Jon Alm Eriksen  3 days ago
> the data is not translational invariant in the “frequency” direction
> 
> Jon Alm Eriksen  3 days ago
> Thanks all for helping me out!
> 
> Andrew Dinhobl  3 days ago
> I've been struggling with this as well recently. I'm also currently working on a 1-D convolution with (#vars x #timesteps x batchsize) and I used the unsqueeze thing to add an additional dimension for "channels" but still running into some issues.
> 
> Brian Chen  3 days ago
> Generally it's easiest to represent each var as a channel, so time x vars x batch.
> 
> 
> 
> 
> Brian Chen  3 days ago
> So no need to do any unsqueezing
> 
> Andrew Dinhobl  3 days ago
> What do you mean by "each var as a channel"?
> 
> Brian Chen  3 days ago
> If you have a multivariate time series, the easiest way to run a 1d conv over it is to treat each variable as a channel
> 
> Brian Chen  3 days ago
> I believe that handles interactions between variables as well because of channel mixing

**Comment by ToucheSir** [comment]
We could tweak https://fluxml.ai/Flux.jl/stable/models/layers/#Convolution-and-Pooling-Layers a bit to note that the spatial/temporal dimensions always come first (i.e. format is `S_1 x S_2 x ... x S_n x C x N`), but otherwise there shouldn't be much to do. PRs welcome :)

**Comment by aditkumar72** [comment]
Can you please give some more details?

**Comment by vivekkumar7089** [comment]
@ToucheSir I would like to work on this and will raise the PR soon.

**Comment by ToucheSir** [comment]
Not sure why I didn't close this at the time, but thanks again to @vivekkumar7089 for the docs PR!
