### ISSUE TITLE
Better handling for layers with multiple inputs w/ outputsize

### ISSUE THREAD

**Issue by darsnack** [FluxML/Flux.jl#1466]
Given the variable argument version of `Parallel` (#1462) and #1009, it seems like we need better support for multiple arguments as layer inputs. Currently, `outputsize` only understands a single `Tuple` for `inputsize`.

**Comment by mcabbott** [comment]
Should be easy to do, something like `outputsize(m, (10,32), (20, 32))`. With `padbatch=true` applied to all the inputs?

Maybe another feature to consider is making `outputsize` give more informative errors. A simple step would be that, given a `Chain`, it uses `try/catch` to step along, and tells you which layer rejected what size input. This would slow it down of course, but only some ns/layer, am I correct in thinking this would not be a concern?

**Comment by DhairyaLGandhi** [comment]
Try catch would be bad for AD, so I'd punt on it for the time being.

**Comment by mcabbott** [comment]
How would AD be involved?

**Comment by DhairyaLGandhi** [comment]
The codegen for the forward pass would have to look at the try-catch, which would slow down AD.

**Comment by mcabbott** [comment]
But `outputsize` takes and returns a tuple of integers, it doesn't call AD at all. 

https://github.com/FluxML/Flux.jl/blob/8dfe4fa73671128e6a7b18835ec10eba9d04e92d/src/outputsize.jl#L98-L102

Are you suggesting that there's a use case in which people call AD on that, somehow?

**Comment by DhairyaLGandhi** [comment]
I was thinking of that as a general construct where this is embedded into a version of `Parallel` that can generate the output size on the fly to be used for downstream model flow.

Sort of like AutoML, but not quite the same thing

**Comment by DhairyaLGandhi** [comment]
I'm imagining it as a utility for automated model building and optimisation of the hyper param selection.

**Comment by mcabbott** [comment]
Well, OK, that sounds like a much more ambitious piece of machinery, maybe open an issue? I guess I'm already bending this issue away from its original intent, but 

> making outputsize give more informative errors

is still about the same function. In which there is no AD.

**Comment by darsnack** [comment]
Yeah better to leave￼ AD in outputsize for another issue. I was thinking for this issue,￼ it should treat `(x, y), (a, b)` the same as `((x, y), (a, b))`. That's how the layers work, and AFAIK that's required for compatibility with `Chain`.
