### ISSUE TITLE
Kronecker Product on Tracked Arrays No Method Matching *

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#149]
Trying to do a Kronecker Product of two tracked arrays and have a no method matching for `*`:
```
kron(param(eye(2)),param(eye(2)))
#=> MethodError: no method matching *(::TrackedArray{…,Array{Float64,0}}, ::TrackedArray{…,Array{Float64,0}})
```

**Comment by jessebett** [comment]
Actually, I'm probably missing something pretty fundamental.

Why doesn't this work?
```
param(1.)*param(2.) #=> MethodError: no method matching *(::TrackedArray{…,Array{Float64,0}}, ::TrackedArray{…,Array{Float64,0}})
```

**Comment by MikeInnes** [comment]
The basic problem here we don't have `kron` isn't implemented, so it's falling back to scalar indexing (which could work in theory but would be very slow). If you want to write down the gradient of `kron` it'd be a very welcome addition.

Likewise for scalar multiplication (your second comment); it would be fine to add it, although it's unlikely that there's many real use cases for it.

**Comment by jessebett** [comment]
I brought up the scalar multiplication because I think that's what is throwing the error when calling `kron` on a TrackedArray.

So wouldn't implementing scalar multiplication give us gradients through Base.kron for free?

Or are you saying that it's Base.kron which uses scalar indexing and that would be very slow?

**Comment by jessebett** [comment]
Could we perhaps follow Tensorflow's implementation and get the Kronecker product through clever reshaping?

```
def kronecker_product(mat1, mat2):
  """Computes the Kronecker product two matrices."""
  m1, n1 = mat1.get_shape().as_list()
  mat1_rsh = array_ops.reshape(mat1, [m1, 1, n1, 1])
  m2, n2 = mat2.get_shape().as_list()
  mat2_rsh = array_ops.reshape(mat2, [1, m2, 1, n2])
return array_ops.reshape(mat1_rsh * mat2_rsh, [m1 * m2, n1 * n2])
```

Do you have intuition on the performance of an approach like this in Flux?

I don't really know what's going on with reshape on Flux params:

```
using Flux
m = param(eye(2))

m_rsh = reshape(m,(1,4))
#=>
1×4 Base.ReshapedArray{Float64,2,TrackedArray{…,Array{Float64,2}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}:
 param(1.0)  param(0.0)  param(0.0)  param(1.0)

2*m_rsh 
#=>
MethodError: Cannot `convert` an object of type TrackedArray{…,Array{Float64,0}} to an object of type Float64
```

**Comment by MikeInnes** [comment]
Sure, that should work. If you can get that working with normal arrays I can make sure the `reshape` works properly; we'll have to hook in to avoid creating a `ReshapedArray` in that case, I think.

**Comment by jessebett** [comment]
Here it is working with normal arrays:

```
function kronecker_product(mat1,mat2)
    m1, n1 = size(mat1)
    mat1_rsh = reshape(mat1,(1,m1,1,n1))

    m2, n2 = size(mat2)
    mat2_rsh = reshape(mat2,(m2,1,n2,1))

    return reshape(mat1_rsh.*mat2_rsh, (m1*m2,n1*n2))
end
```

**Comment by jessebett** [comment]
@MikeInnes is there a resource explaining or example showing how I could 'hook to avoid creating a `ReshapedArray`'? I could give it a try if you think it's relatively accessible?

**Comment by MikeInnes** [comment]
Reshape is easy. We already catch `Base.reshape(xs::TrackedArray, dims::Union{Colon,Int64}...) = ...` so we just need to catch the case where `dims` is a tuple, like you used above, and forward it.

But using the derivative would definitely be better, as it'd work for multi-dimensional kronecker products as well. You just need to define a method like `back(::typeof(kron), grad, a, b)`, following the others in [lib.jl](https://github.com/FluxML/Flux.jl/blob/69db0970fdf50cc54f3874a711a7a2ce58a83233/src/tracker/lib.jl#L110).
