### ISSUE TITLE
Zeros has old behaviour on releases up to 0.11.6

### ISSUE THREAD

**Issue by DrChainsaw** [FluxML/Flux.jl#1507]
Not sure if this is intentional due to some breakage I have forgotten about.

On Flux 0.11.6 zeros.jl seem to have the old contents before #1379 meaning that issues #1332, and #1277 are still present.

Master: https://github.com/FluxML/Flux.jl/blob/master/src/zeros.jl
0.11.6: https://github.com/FluxML/Flux.jl/blob/v0.11.6/src/zeros.jl

**Comment by DhairyaLGandhi** [comment]
Yes we haven't released it yet. That's a technically breaking change too. We would also consider #1402 for various reasons including #1302 and #1481 

GitHub releases has been a bit dirty
