### ISSUE TITLE
Moving multihead attention from transformers.jl into Flux.jl

### ISSUE THREAD

**Issue by rakesh4real** [FluxML/Flux.jl#1514]
In reference to https://github.com/FluxML/Flux.jl/issues/1431,

> Attention Layers
>
> - [x] Transformer. Well maintained implementations in Tansformers.jl.
> - [ ] MultiHeadAttention Should be moved from Transformers.jl to Flux.jl

I am planning to move [mh_atten.jl](https://github.com/chengchingwen/Transformers.jl/blob/51f1cf613199a0e4c9742a6cd01a62b799b81d8f/src/basic/mh_atten.jl) into [layers](https://github.com/FluxML/Flux.jl/tree/master/src/layers).

Is it the correct location to directory to move to?

**Comment by CarloLucibello** [comment]
I'm in favor of this, although it is probably better done by the package author @chengchingwen, at least to preserve authorship

**Comment by rakesh4real** [comment]
closing with reference to https://github.com/FluxML/Flux.jl/issues/1431#issuecomment-783141863

**Comment by DhairyaLGandhi** [comment]
I would consider a pr to Transformers with the cudnn dispatch as a contribution to our ecosystem as well @rakesh4real 😉
