### ISSUE TITLE
`gpu` behaves differently from `cu` on a Char array

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#1517]
```julia
julia> using Flux, CUDA

julia> ['a', 'b', 'c'] |> cu    # can move to gpu, Char isbittype
3-element CuArray{Char,1}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

julia> ['a', 'b', 'c'] |> gpu  # WRONG, doesn't move to device
3-element Array{Char,1}:
 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
 'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)
```

**Comment by darsnack** [comment]
Seems like a Functors.jl issue: https://github.com/FluxML/Functors.jl/blob/61822d9b662aea7efbccef7d4513550187227d50/src/functor.jl#L8

I think what ends up happening is that since `Char` isn't a `Number`, the array is not treated as a leaf. So instead, we call `cu` on each character (which has no effect), then reconstruct an `Array`.

**Comment by ToucheSir** [comment]
Is there a way to dispatch on these primitive isbits types? Or is `Char` the only one we have to worry about aside from the `Number` type hierarchy?

**Comment by darsnack** [comment]
> Is there a way to dispatch on these primitive isbits types?

Not purely from the type (I don't think). Was poking around CUDA.jl to see if there was a set of types for which we could define this. Seems like it could special case Functors.jl too much though.

I think the best way is to allow a predicate in `fmap` (writing a PR right now). This particular issue might be one that we want to handle in a standard way, but a controllable descent seems like a nice way to address these in specific use cases of Functors.jl. I could a future where we don't want something to be a leaf, but we also don't want to descend in the specific `fmap` call.

**Comment by darsnack** [comment]
With https://github.com/FluxML/Functors.jl/pull/10 we'd just do:
```julia
gpu(x) = use_cuda[] ? fmap(CUDA.cu, x; predicate = CUDA.isbits) : x
```

**Comment by ToucheSir** [comment]
@darsnack do you have bandwidth to PR this? Just needs tests and it's good to go, right?

**Comment by darsnack** [comment]
Yes, I think it just needs a test (could just use the OP), but it would be appreciated if you could submit the PR (I am trying to close out my other Flux PRs right now).
