### ISSUE TITLE
OneHotArrays.jl?

### ISSUE THREAD

**Issue by mschauer** [FluxML/Flux.jl#1544]
Would it make sense for one-hot-arrays to live outside Flux?

**Comment by DhairyaLGandhi** [comment]
I think that would be the case if we could make it more generic and better tested. I'm assuming the use cases for such a package are generally narrow though.

**Comment by mschauer** [comment]
I don't think it's too narrow, just skimming https://juliahub.com/ui/CodeSearch?q=onehot&u=all&t=all

**Comment by darsnack** [comment]
Yeah, I was thinking the same thing working on a personal project where I wanted one-hot arrays but not the rest of Flux. I agree with @DhairyaLGandhi that we would want some more comprehensive coverage and testing. I think the underlying array implementation is generic enough, but I'm talking about defining functions like `argmax`, etc. We may not have all the possible functions defined sensibly right now.

**Comment by mcognetta** [comment]
I, too wish it lived outside flux. If I put together a roadmap for migrating it could there be a review process for it?

**Comment by darsnack** [comment]
Absolutely, I will review any PRs that migrate the code. The destination repo will still need to be owned by Flux since it is integral to our codebase. I mostly haven't worked on this because of a lack of time, not a lack of interest.

**Comment by ParadaCarleton** [comment]
> I think that would be the case if we could make it more generic and better tested. I'm assuming the use cases for such a package are generally narrow though.

Judging by [this](https://discourse.julialang.org/t/all-the-ways-to-do-one-hot-encoding/64807) thread there'd be a lot of interest in it outside of MLJ.

**Comment by mcognetta** [comment]
Thanks for pinging this. Actually I have a PR nearly ready. It needs to be done in two stages though, and I'd need a core maintainer to help. 

How should we move forward?

PS sorry for the delay, it has been a hectic few months.

**Comment by ToucheSir** [comment]
Feel free to link the repo you've been working on once you feel it's in a state to review. Once that's registered as a package, we can be far more leisurely about deciding how to integrate it into Flux.

**Comment by darsnack** [comment]
Yeah happy to provide core maintainer help. Just ping me where needed.

**Comment by TLipede** [comment]
I wouldn't want to step on any toes, but I'm happy to contribute to moving this to its own package if that would be helpful. I can appreciate that time can get away, and I luckily have a little bandwidth to work on this at the moment.

**Comment by darsnack** [comment]
That would be great! I just created https://github.com/FluxML/OneHotArrays.jl. You can just PR that repo to port the existing code from Flux, then make additions to the codebase as well. We can help by reviewing the PRs.

I'll add some CI, etc. later today.

**Comment by TLipede** [comment]
Great stuff thanks! 👍🏿

**Comment by TLipede** [comment]
Quick question; should there also be a small OneHotArraysCUDA.jl package?

**Comment by darsnack** [comment]
I would say no for now while we get the repo set up. We can always move it out at a later point.
