### ISSUE TITLE
LSTM failed to return gradient

### ISSUE THREAD

**Issue by zqni** [FluxML/Flux.jl#1551]
When training an LSTM model, I found the returning gradient is in the wrong form which failed the training. Here's a toy example. 

```
Using Flux
trainX = [rand(5,5)[i,:] for i=1:5]|>gpu
trainY = [rand(5,2)[i,:] for i=1:5]|>gpu
myModel  = Flux.LSTM(5,2) |>gpu
params = Flux.params(myModel)    
opt =  ADAM()
loss(x,y) =sum(mse.(trainY[y],myModel.(trainX[x])))
x1 = y1 = [i for i=1:5]
trainData = Flux.Data.DataLoader(x1,y1,shuffle=true,batchsize=5)  
Flux.train!(loss,params,trainData,ADAM())
```

The error is

`ArgumentError: NamedTuple{(:σ, :Wi, :Wh, :b, :h, :c),Tuple{Nothing,LinearAlgebra.Transpose{Float32,CuArray{Float32,2}},LinearAlgebra.Transpose{Float32,CuArray{Float32,2}},CuArray{Float32,1},Nothing,Nothing}} keys must be a subset of NamedTuple{(:Wi, :Wh, :b, :h, :c),NTuple{5,Nothing}} keys`

If I change the LSTMcell to a normal RNNcell, the model works. 
My Flux edition is 0.12 and the Zygote is 0.6.7, my Julia is 1.5.3.

Am I missing anything here?

**Comment by DhairyaLGandhi** [comment]
I think the arguments to mse are usually the reverse.

**Comment by DhairyaLGandhi** [comment]
This is happening in the accum step. cc @jeremiedb

**Comment by zqni** [comment]
Hi Dhairya, thanks for your reminder. Indeed, even I changed the order of the inputs to mse, the error still remains.

**Comment by jeremiedb** [comment]
@zqni Could you provide a reproducible example. The provided code shows some issues. 

```julia
trainX = [rand(5,5)[i,:] for i=1:5]|>gpu
trainY = [rand(5,2)[i,:] for i=1:5]|>gpu
myModel  = Flux.LSTM(5,2) |>gpu
params = Flux.params(myModel)
opt =  ADAM()
loss(x,y) =sum(mse.(trainY[y],myModel.(trainX[x])))
x1 = y1 = [i for i=1:5]

julia> x1
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> y1
5-element Vector{Int64}:
 1
 2
 3
 4
 5
```

Also, is the  [i,:]`  in `trainX = [rand(5,5)[i,:] for i=1:5]|>gpu` really what needed? The trainY dimension doesn't seems right. 
Is the output of size 2 really what you want? Typically, you'd want to to have a single output for each observation of the batch and each element of the sequence. For exmaple: 
```
rnn = Chain(LSTM(feat, h_size),
    Dense(h_size, 1, σ),
    x -> reshape(x, :))
```

I can confirm LSTM does work on the latest 0.12 release.

**Comment by zqni** [comment]
@jeremiedb Thanks a lot for your reply. Here  x1,y1 are just the index to select which inputs to be trained and they're not data. If I removed them and input data directly, I still met the error.

```
trainX =[ rand(5,5)[i,:] for i=1:5]|>gpu
trainY = [rand(5,2)[i,:] for i=1:5]|>gpu
myModel  = Chain(Flux.LSTM(5,2)) |>gpu
params = Flux.params(myModel)    
opt =  ADAM()
loss(x,y) =sum(mse.(myModel.(x),y))
trainData = Flux.Data.DataLoader(trainX,trainY,shuffle=true,batchsize=5)  
Flux.train!(loss,params,trainData,ADAM())
```
Here I want to try a many-to-many LSTM model and I think it's very common e.g. if you want to predict some responses in the next two days with the last 5 days' record. That's why my output size is not 1 here.

**Comment by jeremiedb** [comment]
The code you provided errored right at the data loader part, which is why it is a good practice to provide the actual reproducible example along the returned error message when opening an issue: 

```julia
julia> trainData = Flux.Data.DataLoader(trainX,trainY,shuffle=true,batchsize=5)
ERROR: MethodError: no method matching Flux.Data.DataLoader(::Vector{CUDA.CuArray{Float32, 1}}, ::Vector{CUDA.CuArray{Float32, 1}}; shuffle=true, batchsize=5)
Closest candidates are:
  Flux.Data.DataLoader(::Any; batchsize, shuffle, partial, rng) at C:\Users\jerem\.julia\packages\Flux\lwA90\src\data\dataloader.jl:70
  Flux.Data.DataLoader(::D, ::Int64, ::Int64, ::Bool, ::Int64, ::Vector{Int64}, ::Bool, ::R) where {D, R<:Random.AbstractRNG} at C:\Users\jerem\.julia\packages\Flux\lwA90\src\data\dataloader.jl:5 got unsupported keyword arguments "shuffle", "batchsize"
Stacktrace:
 [1] top-level scope
   @ REPL[80]:1
```

Please take a look at the docs about the expected formatting: https://fluxml.ai/Flux.jl/dev/models/recurrence/
It may hopefully resolve some confusion about the shape. 

The following might be closer to what you want: 
```julia
trainX = [rand(5, 5) for i = 1:5] |> gpu
trainY = [rand(2, 5) for i = 1:5] |> gpu
myModel  = Chain(Flux.LSTM(5, 2)) |> gpu
params = Flux.params(myModel)
opt =  ADAM()
loss(x,y) = sum(Flux.Losses.mse.(myModel.(x), y))
Flux.train!(loss,params, [(trainX, trainY)], opt)
```

**Comment by zqni** [comment]
@jeremiedb I appreciate it a lot and your suggestion about the input shape is reasonable. The issue is that I still run across the same error even when I use your code above. I was wondering whether it's the problem of the specific edition of Zygote.

`ArgumentError: NamedTuple{(:σ, :Wi, :Wh, :b, :h, :c),Tuple{Nothing,LinearAlgebra.Transpose{Float32,CuArray{Float32,2}},LinearAlgebra.Transpose{Float32,CuArray{Float32,2}},CuArray{Float32,1},Nothing,Nothing}} keys must be a subset of NamedTuple{(:Wi, :Wh, :b, :h, :c),NTuple{5,Nothing}} keys`

**Comment by zqni** [comment]
@jeremiedb I appreciate it a lot and I must get something mixed up before. When opening a new notebook, I got the same results as your codes.
