### ISSUE TITLE
Normalization layers promote eltype

### ISSUE THREAD

**Issue by DrChainsaw** [FluxML/Flux.jl#1562]
Reason is that scalars (e.g. momentum and epsilon) are always `Float32`s. This also masks the issue when using `Float64`s.

```julia
julia> bn32 = BatchNorm(4)
BatchNorm(4)

julia> bn16 = Flux.paramtype(Float16, bn32)
BatchNorm(4)

julia> eltype.(Flux.params(bn16))  # [edited]
2-element Vector{DataType}:
 Float16
 Float16

julia> data32 = randn(Float32, 4, 3);

julia> bn32(data32)
4×3 Matrix{Float32}:
  1.44632     0.801638   0.750056
  0.131405    1.01101    1.57935
 -0.0489822  -2.75201   -0.854299
  0.310867    0.288718  -0.606384

julia> data16 = Float16.(data32);

julia> bn16(data16)
4×3 Matrix{Float32}:
  1.49415      0.843725   0.791455
  0.21807      1.09792    1.66641
 -0.00660238  -2.77763   -0.832589
  0.302387     0.280992  -0.590986
```

One way could be to change constructors to always change the type of the scalars to be of the same types as the params. Another way which might be a little less code is to change `_norm_layer_forward` to convert to the same types as the parameters. The latter has the advantage that it should make `Float16` normalization layers work with CUDA (which does not have `sqrt` intrinsics for half types). Besides convert overhead, drawback is that the day it does, normalization layers will still use the (presumably slower) float `sqrt` until someone thinks about updating `_norm_layer_forward`.

Example of modified `_norm_layer_forward`:

```julia
using Flux
using Flux: _isactive, hasaffine
using Statistics
using Flux.Zygote
function Flux._norm_layer_forward(l, x::AbstractArray{T,N}; reduce_dims, affine_shape) where {T, N}
  if !_isactive(l) && l.track_stats # testmode with tracked stats
    stats_shape = ntuple(i -> i == N-1 ? size(x, N-1) : 1, N)
    μ = reshape(l.μ, stats_shape)
    σ² = reshape(l.σ², stats_shape)
  else  # trainmode or testmode without tracked stats
    μ = mean(x; dims=reduce_dims)
    σ² = mean((x .- μ).^2; dims=reduce_dims)
    if l.track_stats
      ## update moving mean/std
      Zygote.ignore() do
        mtm = convert(eltype(l.β), l.momentum)
        m = prod(size(x, i) for i in reduce_dims)  # needed for computing corrected var
        μnew = vec(N ∈ reduce_dims ? μ : mean(μ, dims=N))
        σ²new = vec(N ∈ reduce_dims ? σ² : mean(σ², dims=N))
        l.μ = (1-mtm) .* l.μ .+ mtm .* μnew
        l.σ² = (1-mtm) .* l.σ² .+ mtm .* (m / (m - one(eltype(l.σ²)))) .* σ²new
      end
    end
  end
  if hasaffine(l)
    γ = reshape(l.γ, affine_shape)
    β = reshape(l.β, affine_shape)
    return l.λ.(γ .* (x .- μ) ./ convert.(eltype(β), sqrt.(σ² .+ l.ϵ)) .+ β)
  else
    return l.λ.((x .- μ) ./ convert.(eltype(β), sqrt.(σ² .+ l.ϵ)))
  end
end

julia> bn16(data16)
4×3 Matrix{Float16}:
  1.494      0.8438   0.7915
  0.218      1.098    1.666
 -0.006603  -2.777   -0.8325
  0.3022     0.281   -0.591


julia> gs16 = gradient(() -> sum(bn16(data16)), params(bn16))
Grads(...)

julia> gs16[bn16.γ]
4-element Vector{Float16}:
 -0.001465
 -0.003906
  0.001221
  0.000977

julia> gs16[bn16.β]
4-element Vector{Float16}:
 3.0
 3.0
 3.0
 3.0
``` 

I can draft a PR for either option (or some other alternative) if wanted.

**Comment by DhairyaLGandhi** [comment]
Sounds like fixing the `_norm_layer_forward` is the right move here

**Comment by DhairyaLGandhi** [comment]
Possibly should be rolled into #1509

**Comment by darsnack** [comment]
Yeah I believe the old BN and friends had the call to `convert` in there for this reason. Looks like that got lost in the refactor. Agree that #1509 is the best place to add this.

**Comment by DrChainsaw** [comment]
Alright, I'll sit tight then until 1509 gets merged!

**Comment by DrChainsaw** [comment]
Heads up in case you aren't aware already: CUDA does not seem to like convert (or adapt), it fails with `KernelError: passing and using non-bitstype argument`. Seems like broadcasted type constructors are ok, e.g `Float16.(x)` or ` eltype(β).(sqrt.(σ² .+ l.ϵ))`.

**Comment by DrChainsaw** [comment]
Fwiw, CUDA does now support `sqrt` for `Float16`, so Float16 batchnorm works as long as momentum and epsilon are Float16.
