### ISSUE TITLE
Recurrent cell `eltype` restriction breaks `outputsize`

### ISSUE THREAD

**Issue by darsnack** [FluxML/Flux.jl#1565]
Since `outputsize` works by passing an array of `eltype(x) == Nil`, it will result in a `MethodError` when applied to recurrent cells.

**Comment by DhairyaLGandhi** [comment]
In light of the incoming issues about the type restrictions, the correct play seems to be to loosen them or get rid of them. The latter might be more suited to flux design, and we can document usage of single precision like every other flux layer.
