### ISSUE TITLE
Issue with Flux.jl installation

### ISSUE THREAD

**Issue by ArthurMendesAlves** [FluxML/Flux.jl#1568]
Hi, i'm having some trouble with Flux.jl installation. It appears this message:
(@v1.6) pkg> add Flux
Updating registry at C:\Users\arthu\.julia\registries\General
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Flux [587475ba]:
Flux [587475ba] log:
├─possible versions are: 0.4.1-0.12.1 or uninstalled
├─restricted to versions * by an explicit requirement, leaving only versions 0.4.1-0.12.1
├─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.4.1-0.10.4, 0.11.2-0.12.1] or uninstalled, leaving only versions: [0.4.1-0.10.4, 0.11.2-0.12.1]
│ └─CUDA [052768ef] log:
│ ├─possible versions are: 0.1.0-2.6.3 or uninstalled
│ ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-2.6.3
│ └─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-2.6.3] or uninstalled, leaving only versions: [2.3.0, 2.5.0-2.6.3]
├─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: 0.4.1-0.11.1 or uninstalled, leaving only versions: 0.4.1-0.10.4
│ └─StatsBase [2913bbd2] log:
│ ├─possible versions are: 0.24.0-0.33.4 or uninstalled
│ ├─restricted by compatibility requirements with OnlineStats [a15396b6] to versions: 0.24.0-0.33.4
│ │ └─OnlineStats [a15396b6] log:
│ │ ├─possible versions are: 0.19.0-1.5.8 or uninstalled
│ │ ├─restricted to versions * by an explicit requirement, leaving only versions 0.19.0-1.5.8
│ │ └─restricted by compatibility requirements with JuliaDB [a93385a2] to versions: [0.19.0-0.23.0, 1.0.0-1.5.8]
│ │ └─JuliaDB [a93385a2] log:
│ │ ├─possible versions are: 0.9.0-0.13.1 or uninstalled
│ │ └─restricted to versions * by an explicit requirement, leaving only versions 0.9.0-0.13.1
│ └─restricted by compatibility requirements with JuliaDB [a93385a2] to versions: 0.24.0-0.32.2
│ └─JuliaDB [a93385a2] log: see above
└─restricted by compatibility requirements with NNlib [872c559c] to versions: 0.11.0-0.12.1 or uninstalled — no versions left
└─NNlib [872c559c] log:
├─possible versions are: 0.3.2-0.7.17 or uninstalled
└─restricted by compatibility requirements with CUDA [052768ef] to versions: 0.7.7-0.7.17
└─CUDA [052768ef] log: see above
Could someone help me to figure out what's wrong? Thanks!

**Comment by DhairyaLGandhi** [comment]
Seems like you have some old cuda version in the project. I would start in a fresh environment using `] activate --temp` before the `add`

**Comment by ArthurMendesAlves** [comment]
@DhairyaLGandhi, it worked perfectly. Thanks!
