### ISSUE TITLE
Stable docs are stuck on v0.11.2 

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/Flux.jl#1580]
This doesn't appear to have been fixed by the 0.12 and 0.12.1 CI fixes. Does anybody know what's going on?

**Comment by DhairyaLGandhi** [comment]
Seemed like it pushed it to `dev` fine, but didn't make a tag ever. Will push one out manually in the morning

**Comment by ToucheSir** [comment]
Is there any way to troubleshoot why it wasn't auto-tagging for stable releases? Or was that never an automated process?

**Comment by DhairyaLGandhi** [comment]
Closed in https://github.com/FluxML/Flux.jl/commit/cde0a4590c16d61bd9e2f6a52ccfe48a2d3014cb
