### ISSUE TITLE
Warning using Flux on Linux device without CUDA or Nvidia card

### ISSUE THREAD

**Issue by JamieMair** [FluxML/Flux.jl#1581]
Hi,

I have been getting the following error everytime I use `using Flux` in my code.
`
modprobe: ERROR: could not insert 'nvidia': No such device
`
This says there is an error, however, the code still runs okay.

I am using Julia v1.6.0 and Flux v0.12.1

The machine this is being run on does not have CUDA or any nVidia devices attached.

Regards,
Jamie

**Comment by DhairyaLGandhi** [comment]
That's odd, you might want to open an issue on CUDA.jl

**Comment by ToucheSir** [comment]
Yup, this kind of error is 100% on CUDA.jl.
