### ISSUE TITLE
No `tobatch` function defined. `Utils.jl`

### ISSUE THREAD

**Issue by abcsds** [FluxML/Flux.jl#159]
As half-writen in #46 the `tobatch` function called in line 79 of the `utils.jl` file does not exist. It's not a julia function. They mention it could have been left in a different branch or commit,  but I cannot find it by searching the repo. This same accuracy function calls the `argmax` function which doesn't exist in julia. Probably a completely new accuracy function would be useful, since the alternative to `argmax`; `findmax` is very slow.

**Comment by abcsds** [comment]
Found my error with the argmax; one must explicitly import it into the working scope. 
```julia
using Flux: onehotbatch, argmax, crossentropy, throttle
``` 
I found this in the (zoo)[https://github.com/FluxML/model-zoo/blob/master/mnist/mlp.jl#L2]. I'll get working on the documentation if you don't mind. Sorry if I was too quick to send an issue.

I still can't find the `tobatch` function, though.

**Comment by MikeInnes** [comment]
I thought I'd removed `accuracy` ages ago. I have now anyway. It's pretty easy to just [write it out](https://github.com/FluxML/model-zoo/blob/07eb0b32ab7ae6e64f3c3f064df0dfafd3d34599/mnist/mlp.jl#L26).

Docs patches always welcome!
