### ISSUE TITLE
Do not initialize CUDA during precompilation

### ISSUE THREAD

**Issue by maleadt** [FluxML/Flux.jl#1597]
This is wrong: https://github.com/FluxML/Flux.jl/blob/8a5b9774f0d6b254f60c88ca07a984997a016e75/src/losses/Losses.jl#L27

This should be guarded by a check `if !precompiling`: https://github.com/FluxML/Flux.jl/blob/8a5b9774f0d6b254f60c88ca07a984997a016e75/src/Flux.jl#L59-L61

Additionally, this shouldn't be done during `__init__`, but lazily when first calling the `gpu` function.

**Comment by DhairyaLGandhi** [comment]
We already use the flag in `gpu` as well. Are you saying we skip this check here entirely and have `gpu` set the flag on first call and then use that consequently? Currently it's hidden behind a `Ref{Bool}` so we need something to say "hasn't been initialised yet", with `missing` or `nothing`

**Comment by maleadt** [comment]
I think that would be better for users with a GPU, but who don't plan to use it (so that `using Flux` doesn't start downloading the large CUDA artifacts). I'll explore that in the multi GPU back-end PR.

**Comment by darsnack** [comment]
In lieu of the long term fix, should we release a quick fix for the losses issue? Would using `use_cuda[]` instead of `CUDA.functional()` work?

**Comment by DhairyaLGandhi** [comment]
It's the same either way. Fixing the init would be better.

**Comment by IanButterworth** [comment]
It'd be nice to have this fixed. Downloading during precompilation is pretty awkward with the new Pkg auto precompilation, especially on a slow connection given the output during precomp is suppressed, so it's not clear that a download is happening

**Comment by IanButterworth** [comment]
Friendly bump on this
