### ISSUE TITLE
Flux downloads CUDA110 Artifacts every time I precompile on Ubuntu

### ISSUE THREAD

**Issue by arvindmohan** [FluxML/Flux.jl#1600]
I have these artifacts already installed. So every single time I load `using Flux` I get `Downloading artifact: CUDA110` . This can be quite time-consuming and impractical to use. I never had this issue until I updated to v0.12.3 on Julia 1.6. Is there a way to Fix it?

Currently I `Ctrl+C` the CUDA artifact download and Flux works just fine afterwards. Problem is, I cannot do this in a Pluto notebook as it throws a cell termination error. Would appreciate any help fixing: Is this a bug, or a local issue?

**Comment by darsnack** [comment]
Related to https://github.com/FluxML/Flux.jl/issues/1597

**Comment by ToucheSir** [comment]
Per https://github.com/FluxML/Flux.jl/pull/1711, this has been fixed for a while.
