### ISSUE TITLE
@epochs is missing a bracket

### ISSUE THREAD

**Issue by CrookedGrandma** [FluxML/Flux.jl#1615]
This is a very minor issue, but when using `@epochs`, it prints `[ Info: Epoch x`. I imagine there should be an extra square bracket in there, either at the end or after the colon. Here's a screenshot:

![image](https://user-images.githubusercontent.com/23079500/121878709-51c37e00-cd0c-11eb-8d9c-156a02814754.png)

**Comment by darsnack** [comment]
I think this was intentional to act more like a left margin than a bracket.

**Comment by ToucheSir** [comment]
This is the default logging format in Julia and does not have any Flux-specific behaviour.
```julia
julia> @info "test"
[ Info: test
```

**Comment by darsnack** [comment]
Thanks, closing this then.
