### ISSUE TITLE
Flux Overview Documentation Out of Date

### ISSUE THREAD

**Issue by Zenthial** [FluxML/Flux.jl#1621]
The Provide Training and Test Data header is out of date with https://github.com/FluxML/Flux.jl/blob/master/docs/src/models/overview.md

`y_train, y_test = actual.(x_train), actual.(y_train)` should be `y_train, y_test = actual.(x_train), actual.(x_test)`, as it is in the overview.md

https://fluxml.ai/Flux.jl/stable/models/overview/

**Comment by DhairyaLGandhi** [comment]
https://fluxml.ai/Flux.jl/dev/models/overview/ should have the expected verbiage. The docs would be updated with a release.

**Comment by DhairyaLGandhi** [comment]
Thanks for pointing it out @Zenthial !
