### ISSUE TITLE
Documentation for I/O

### ISSUE THREAD

**Issue by dented42** [FluxML/Flux.jl#163]
It would be nice if the documentation mentioned reading and writing trained neural networks to/from the filesystem.

**Comment by MikeInnes** [comment]
I think this is fixed with the new [saving & loading](http://fluxml.ai/Flux.jl/stable/saving.html) docs, but let me know if anything's unclear!

**Comment by dented42** [comment]
That definitely covers all of the questions I wanted answers to. Thanks!
