### ISSUE TITLE
Where are the `cpu()` and `gpu()` functions? 

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/Flux.jl#1631]
I am trying to see the docs for the `cpu` and `gpu` functions. When I do the following: 
```Julia

help?> cpu
search: cpu CapturedException ComposedFunction

  No documentation found.

  Flux.cpu is a Function.

  # 1 method for generic function "cpu":
  [1] cpu(m) in Flux at /Users/logankilpatrick/.julia/packages/Flux/qXNjB/src/treelike.jl:60
```
it says `src/treelike.jl:60` should be where I find this code but that file does not exist. Where can I find the code for these functions?

**Comment by ToucheSir** [comment]
Hmm, treelike.jl has been removed for at least a couple major versions now. Can you check that Flux is up to date?

**Comment by DhairyaLGandhi** [comment]
`src/functor.jl`

I'm closing this since this seems to be a version compatibility issue, but feel free to open if not.

**Comment by logankilpatrick** [comment]
Yep that’s what it must have been! Thanks all. 

Best, 
Logan Kilpatrick
