### ISSUE TITLE
How to tell Flux.jl not to use the GPU?

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/Flux.jl#1644]
Per here: https://stackoverflow.com/questions/68195038/how-to-tell-flux-jl-not-to-use-the-gpu is using `Flux.use_cuda[]` the correct way to disable to GPU? Or is this more of a user facing flag that I should not be setting manually?

**Comment by logankilpatrick** [comment]
Feel free to just answer the question on SO and close this issue.

**Comment by DhairyaLGandhi** [comment]
CUDA has a `CUDA_VISIBLE_DEVICES` env var which can be unset to disable picking up any GPU, or even choose only specific ones to be available to a process. Would you mind passing that along to SO?
