### ISSUE TITLE
Missing docs for @functor

### ISSUE THREAD

**Issue by Gregliest** [FluxML/Flux.jl#1653]
The links to [Flux.@functor](https://fluxml.ai/Flux.jl/stable/models/advanced/models/@ref) appear to be broken, such as [here](https://fluxml.ai/Flux.jl/stable/models/advanced/#Custom-multiple-input-or-output-layer). I can't tell where the link is supposed to go, is it to [Functors.jl](https://github.com/FluxML/Functors.jl)?

**Comment by DhairyaLGandhi** [comment]
Yeah, Functors.jl seems like the right place to put it. cc @logankilpatrick who I know was interested in seeing some docs improvements.

**Comment by ToucheSir** [comment]
We even have docstrings in Functors.jl, just not a docs site to go with them. I opened https://github.com/FluxML/Functors.jl/issues/15 a couple days ago because I don't have the time/expertise to set one up, so contributions welcome!

**Comment by logankilpatrick** [comment]
Happy to help with this, swamped over the next week but should be able to help soon!
