### ISSUE TITLE
typo in the docs/overview section right at the beginning

### ISSUE THREAD

**Issue by ptoche** [FluxML/Flux.jl#1663]
https://fluxml.ai/Flux.jl/stable/models/overview/ 

julia> y_train, y_test = actual.(x_train), actual.(y_train)

should be

julia> y_train, y_test = actual.(x_train), actual.(x_test)

**Comment by ToucheSir** [comment]
Dupe of https://github.com/FluxML/Flux.jl/pull/1641. Fix was in https://github.com/FluxML/Flux.jl/pull/1608 and just hasn't made it into a patch release yet.
