### ISSUE TITLE
Multiple calls on model is slow 

### ISSUE THREAD

**Issue by mfalt** [FluxML/Flux.jl#167]
Sorry for the long question, I am trying to figure out why multiple calls on a model can be very slow with Flux. I thought that this is partly because of a lot of type instability in the code, but I am not sure. For example, calling the model is itself type unstable.
I realize that this would be less of a problem if the data can be batched in larger sets, but it seems like this is not always possible, for example with RNNs?

In the following example, we have 1000 data series, each having different number of observations (between 4 and 100). Each observation is two numbers. Since the data have different lengths I don't think it is possible to stack them all in a  big matrix/tensor. And it also seems that it is not even possible to make the RNN layer handle the whole series at once, without calling the model several times? 
```julia
using Flux: TrackedArray, param, mse

m = Chain(Dense(2, 32) ,RNN(32, 32), Dense(32,2))

observation() = randn(2, rand(4:100))
data = [observation() for i in 1:1000]

xs = ([data[i][:,j] for j in 1:size(data[i],2)-1] for i in 1:length(data))
ys = ([data[i][:,j] for j in 2:size(data[i],2)  ] for i in 1:length(data))

function loss1(xin,yin)
    l = param(reshape([0.]))
    for (x,y) in zip(xin,yin)
        # Annotate to avoid type instability to propagate
        mx = m(x)::TrackedArray{Float64,1,Array{Float64,1}}
        l += Flux.mse(mx,y)
    end
    Flux.reset!(m)
    l
end
# Type unstable version
function loss2(xin,yin)
    l = sum(mse.(m.(xin),yin))
    Flux.reset!(m)
    l
end

opt = ADAM(params(m),0.001)

# Equally slow
@time Flux.train!(loss1, zip(xs,ys), opt)
@time Flux.train!(loss2, zip(xs,ys), opt)
```
If we try to stack the variables instead, the code runs 10 times faster, but RNN does something wrong
```julia

function loss3(xin,yin)
    l = sum(mse(m(xin),yin))
    Flux.reset!(m)
    l
end

xs2 = (data[i][:,1:end-1] for i in 1:length(data))
ys2 = (data[i][:,2:end  ] for i in 1:length(data))

# 10 times faster, but wrong
@time Flux.train!(loss3, zip(xs2,ys2), opt)

#Different results, only same at first time step
Flux.reset!(m)
@show m.(first(xs))
Flux.reset!(m)
@show m(first(xs2))
```

One example of the type instability I can see is that `Chain` is storing the layers as `Vector{Any}` and that `Recurr` has no type annotation on `init` and `state`. But even if I try to fix that (and declare `m` `const`) , there is still a slowdown of a factor 10.
What is the RNN node actually doing on this second example, is this a bug?
And are there any plans/ambitions to make the package type stable? The only way I was able to do it with `Chain` was to unroll the layers using `@generated`, but it seems tricky to make `Recurr` type stable.

**Comment by MikeInnes** [comment]
In your last example, the issues is probably that you're not mapping over the sequence; the RNN layers aren't designed to accept a single array representing a whole sequence (at the moment).

One way to handle the batching here is to pad each sentence to a common length with some kind of "end" token. So a batch of two sequences `[w1, w2]` and `[v1, v2, v3]` becomes `[[w1; v1], [w2; v2], [end; v3]]`.

RE type stability; it would be interesting to quantify the cost of this. It's possible to make `Chain` type-stable by folding a sequence into `Chain{Layer1,Layer2}`, but I'm not sure the compilation cost would be worthwhile. For RNNs, we can make the fields type stable once cassette is working.

**Comment by boathit** [comment]
@MikeInnes To address this problem, I think we need to provide some utilities to return the **real** last hidden states of RNN for a batch of variable-length sequences such as the [`pack_padded_sequence`](http://pytorch.org/docs/master/nn.html#pack-padded-sequence) in PyTorch.

**Comment by MikeInnes** [comment]
Right, you can't just put NaNs in your input data. The easiest way to deal with this is to create a special "end of sequence" marker to pad your sequences, e.g.
```julia
alphabet = [:a, :b, :c, :end]
# Pad a sequence of length 4 to length 6
seq = onehotbatch([:b, :c, :a, :c, :end, :end], alphabet)
```
The expectation here is that the model will learn to ignore the trailing end markers and behave as if the sequence were shorter.

The other way to do this is with masking as @boathit points out. It's perfectly feasible to implement this yourself by multiplying outputs by `0` at appropriate times (this would erase the gradient and avoid your NaN issue). It'd be nice to have more utilities for that, though.

**Comment by jekbradbury** [comment]
@boathit Utilities for masking for variable-length sequences are in-progress in github.com/jekbradbury/Minibatch.jl

**Comment by boathit** [comment]
@jekbradbury Glad to hear about that.
