### ISSUE TITLE
update! a scalar parameter

### ISSUE THREAD

**Issue by rlrs** [FluxML/Flux.jl#1677]
I'm trying to optimize a single parameter in an array, but I run into an issue that depends on which optimizer I try.
For example,

```
using Flux
table = randn(2,2)
e = 1.0
x = @view table[1, 1]
dx = @view [e][1]
Flux.Optimise.update!(Descent(), x, dx)
```

> ERROR: LoadError: DimensionMismatch("cannot broadcast array to have fewer dimensions")
> Stacktrace:
>  [1] check_broadcast_shape(#unused#::Tuple{}, Ashp::Tuple{Base.OneTo{Int64}})
>    @ Base.Broadcast ./broadcast.jl:518
>  [2] check_broadcast_axes
>    @ ./broadcast.jl:523 [inlined]
>  [3] check_broadcast_axes
>    @ ./broadcast.jl:527 [inlined]
>  [4] instantiate
>    @ ./broadcast.jl:269 [inlined]
>  [5] materialize!
>    @ ./broadcast.jl:894 [inlined]
>  [6] materialize!
>    @ ./broadcast.jl:891 [inlined]
>  [7] update!(opt::Descent, x::SubArray{Float64, 0, Matrix{Float64}, Tuple{Int64, Int64}, true}, x̄::SubArray{Float64, 0, Vector{Float64}, Tuple{Int64}, true})
>    @ Flux.Optimise ~/.julia/packages/Flux/ma5BY/src/optimise/train.jl:26
>  [8] top-level scope
>    @ ~/nie/scripts/test.jl:17

With ADAM, something different happens,
```
using Flux
table = randn(2,2)
e = 1.0
x = @view table[1, 1]
dx = @view [e][1]
Flux.Optimise.update!(ADAM(), x, dx)
```

> ERROR: LoadError: TypeError: in typeassert, expected Tuple{SubArray{Float64, 0, Matrix{Float64}, Tuple{Int64, Int64}, true}, SubArray{Float64, 0, Matrix{Float64}, Tuple{Int64, Int64}, true}, Vector{Float64}}, got a value of type Tuple{Array{Float64, 0}, Array{Float64, 0}, Vector{Float64}}
> Stacktrace:
>  [1] apply!(o::ADAM, x::SubArray{Float64, 0, Matrix{Float64}, Tuple{Int64, Int64}, true}, Δ::Vector{Float64})
>    @ Flux.Optimise ~/.julia/packages/Flux/ma5BY/src/optimise/optimisers.jl:177
>  [2] update!(opt::ADAM, x::SubArray{Float64, 0, Matrix{Float64}, Tuple{Int64, Int64}, true}, x̄::SubArray{Float64, 0, Vector{Float64}, Tuple{Int64}, true})
>    @ Flux.Optimise ~/.julia/packages/Flux/ma5BY/src/optimise/train.jl:26
>  [3] top-level scope
>    @ ~/nie/scripts/test.jl:17

Here, both x and dx are 0-dimensional views. Is there a different, correct way to perform this update?
In case it's useful,
`]st Flux`
>[587475ba] Flux v0.12.5

**Comment by DhairyaLGandhi** [comment]
this used to work, I'm guessing the array interface/ mutation pr broke it? Could you test with Optimisers.jl?

**Comment by rlrs** [comment]
I'm not quite sure of the interface for Optimisers, like this?

```
using Optimisers: Descent

table = randn(2,2)
e = 1.0
x = @view table[1, 1]
dx = @view [e][1]
opt = Descent()
opt(nothing, x, dx)
```
>(nothing, -0.49776332332583917)

**Comment by darsnack** [comment]
It's the same as Flux with the addition of externally tracked state:
```julia
opt = Descent()
st = state(opt)
x, st = update(opt, st, x, dx)
```

**Comment by rlrs** [comment]
I updated the OP with more information. Also, while this does work, it doesn't update `table`,
```
using Flux
using Optimisers: Descent, state, update

table = randn(2,2)
e = 1.0
x = @view table[1, 1]
dx = @view [e][1]
opt = Descent()
st = state(opt, [])
(st, x) = update(opt, st, x, dx)
```

**Comment by ToucheSir** [comment]
Unlike the current Flux one, the `Optimisers.jl` API doesn't mutate the parameters you give it. You have to use the returned value from `update`:
```julia
using Optimisers

table = randn(2,2)
e = 1.0
x = table[1, 1]
dx = e

opt = Descent()
st = Optimisers.init(opt)  # this is nothing because Descent doesn't have any internal state
st, x′ = Optimisers.update(opt, st, x, dx)
table[1, 1] = x′ # manual update
```
