### ISSUE TITLE
Support NamedTuples for Container Layers

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/Flux.jl#1680]
This came up in https://github.com/FluxML/Metalhead.jl/pull/70 and surprised me, because I thought we supported this already! 

Other than `Chain`, are there any other layers we'd want to support this? The only other one that uses a tuple field is `Parallel`, but since it doesn't forward methods to `.layers` I'm not sure this is applicable.

Another thing using NamedTuples would open up is the possibility of defining aliases for `Chain`. e.g. 
```julia
const ResNetBlock{C1,C2,N} = Chain{NamedTuple{(:conv1, :conv2, :norm), Tuple{C1, C2, N}}}
```

**Comment by darsnack** [comment]
I think this in combo with @mcabbott's "big show" would make models really readable. Like big show can print the names alongside the other info.

Is forwarding methods conceptually linked here (am I missing something)? For `Parallel` it would be nice to name the branches. I could see this being really useful for inception modules.

**Comment by DhairyaLGandhi** [comment]
That works already in the sense that we can optionally store named tuples, what was spoken about in the discussion was how to leveraging it for larger models.

Forwarding indexing would be needed. The printing is really to have custom show methods, since the `Chain` aren't as meaningful as the concept they represent.

**Comment by darsnack** [comment]
`Chain` is one of those weird layers in that its types/constructor are extremely restrictive: https://github.com/FluxML/Flux.jl/blob/0a215462ad8e0ba795205c9e94864403207d63fa/src/layers/basic.jl#L26-L29

**Comment by darsnack** [comment]
I think `Parallel` does forward indexing to the branches?
