### ISSUE TITLE
Flux tests with master fail with signal 11

### ISSUE THREAD

**Issue by colbec** [FluxML/Flux.jl#1697]
Using 
```
Julia Version 1.8.0-DEV.385
Commit 310bf160e0* (2021-08-23 02:42 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
```
`pkg test Flux` (Flux v0.12.6) produces an error with signal received 11. [Gist of output here](https://gist.github.com/colbec/4ba9fb19b56a2b51b27b8e3fad1a94ec). Test with 1.6.2 completes without error.

**Comment by DhairyaLGandhi** [comment]
Seems like a segfault at `utils.jl:238`. I haven't seen this before, I'm wondering if this is a Julia issue since this is running a 1.8 custom build.

**Comment by colbec** [comment]
I'm not aware of running a custom version, not deliberately anyway, just a pkg update. Although it is true I get a message as the test starts 
```
(@v1.8) pkg>  test Flux
     Testing Flux
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations ~/gitprogs/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1489
```
If you could advise how to re-set the installation I can re-test.

**Comment by ToucheSir** [comment]
Dhairya meant that you're running a nightly version of Julia itself. IIRC we've been having a similar erroron nightly CI, caused by an external package that we use in tests but doesn't support Julia 1.8 at present.

**Comment by colbec** [comment]
Ok thanks, I will close this then and try testing again in a few days, using 1.6.2 for any work in the meantime.

**Comment by ToucheSir** [comment]
FWIW, I've been running Flux on 1.7 betas for a few weeks now with no hiccups. Nightly may well work, but because of how many external packages are involved in the tests those may not.
