### ISSUE TITLE
Recurrent docs out of sync

### ISSUE THREAD

**Issue by darsnack** [FluxML/Flux.jl#1714]
Looking at the blame for the recurrence doc page, [this line](https://github.com/FluxML/Flux.jl/blame/cea8f752161415de51d971ad9aa9c2be7a4f1e7a/docs/src/models/recurrence.md#L75) was updated to only have a single output, but the rest of the tutorial was not updated.

**Comment by ToucheSir** [comment]
Should've been fixed by https://github.com/FluxML/Flux.jl/pull/1763.
