### ISSUE TITLE
[Documentation] No `logsumexp` in NNlib page

### ISSUE THREAD

**Issue by JinraeKim** [FluxML/Flux.jl#1718]
In [NNlib page](https://fluxml.ai/Flux.jl/stable/models/nnlib/), I cannot find a documentation of `logsumexp`, while it's written [here](https://github.com/FluxML/NNlib.jl/blob/master/src/softmax.jl#L133).

I think it would be better to expose this function explicitly.

**Comment by JinraeKim** [comment]
One more: why is it numerically stable? Can you share any references or small comments?

**Comment by DhairyaLGandhi** [comment]
Yes, that would require an addition to https://github.com/FluxML/Flux.jl/blob/master/docs/src/models/nnlib.md

I pushed out a quick PR to add it in. 

https://gregorygundersen.com/blog/2020/02/09/log-sum-exp/ seems like a decent explanation of why it's stable.

**Comment by JinraeKim** [comment]
@DhairyaLGandhi Thank you!
