### ISSUE TITLE
Random Gradient Faliures

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#172]
I thought I noticed this on a project I was working on last night, but messing with the test sets just now caused me to notice that it appears gradients are randomly failing.

Running this test `@test gradtest((x, W, b) -> σ.(W*x .+ b), 5, (2,5), 2)` passes most of the time. But it appears somewhat randomly that the test doesn't pass.

```
@testset begin
  for i in 1:100
    @test gradtest((x, W, b) -> σ.(W*x .+ b), 5, (2,5), 2)
  end
end #=> Some tests did not pass: 97 passed, 3 failed, 0 errored, 0 broken.
```

**Comment by jessebett** [comment]
Sometimes I'm getting ~1-5% failure rate. Try increasing the testset to `i in 1:1000` to more consistently show these fails rates.

Also it appears this is happening for every test at least in the `tracker.jl` tests.

**Comment by iblis17** [comment]
The underlying implementation of `gradtest` is finite difference, maybe you can try to tune the `rtol` of `isapprox`, or change the `delta` of implementation.

see https://github.com/FluxML/Flux.jl/blob/f22cfb5b4341eba30b834e2655437fe13bf3b265/src/tracker/numeric.jl#L7-L22

**Comment by MikeInnes** [comment]
Yeah, this is almost certainly just a numerical issue (you could seed the RNG in the snippet above to verify that). I'm not sure how best to avoid that – numerical testing is hard – but given that we [seed the RNG in Flux tests](https://github.com/FluxML/Flux.jl/blob/f22cfb5b4341eba30b834e2655437fe13bf3b265/test/runtests.jl#L3), it shouldn't cause too much of an issue in practice.

**Comment by MikeInnes** [comment]
I don't think there's an action item here, but feel free to complain if there should be.
