### ISSUE TITLE
Flattened data vs Flux.flatten layer in MNIST MLP in the model zoo

### ISSUE THREAD

**Issue by congUoM** [FluxML/Flux.jl#1722]
I post this issue in the model-zoo repo but I think it may be an issue with Flux.jl itself
[Flattened data vs Flux.flatten layer in MNIST MLP in the model zoo](https://github.com/FluxML/model-zoo/issues/316)

**Comment by CarloLucibello** [comment]
issue discussed and closed in model-zoo
