### ISSUE TITLE
Investigate nightly CI build issues

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/Flux.jl#1724]
e.g. latest commit of this writing: https://github.com/FluxML/Flux.jl/runs/3708588387

We're currently failing on https://github.com/JuliaArrays/ArrayInterface.jl/pull/205, which should've been fixed in ArrayInterface@3.1.33. Flux has a compat bound on 3.1 and I was able to add the new version locally without any conflicts, so do we just need to bump the Manifest?

**Comment by CarloLucibello** [comment]
Our Manifest is 2 months old, we should get rid of it or automatize the update, the current situation really doesn't make sense.

**Comment by CarloLucibello** [comment]
let's see if CI in #1725 goes all green

**Comment by DhairyaLGandhi** [comment]
We have updated it in #1708 and can automate updating it too.

**Comment by ToucheSir** [comment]
Seems like we're back to `BoundsError(a=Array{Core.Compiler.VarState, (3,)}[Core.Compiler.VarState(typ=Core.Const(val=ZygoteRules._pullback), undef=false), Core.Compiler.VarState(typ=Zygote.Context, undef=false), Core.Compiler.VarState(typ=Core.Const(val=Main.var"#13"), undef=false)], i=(4,))`. Did anyone ever figure out what that was about?

**Comment by ToucheSir** [comment]
Zygote is good as of https://github.com/FluxML/Zygote.jl/pull/1125, I guess we'll see what's left once a new patch release is cut.
