### ISSUE TITLE
OpenCL support

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#173]
Tracking the issues we have getting OpenCL support.

- [x] `adapt` integration: https://github.com/JuliaGPU/CLArrays.jl/pull/16
- [x] Dual number support: https://github.com/JuliaGPU/CLArrays.jl/issues/17
- [ ] Integration with `Flux.gpu`
- [ ] GPU-compatible softmax: https://github.com/JuliaGPU/GPUArrays.jl/issues/96
- [ ] Convolutions: https://github.com/JuliaGPU/GPUArrays.jl/issues/102

Worth checking out ROCm and MIOpen as part of this.

**Comment by ViralBShah** [comment]
@sdanisch

**Comment by SimonDanisch** [comment]
on it :) most is done, just waiting for tags & tests to turn green

**Comment by SimonDanisch** [comment]
Allirght: https://github.com/JuliaLang/METADATA.jl/pull/13419

**Comment by yblainm** [comment]
Hello! Does anyone know what the status of OpenCL support is?

**Comment by jpsamaroo** [comment]
CLArrays is broken due to Transpiler not being updated for Julia 1.0 (which is unlikely to happen unless some adventurous individual cares to take that on), so automatic conversion of Julia code (i.e. Flux models and functions) is not currently possible.

**Comment by dented42** [comment]
Is ArrayFire a potential alternative that could be used as an underlying representation for OpenCL support?

**Comment by MikeInnes** [comment]
Yes, supporting ArrayFire arrays may be a good idea as well. I'm not sure what they're like convolutiosn wise but the basics should be straightforward.

**Comment by jpsamaroo** [comment]
FYI for anyone still watching this thread, #938 will address this for AMD GPUs by skipping OpenCL and using ROCArrays instead.

**Comment by MikeInnes** [comment]
I'll close this issue since it was pretty tied to CLArrays, and that work isn't moving any more. We can track ROCm support in #938.

**Comment by hzurt** [comment]
I see this has been closed in favor of ROCm support, however ROCm only works with a few of the newest amd gpus. Is there any way to use older AMD gpus that are not supported by ROCm with flux?
