### ISSUE TITLE
unsqueeze is not type stable

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1737]
Is there a way to make `Flux.unsqueeze` type stable? In principle the result type is determined: Given an `Array{T,N}` as input, the output is an `Array{T,N+1}`.

![image](https://user-images.githubusercontent.com/10637482/136196673-df333eb6-d661-41fc-af49-f5edaee7c026.png)

**Comment by ToucheSir** [comment]
I wonder if the `var"N+1"` construct used in https://github.com/FluxML/Flux.jl/blob/master/src/onehot.jl would work. Not sure how the signature could be generalized across array types, however.

**Comment by ToucheSir** [comment]
If anyone wants to tackle this, https://github.com/JuliaLang/julia/blob/master/base/reshapedarray.jl might have some goodies to pull.

**Comment by ToucheSir** [comment]
Very nice, that benchmarks way better as well. Do you mind filing a PR so that we can give you credit for this?

**Comment by cossio** [comment]
You are right,

![image](https://user-images.githubusercontent.com/10637482/139578152-28c526be-47a2-4f1d-adb6-cb31477235c9.png)

I'll do a PR.

**Comment by cossio** [comment]
Done, https://github.com/FluxML/Flux.jl/pull/1759. Please review.
