### ISSUE TITLE
Link to "train!" gives 404 page not found error on the website.

### ISSUE THREAD

**Issue by Chandu-4444** [FluxML/Flux.jl#1745]
I was looking through the docs [here](https://fluxml.ai/Flux.jl/stable/models/overview/). And when I press on `train!`, it redirected me to a 404 page.

**Comment by logankilpatrick** [comment]
This will be closed by #1784 I believe

**Comment by Chandu-4444** [comment]
> This will be closed by #1784 I believe

Yeah. I think the docs aren't updated yet to reflect the changes right? Cause I still get the same 404 error.

**Comment by logankilpatrick** [comment]
You have to switch to the dev docs. It works for one of the mentions of `train` but the other does not yet work. They should both be fixed once that PR is merged (you will have to used the dev branch till a new release is tagged).

**Comment by Chandu-4444** [comment]
Oh, ok thanks 👍

**Comment by logankilpatrick** [comment]
We can leave this open till the PR is merged and verified it fixes the issue.

**Comment by logankilpatrick** [comment]
Fixed!
