### ISSUE TITLE
Tensor Comprehensions

### ISSUE THREAD

**Issue by juliohm** [FluxML/Flux.jl#175]
Just sharing to make sure it is in your radar: https://research.fb.com/announcing-tensor-comprehensions/

It seems pretty much what Julia provides as a language, not only ML. Write simple code that is converted to efficient LLVM. Feel free to close the issue anytime, just sharing :)

**Comment by ViralBShah** [comment]
I think all of us saw that. Really cool. Closing, as not really an issue. Maybe best to share these things on discourse or the slack ML channel. Thanks for sharing anyways.
