### ISSUE TITLE
How to fast find source code of function, like Dense() Chain()

### ISSUE THREAD

**Issue by Runfa-Zhang** [FluxML/Flux.jl#1770]

**Comment by ToucheSir** [comment]
Flux is just plain Julia code, so anything you'd use in general works for functionality here as well. e.g. [`@which`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.@which) and [`@less`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.@less) for locating functiions :)

**Comment by Runfa-Zhang** [comment]
> Flux is just plain Julia code, so anything you'd use in general works for functionality here as well. e.g. [`@which`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.@which) and [`@less`](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.@less) for locating functiions :)

# Thanks very much!
