### ISSUE TITLE
How to write a seq of w_i:  w_1, w_2, ... , w_1000

### ISSUE THREAD

**Issue by Runfa-Zhang** [FluxML/Flux.jl#1773]
How to write a seq of w_i
```
w_1, w_2, ... , w_1000
```

**Comment by ToucheSir** [comment]
Duplicate of https://github.com/FluxML/NNlib.jl/issues/365. Again, please use the community forums (Discourse, Slack, Zulip, etc.) for questions. This repository is for issues and feature requests for Flux.jl specifically. If you need assistance with translating questions, also check out the resources on https://cn.julialang.org/.
