### ISSUE TITLE
Differentiating through my custom struct its restructuring throws an error

### ISSUE THREAD

**Issue by JTaets** [FluxML/Flux.jl#1796]
Title says all.

I could boil down my errors to this mwe.
``` Julia
using Flux

struct Model
    model
    offset
end
@Flux.functor Model (model,)
(m::Model)(x) =m.model(x+m.offset)

model = Model(Dense(1,1),[4])
p,re = Flux.destructure(model)
println(length(p)) #2 parameters
Flux.gradient((p)->sum(re(p)([1])),p) #doesn't work
```
The last lines throws an error `DimensionMismatch("variable with size(x) == (2,) cannot have a gradient with size(dx) == (3,)")`

**Comment by DhairyaLGandhi** [comment]
Could you try with `@functor Model`

**Comment by JTaets** [comment]
Then it works, but I don't want this offset to be differentiable

**Comment by ToucheSir** [comment]
Try `(m::Model)(x) = m.model(x + Zygote.dropgrad(m.offset))`. ref. https://fluxml.ai/Zygote.jl/latest/utils/#Zygote.dropgrad

**Comment by JTaets** [comment]
This also works for my actual case. Thank you!
