### ISSUE TITLE
remove Bors

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#1843]
It's just extra friction with no real benefit

**Comment by CarloLucibello** [comment]
I removed the restriction to merge only through bors already

**Comment by darsnack** [comment]
So what purpose does `bors` serve without the merging part? None, right? I'm in favor of deleting.

**Comment by CarloLucibello** [comment]
It can still be used for merging, only is not strictly required. But yes, basically is just a step toward removing it

**Comment by ToucheSir** [comment]
Done in https://github.com/FluxML/Flux.jl/pull/2133.
