### ISSUE TITLE
conv1d layer

### ISSUE THREAD

**Issue by staticfloat** [FluxML/Flux.jl#186]
It would be really great to have a conv1d/LocallyConnected layer.  I'd be willing to help write it, if someone points me to the right place to implement things (perhaps in NNlib?)

**Comment by MikeInnes** [comment]
You might be pleased to know that I just [rewrote the convolution API](https://github.com/FluxML/NNlib.jl/blob/a06ad3d8060d073b69a5c6ef1fb118bce088f34e/src/conv.jl#L25) to be agnostic to the number of dimensions.

This should be trivial if we just dispatch on vectors and reshape to 2D, write?

**Comment by jekbradbury** [comment]
Depending on some/all of sizes, strides, dilation, and padding choices the fastest way to do a 1D conv on GPU is usually one of (a) just run a loop along the filter size dimension with BLAS calls or (b) reshape to 2D and call cuDNN, with (a) being equal or better in my experience for the smallest filter sizes.

And I think your N-dimensional CPU conv implementation will work unmodified for 1D?

**Comment by MikeInnes** [comment]
It doesn't seem to work out of the box

```julia
julia> c = cu(Conv((2,), 3=>4))
Conv((2,), 3=>4)

julia> c(cu(rand(10,3,2)))
ERROR: CUDNNError(code 9, CUDNN_STATUS_NOT_SUPPORTED)
```

Not sure if this is something CUDNN doesn't support, or if we've done something wrong.

**Comment by jekbradbury** [comment]
cuDNN doesn't support 1D convolutions, but you can call it with a 2D input that happens to have height 1 and a filter bank that also has height 1.

**Comment by staticfloat** [comment]
It looks like `Flux` wants me to pad my vectors up with dimensions up to a 4-d tensor; if I wanted to, for instance, Chain a Dense layer into a locally connected layer, it would be nice if the `Flux.conv()` machinery accepted lower-dimensional tensors.  E.g.:

```
Flux.conv(randn(100, 1, 1, 1), ones(4, 1, 1, 1)) == Flux.conv(randn(100,1), ones(4,1)) == Flux.conv(randn(100), ones(4)) 
```

**Comment by MikeInnes** [comment]
Right, so there's two issues here: First that the conv kernels only support 2d and 3d (so only 4d and 5d inputs work). I added 1d (3d input) conv in https://github.com/FluxML/NNlib.jl/commit/65aa41912cf1e689fde1ac9754771c73841e7438.

The other issue is expanding the channel/batch dimensions. The batch is easy enough, but I'm thinking we should do it in Flux `Conv` rather than NNlib. The channel also has type-stability issues (unless we don't drop the channel on the output?), and besides that, seems like it could cause confusion if you try to batch a single-channel input. But I'm happy to see proposals here, I haven't thought it through that carefully.

**Comment by MikeInnes** [comment]
Ok, did the batch expansion in https://github.com/FluxML/Flux.jl/commit/7606b1a3997971f829e343a0af41dd3de9de0eec, so I think we're good here – but let me know if you have any other suggestions!

**Comment by MikeInnes** [comment]
Actually, I had to undo that; for some reason it breaks the type stability of the broadcast :( Need to leave it for now, but feel free to poke around with it.

**Comment by clouds56** [comment]
meet the same issue here, should we fallback to CUDA but not CuDNN when the dimensions is not 2d/3d?

**Comment by MikeInnes** [comment]
We can just re-apply that patch, but make sure that it infers properly. Just needs someone to work through it.

**Comment by bryaan** [comment]
So does Flux master support 1d CNN at this point?

**Comment by ForceBru** [comment]
What's the recommended way of doing 1D convolutions in Flux? Should I pad my data to 4 dimensions like this:

```julia
julia> layer = Conv((4, ), 1=>1)
Conv((4,), 1 => 1)  # 5 parameters

julia> layer(Float32[[1,2,3,4];;;])
1×1×1 Array{Float32, 3}:
[:, :, 1] =
 4.2415104

julia> layer(Float32[[1,2,3,4];;; [2,3,4,5]])
1×1×2 Array{Float32, 3}:
[:, :, 1] =
 4.2415104

[:, :, 2] =
 5.790003
```

Is there any way of not doing this? I'm trying to use CNNs with time series data, so I don't think I need 4 dimensions.

**Comment by ToucheSir** [comment]
Have you tried just passing in 3D data to the conv layer? I'm surprised a 4D input works at all for a 1D kernel.

**Comment by ForceBru** [comment]
@ToucheSir, oops, `Float32[[1,2,3,4];;;]` is actually 3D, not 4D... 4D input doesn't work, indeed:

```julia
julia> layer = Conv((4, ), 1=>1)
Conv((4,), 1 => 1)  # 5 parameters

julia> layer(Float32[[1,2,3,4];;;;])
ERROR: DimensionMismatch("Rank of x and w must match! (4 vs. 3)")
Stacktrace:
 [1] DenseConvDims(x::Array{Float32, 4}, w::Array{Float32, 3}; kwargs::Base.Pairs{Symbol, Any, NTuple{4, Symbol}, NamedTuple{(:stride, :padding, :dilation, :groups), Tuple{Tuple{Int64}, Tuple{Int64, Int64}, Tuple{Int64}, Int64}}})
   @ NNlib ~/.julia/packages/NNlib/tvMmZ/src/dim_helpers/DenseConvDims.jl:58
 [2] (::Conv{1, 2, typeof(identity), Array{Float32, 3}, Vector{Float32}})(x::Array{Float32, 4})
   @ Flux ~/.julia/packages/Flux/BPPNj/src/layers/conv.jl:165
 [3] top-level scope
   @ REPL[192]:1
 [4] top-level scope
   @ ~/.julia/packages/CUDA/DFAea/src/initialization.jl:52
```
