### ISSUE TITLE
Flux v0.12.9  and the Flux.Tracker.gradient is wrong, why?

### ISSUE THREAD

**Issue by hjlFrist** [FluxML/Flux.jl#1898]
Flux v0.12.9  and the Flux.Tracker.gradient is wrong, why?

**Comment by ToucheSir** [comment]
`Flux.Tracker` does not exist on v0.12.9. I'd recommend asking for help on [Discourse](discourse.julialang.org/) or Slack and following the instructions [here](https://discourse.julialang.org/t/please-read-make-it-easier-to-help-you/14757) before asking.

**Comment by hjlFrist** [comment]
thank you
