### ISSUE TITLE
UndefVarError: Call not defined

### ISSUE THREAD

**Issue by osofr** [FluxML/Flux.jl#190]
Trying to compile Flux on latest master:

```julia
julia> using Flux
INFO: Precompiling module Flux.
ERROR: LoadError: LoadError: LoadError: UndefVarError: Call not defined
```

**Comment by MikeInnes** [comment]
You'll need to `Pkg.checkout("DataFlow")` (this is useful note for the next release).

**Comment by MikeInnes** [comment]
Just merged https://github.com/JuliaLang/METADATA.jl/pull/13656 so this shouldn't be an issue any more.
