### ISSUE TITLE
This one is not in use, which one should I use instead in Flux?

### ISSUE THREAD

**Issue by hjlFrist** [FluxML/Flux.jl#1903]
my Flux is  0.12.9,but track.forword is not in use. The original expression is  Tracker.forward(x -> uθ(x), x)[2](1)[1]， What should the new expression be?

**Comment by ToucheSir** [comment]
GitHub issues is not a help forum. Please use https://discourse.julialang.org or https://julialang.org/slack/. You may be more comfortable asking in https://discourse.juliacn.com/ as well.
