### ISSUE TITLE
Missing docstring for `Flux.Data.Dataloader`

### ISSUE THREAD

**Issue by Saransh-cpp** [FluxML/Flux.jl#1909]
The `dev` documentation shows a missing docstring error here - https://fluxml.ai/Flux.jl/dev/data/dataloader/

![image](https://user-images.githubusercontent.com/74055102/159161647-08bf8b39-43b5-4b20-a319-28df5d27294e.png)

`DataLoader` was replaced by the `DatLoader` from `MLUtils` here - https://github.com/FluxML/Flux.jl/pull/1874

Should the documentation say something like - `Flux.jl` now uses `DataLoader` from `MLUtils`.  For more documentation on `DataLoader`, refer [here](https://juliaml.github.io/MLUtils.jl/dev/api/#MLUtils.DataLoader). Or should I manually add the documentation in the .`md` file?

**Comment by CarloLucibello** [comment]
I guess we want to mention that the DataLoader lives in MLUtils but also display the docstring in Flux's docs. 
Maybe we just need to add `MLUtils` [here](https://github.com/FluxML/Flux.jl/blob/2aa2a263a5a3603244369eda24c0de3cfb0d56c1/docs/make.jl#L4)
and change the docs markdown to 
```
```@docs
MLUtils.DataLoader
```

**Comment by Saransh-cpp** [comment]
Oh yes, I just noticed that the documentation also does something similar with Functors (https://fluxml.ai/Flux.jl/stable/models/functors/) and NNLib (https://fluxml.ai/Flux.jl/stable/models/nnlib/). I'll try to fix this up!
