### ISSUE TITLE
Different `Julia` versions at different places for doctests

### ISSUE THREAD

**Issue by Saransh-cpp** [FluxML/Flux.jl#1914]
While going through the doctests and workflows of `Flux.jl`, I noticed that the `Julia` version used for doctests is different in the workflows and different in the `make.jl` file.

Moreover, the doctests never run while building the documentation, as the version is pinned to `v1.5` (and the version used in workflows is `1.6`). Note, the workflows automatically pick up the latest `1.6` release, which is `1.6.5`, but this is not the case with `make.jl`. When building the documentation, the doctests run only on `Julia` `v1.5`.

The workflows run the doctests manually, hence they are anyway not needed while building the documentation. Should we turn off the doctests while building docs (the behavior that is being followed right now indirectly), or should we pin the version to `1.6.5` and turn them off from workflows (which would mean building the documentation on every PR to run doctests)?

`make.jl` - 
https://github.com/FluxML/Flux.jl/blob/81eea8495ec9669ed500f7189f4600a1b2a1b1ee/docs/make.jl#L4-L6

`ci.yml` -
https://github.com/FluxML/Flux.jl/blob/81eea8495ec9669ed500f7189f4600a1b2a1b1ee/.github/workflows/ci.yml#L54-L65

**Comment by ToucheSir** [comment]
Nice catch! Turning them off completely seems like the easiest path to me.
