### ISSUE TITLE
Inconsistent "Julia ecosystem" docs

### ISSUE THREAD

**Issue by Saransh-cpp** [FluxML/Flux.jl#1922]
The documentation available for the "Julia Ecosystem" related to `Flux.jl` is available in 2 places; here - https://fluxml.ai/ecosystem.html, and here - https://fluxml.ai/Flux.jl/stable/ecosystem/, but both of these pages are inconsistent with each other.

The doc could be changed in a few ways -
1. Update both of them to be the same and maintain both of them to be the same.
2. The first point creates redundant documentation; therefore, keep only the official website's version deployed in the same place.
3. People like me who jump straight to the docs generated by `Documenter.jl` will miss the "Ecosystem" docs (which happened in reality) in the second point. Hence, create the "Ecosystem" docs in the `Documenter.jl` generated docs and link the official website's button to this page.
4. Remove it entirely from the official website, which I honestly don't think would be a good idea.

Would love to have some discussion on this!

**Comment by darsnack** [comment]
I agree, the docs version should be updated to be organized like the website, and the menubar link for the website should just send you to the ecosystem page of the docs. The website ecosystem page should just be deleted.
