### ISSUE TITLE
Flux.flip with broadcasting warning

### ISSUE THREAD

**Issue by fpartl** [FluxML/Flux.jl#1936]
Hello, in the latest version of Flux is the broadcasting discouraged with warning, as it does not guarantee an iteration order. Shouldn't the [`Flux.flip`](https://github.com/FluxML/Flux.jl/blob/master/src/layers/recurrent.jl#L86) function be refactored according to this warning?

Maybe like this?
```julia
flip(f, xs) = reverse([f(x) for x in reverse(xs)])
```
Thank you!

**Comment by ToucheSir** [comment]
Seems like an easy enough PR, would you like to do the honours?

**Comment by fpartl** [comment]
Closing this issue with honor and my very first PR ([#1938](https://github.com/FluxML/Flux.jl/pull/1938#issue-1198474984)). :1st_place_medal:

**Comment by CarloLucibello** [comment]
let's close this when the PR gets merged

**Comment by darsnack** [comment]
> Closing this issue with honor and my very first PR (#1938). 🥇

Thanks @fpartl!
