### ISSUE TITLE
Add a workflow to clean-up `gh-pages` branch?

### ISSUE THREAD

**Issue by Saransh-cpp** [FluxML/Flux.jl#1940]
Follow up on #1937.

I found out that the documentation previews are permanently stored in the `gh-pages` branch and are never removed automatically. This would bulk up the branch in the long run, and is described in more detail here -https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#gh-pages-Branch. Should I add a workflow (most probably the one referenced in the documentation) to clear these previews, or is it not needed right now?

**Comment by DhairyaLGandhi** [comment]
Sounds worthwhile to have. Maybe it should clean up automatically when a pr
is closed or merged?

**Comment by darsnack** [comment]
Good idea, the workflow in the documentation looks like the one we want.

**Comment by darsnack** [comment]
Hmm probably easier for @ToucheSir or @CarloLucibello to just manually remove them.
