### ISSUE TITLE
Ada or ADA

### ISSUE THREAD

**Issue by KronosTheLate** [FluxML/Flux.jl#1949]
Because doing both
![image](https://user-images.githubusercontent.com/61620837/164649822-efe4c0ca-5f3e-424c-a88a-19533e5de405.png)

Seems like a bad idea...

**Comment by ToucheSir** [comment]
This is the consequence of organic growth :P. For now, a PR adding a type alias would be welcome.

**Comment by cossio** [comment]
I suggest to follow PyToch capitalizations (https://pytorch.org/docs/stable/optim.html):

Adam, AdaMax, Adadelta, AdamW, etc.

**Comment by mcabbott** [comment]
Similar issue solved at https://github.com/FluxML/Optimisers.jl/pull/78, should be easy to copy over.

**Comment by mcabbott** [comment]
Closed by #1996
