### ISSUE TITLE
Community guidelines inclusion

### ISSUE THREAD

**Issue by ysimillides** [FluxML/Flux.jl#195]
As per the community guidelines section in https://github.com/openjournals/joss-reviews/issues/602  (  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support) it may be helpful if these where explicitly mentioned in the readme / contributing.md file (or a link to the community page found here https://github.com/FluxML/Flux.jl/blob/master/docs/src/community.md).

**Comment by MikeInnes** [comment]
I've updated the readme, does that clear things up?

**Comment by ysimillides** [comment]
Yes, thats perfectly fine by me :) . I'll also confirm on the review page.
