### ISSUE TITLE
The thinking about tracking array or scalars

### ISSUE THREAD

**Issue by boathit** [FluxML/Flux.jl#196]
The `getindex` operation of a tracked array returns a tracked array while the `view` operation returns an array of tracked scalars. 

```julia
julia> W = param(rand(2,10))
julia> getindex(W, :, 1:2)
Tracked 2×2 Array{Float64,2}:
 0.244054  0.594308
 0.726764  0.765455
julia> view(W, :, 1:2)
2×2 SubArray{Flux.Tracker.TrackedReal{Float64},2,TrackedArray{…,Array{Float64,2}},Tuple{Base.Slice{Base.OneTo{Int64}},UnitRange{Int64}},false}:
 0.244054 (tracked)  0.594308 (tracked)
 0.726764 (tracked)  0.765455 (tracked)
```

I have been thinking which one is much better and now I am kind of favoring the latter. The argument here is that tracking the scalars will potentially enable us to avoid allocating unnecessary memory such as [this line](https://github.com/FluxML/Flux.jl/blob/master/src/tracker/array.jl#L66), which may become a big deal when the size of `W` is large. The only problem left is that how to make the array of tracked scalars to work normally in the subsequent computation.

**Comment by MikeInnes** [comment]
We could make this work, but it'd probably have to be `TrackedArray{SubArray}` rather than the other way around.
