### ISSUE TITLE
Opaque error caused by Float64 input to RNN

### ISSUE THREAD

**Issue by elsoroka** [FluxML/Flux.jl#1972]
The simplest example in the Flux documentation is
```
using Flux
rnn = RNN(3,5)
rnn(rand(Float32, 3))
```
However, if you write
`rnn(rand(3))`
you get the opaque error message
```
ERROR: MethodError: no method matching (::Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}})(::Matrix{Float32}, ::Vector{Float64})
Closest candidates are:
  (::Flux.RNNCell{F, A, V, var"#s371"} where var"#s371"<:AbstractMatrix{T})(::Any, ::Union{AbstractVector{T}, AbstractMatrix{T}, Flux.OneHotArray}) where {F, A, V, T} at /home/xxx/.julia/packages/Flux/BPPNj/src/layers/recurrent.jl:103
Stacktrace:
 [1] (::Flux.Recur{Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}})(x::Vector{Float64})
   @ Flux ~/.julia/packages/Flux/BPPNj/src/layers/recurrent.jl:47
 [2] top-level scope
   @ REPL[4]:1
 [3] top-level scope
   @ ~/.julia/packages/CUDA/nYggH/src/initialization.jl:52
```
This occurs on both Julia 1.6 and 1.7. I realize Float32 is used in Flux for speed, but if RNN can only support Float32 I think the error message should be clearer especially considering expressions like `rand`, `ones`, `zeros`, and `[1.0]` all default to Float64.

**Comment by ToucheSir** [comment]
So the tricky bit here is that RNNs can support Float64 (and I think most other BLAS-supported float types), but you cannot mix and match. What that means in practice is that it's not super easy to provide a clearer error for this case since the eltype is variable.

One thing we could try is registering an error hint for this that provides a clearer "you mixed up eltypes for an RNN" message. I don't know if a MethodError saves enough type info for us to interrogate there.

**Comment by elsoroka** [comment]
Out of curiosity I tried to define an RNN that could ingest Float64 input. This common example works:
```
accum(h, x) = (h .+ x, x)
rnn = Flux.Recur(accum, 0.0)
```
but `accum` takes the place of the struct `Flux.RNNCell` so you cannot call `Flux.reset!`.

To use `Flux.RNNCell` I had to write
```
rnn1 = Flux.Recur(Flux.RNNCell(1, 1, x->x, initb=zeros, init_state=zeros))
rnn1([1.0])
```
If the error message is not an easy fix, maybe the documentation can explicitly call out this behavior. The [page](https://fluxml.ai/Flux.jl/stable/models/recurrence/) uses 32 bit values but there is no reason given.

**Comment by mcabbott** [comment]
Making this more permissive may also solve the following bug -- `outputsize` works by using a special number type, and this similarly does not match:
```julia
julia> outputsize(RNN(3=>7), (3,))
ERROR: MethodError: no method matching (::Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}})(::Matrix{Float32}, ::Vector{Flux.NilNumber.Nil})
...
Stacktrace:
 [1] (::Flux.Recur{Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}})(x::Vector{Flux.NilNumber.Nil})
   @ Flux ~/.julia/packages/Flux/4k0Ls/src/layers/recurrent.jl:134
 [2] outputsize(m::Flux.Recur{Flux.RNNCell{typeof(tanh), Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}}, inputsizes::Tuple{Int64}; padbatch::Bool)
```

**Comment by ToucheSir** [comment]
FWIW https://github.com/FluxML/Flux.jl/pull/1755 is still kicking around. If it turns out the changes made to projection a while back take care of the performance issues described there, we could revisit it.
