### ISSUE TITLE
Error when using CUDA

### ISSUE THREAD

**Issue by MaAl13** [FluxML/Flux.jl#1997]
Hello, i am trying to use a CNN and it works on the CPU. As soon as i transfer everything to the GPU i get the following error

```
using CUDA, Flux
using NNlib

function build_model(input_size, output_size, hidden_sizes)
    return Chain(
            Dropout(hidden_sizes[5][1]),
            Conv((hidden_sizes[1][1][1], hidden_sizes[1][1][2]), 1=>hidden_sizes[2][1], pad=(hidden_sizes[3][1][1], hidden_sizes[3][1][2]), stride = (hidden_sizes[4][1][1], hidden_sizes[4][1][2])),
            #BatchNorm(16,relu),
            Dropout(hidden_sizes[5][2]),
            Flux.flatten,
            Dropout(hidden_sizes[5][3]),
            Dense(hidden_sizes[7], hidden_sizes[8][1], NNlib.leakyrelu),
            #BatchNorm(1000,relu),
            Dropout(hidden_sizes[5][4]),
            Dense(hidden_sizes[8][1], hidden_sizes[8][2], NNlib.leakyrelu),
            #BatchNorm(500,relu),
            Dropout(hidden_sizes[5][5]),
            Dense(hidden_sizes[8][2], hidden_sizes[8][3], NNlib.hardtanh),
            #BatchNorm(500,relu),
            Dropout(hidden_sizes[5][6]),
            Dense(hidden_sizes[8][3], hidden_sizes[8][4], NNlib.hardtanh),
            #BatchNorm(500,relu),
            Dropout(hidden_sizes[5][7]),
            Dense(hidden_sizes[8][4], output_size, NNlib.σ),
        
        )
end



hidden_sizes = Any[[[49, 9]], [1664], [[0, 0]], [[1, 1]], [0.0, 0.0, 0.2, 0.2, 0.2, 0.2, 0.2], [[1, 1]], 1664, [832, 416, 208, 104]]

model = build_model([49,9], 40, hidden_sizes)

model |> gpu

a = randn((49,9,1,1)) |> gpu
println(model(a))
```

> ERROR: LoadError: TaskFailedException
> 
>     nested task error: TaskFailedException
>     Stacktrace:
>      [1] wait
>        @ ./task.jl:334 [inlined]
>      [2] threading_run(func::Function)
>        @ Base.Threads ./threadingconstructs.jl:38
>      [3] macro expansion
>        @ ./threadingconstructs.jl:97 [inlined]
>      [4] conv_im2col!(y::SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, x::SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, w::SubArray{Float32, 5, Array{Float32, 5}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}, cdims::DenseConvDims{3, 3, 3, 6, 3}; col::CuArray{Float32, 3, CUDA.Mem.DeviceBuffer}, alpha::Float32, beta::Float32)
>        @ NNlib ~/.julia/packages/NNlib/hydo3/src/impl/conv_im2col.jl:47
>      [5] conv_im2col!
>        @ ~/.julia/packages/NNlib/hydo3/src/impl/conv_im2col.jl:28 [inlined]
>      [6] (::NNlib.var"#262#266"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, DenseConvDims{3, 3, 3, 6, 3}, SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, SubArray{Float32, 5, Array{Float32, 5}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}, SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}})()
>        @ NNlib ./threadingconstructs.jl:178
>     
>         nested task error: Scalar indexing is disallowed.
>         Invocation of getindex resulted in scalar indexing of a GPU array.
>         This is typically caused by calling an iterating implementation of a method.
>         Such implementations *do not* execute on the GPU, but very slowly on the CPU,
>         and therefore are only permitted from the REPL for prototyping purposes.
>         If you did intend to index this array, annotate the caller with @allowscalar.
>         Stacktrace:
>          [1] error(s::String)
>            @ Base ./error.jl:33
>          [2] assertscalar(op::String)
>            @ GPUArrays ~/.julia/packages/GPUArrays/Zecv7/src/host/indexing.jl:53
>          [3] getindex(::CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, ::Int64, ::Int64, ::Int64, ::Int64, ::Vararg{Int64})
>            @ GPUArrays ~/.julia/packages/GPUArrays/Zecv7/src/host/indexing.jl:86
>          [4] getindex
>            @ ./subarray.jl:276 [inlined]
>          [5] im2col!(col::CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, x::SubArray{Float32, 4, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Int64}, true}, cdims::DenseConvDims{3, 3, 3, 6, 3})
>            @ NNlib ~/.julia/packages/NNlib/hydo3/src/impl/conv_im2col.jl:227
>          [6] macro expansion
>            @ ~/.julia/packages/NNlib/hydo3/src/impl/conv_im2col.jl:51 [inlined]
>          [7] (::NNlib.var"#903#threadsfor_fun#509"{CuArray{Float32, 3, CUDA.Mem.DeviceBuffer}, Float32, Float32, SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, SubArray{Float32, 5, Array{Float32, 5}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}, DenseConvDims{3, 3, 3, 6, 3}, Int64, Int64, Int64, UnitRange{Int64}})(onethread::Bool)
>            @ NNlib ./threadingconstructs.jl:85
>          [8] (::NNlib.var"#903#threadsfor_fun#509"{CuArray{Float32, 3, CUDA.Mem.DeviceBuffer}, Float32, Float32, SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, SubArray{Float32, 5, CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, SubArray{Float32, 5, Array{Float32, 5}, Tuple{Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}, DenseConvDims{3, 3, 3, 6, 3}, Int64, Int64, Int64, UnitRange{Int64}})()
>            @ NNlib ./threadingconstructs.jl:52
> Stacktrace:
>   [1] sync_end(c::Channel{Any})
>     @ Base ./task.jl:381
>   [2] macro expansion
>     @ ./task.jl:400 [inlined]
>   [3] conv!(out::CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, in1::CuArray{Float32, 5, CUDA.Mem.DeviceBuffer}, in2::Array{Float32, 5}, cdims::DenseConvDims{3, 3, 3, 6, 3}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
>     @ NNlib ~/.julia/packages/NNlib/hydo3/src/conv.jl:195
>   [4] conv!
>     @ ~/.julia/packages/NNlib/hydo3/src/conv.jl:186 [inlined]
>   [5] conv!(y::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, w::Array{Float32, 4}, cdims::DenseConvDims{2, 2, 2, 4, 2}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
>     @ NNlib ~/.julia/packages/NNlib/hydo3/src/conv.jl:145
>   [6] conv!
>     @ ~/.julia/packages/NNlib/hydo3/src/conv.jl:145 [inlined]
>   [7] conv(x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, w::Array{Float32, 4}, cdims::DenseConvDims{2, 2, 2, 4, 2}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
>     @ NNlib ~/.julia/packages/NNlib/hydo3/src/conv.jl:88
>   [8] conv
>     @ ~/.julia/packages/NNlib/hydo3/src/conv.jl:86 [inlined]
>   [9] (::Conv{2, 2, typeof(identity), Array{Float32, 4}, Vector{Float32}})(x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer})
>     @ Flux ~/.julia/packages/Flux/js6mP/src/layers/conv.jl:176
>  [10] macro expansion
>     @ ~/.julia/packages/Flux/js6mP/src/layers/basic.jl:53 [inlined]
>  [11] applychain(layers::Tuple{Dropout{Float64, Colon, Random.TaskLocalRNG}, Conv{2, 2, typeof(identity), Array{Float32, 4}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, typeof(Flux.flatten), Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(leakyrelu), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(leakyrelu), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(hardtanh), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(hardtanh), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(σ), Matrix{Float32}, Vector{Float32}}}, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer})
>     @ Flux ~/.julia/packages/Flux/js6mP/src/layers/basic.jl:53
>  [12] (::Chain{Tuple{Dropout{Float64, Colon, Random.TaskLocalRNG}, Conv{2, 2, typeof(identity), Array{Float32, 4}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, typeof(Flux.flatten), Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(leakyrelu), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(leakyrelu), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(hardtanh), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(hardtanh), Matrix{Float32}, Vector{Float32}}, Dropout{Float64, Colon, Random.TaskLocalRNG}, Dense{typeof(σ), Matrix{Float32}, Vector{Float32}}}})(x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer})
>     @ Flux ~/.julia/packages/Flux/js6mP/src/layers/basic.jl:51
>  [13] top-level scope
>     @ ~/Job_Array_Timer_NN/Test_CUDA_new.jl:38
> in expression starting at /cluster/home/malmansto/Job_Array_Timer_NN/Test_CUDA_new.jl:38

**Comment by ToucheSir** [comment]
`gpu(model)` does not transfer the underlying weights in-place. It creates a new model with all weights as CuArrays. If the return value isn't being assigned to anything, then that new model is immediately being thrown away. Flux is no different from other frameworks in this regard.

**Comment by MaAl13** [comment]
Thank you for the response. However, replacing the last line with b = model(a) produces unfortunately the same error

**Comment by ToucheSir** [comment]
Did you run `model = gpu(model)` before that line? Just adding `b = model(a)` is semantically identical to the top comment example, the important part is that the _model_ is moved. This is unlike e.g. PyTorch where `model.to(...)` moves the parameters in-place.
