### ISSUE TITLE
type cannot been referred with structured model function

### ISSUE THREAD

**Issue by deahhh** [FluxML/Flux.jl#2000]
```Julia
using Flux
struct DConv
      conv::Conv
end
function (m::DConv)(x)
      m.conv(x)
end

Flux.@functor DConv

@code_warntype m(rand(Float32, 10,10,5,1))
```
output as:

MethodInstance for (::DConv)(::Array{Float32, 4})
  from (m::DConv)(x) in Main at REPL[59]:1
Arguments
  m::DConv
  x::Array{Float32, 4}
Body_::Any_
1 ─ %1 = Base.getproperty(m, :conv)_::Conv_
│   %2 = (%1)(x)_::Any_
└──      return %2

You can find that, the sum of execution time of each clause in function, is much less than execute the function directly, with BenchmarkTools.
It's so much that, I got 222ms:9ms in practice. Not the simple example.

**Comment by deahhh** [comment]
@ToucheSir , thanks a lot!

**Comment by deahhh** [comment]
@ToucheSir 
I found that `cat` is not type stable. And there is no other to use as `cat`.

**Comment by deahhh** [comment]
@ToucheSir 
Great!

**Comment by deahhh** [comment]
@ToucheSir 
Would you help me on another question:
I got 222ms execution time with `@btime` before the calling, while 9ms in total before almost every line inner! I thougt that's type-instable, but I konw its not now, as I make it type-stable now.

Any suggestion?

**Comment by ToucheSir** [comment]
`@btime` runs each expression multiple times, so I do not think it's doing what you think it's doing. This kind of question is better suited for a help forum like Discourse, Slack or Zulip, so I'd recommend moving it there. We reserve the issue tracker for bugs and feature requests.

**Comment by deahhh** [comment]
[dfd f](https://discourse.julialang.org/t/there-is-a-huge-difference-in-time-consumption-between-calling-a-function-sentence-by-sentence-and-calling-the-entire-function-at-once/82946)

@ToucheSir 
Could you help me?
