### ISSUE TITLE
[Broken Documentation] Dense(1 => 1)

### ISSUE THREAD

**Issue by trigaten** [FluxML/Flux.jl#2001]
On this page: https://fluxml.ai/Flux.jl/stable/models/overview/#Build-a-Model-to-Make-Predictions
`model = Dense(1 => 1)`
yields
`MethodError: no method matching Dense(::Pair{Int64, Int64})`
It seems that `Dense(1, 1)` should be used instead.

**Comment by ToucheSir** [comment]
Your Flux version is probably out of date. Make sure you have at least v0.13 and that no other packages in your environment are holding it back.
