### ISSUE TITLE
Deprecate `track_stats=true` for `GroupNorm` and `InstanceNorm`

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/Flux.jl#2006]
We discussed this on Slack, and it appears other libraries do not track running stats for either. Nor do any papers appear to make use of a running average. Thus the complexity feels very much not worth it, and doing it by default creates unnecessary inconsistencies with the rest of the ecosystem.

The rough deprecation plan for this is as follows:
1. Emit a warning when users pass `track_stats=true`, with a pointer to use `track_stats=false` since the former will go away in the next breaking Flux release. This is the "good first issue" part.
2. For that breaking release, remove the tracking entirely and leave `track_stats` as a vestigial kwarg. Alternatively, we could remove it completely.

**Comment by akahard2dj** [comment]
Hello! Julia Libraty contirbution is first time in my life!
Should I scarach this one?

**Comment by ToucheSir** [comment]
If this is your first PR to _any_ Julia library, it may be a little tricky. Feel free to take a shot though :)

**Comment by ToucheSir** [comment]
This was fixed in #2042, but it was overzealous in the specification and erroneously included `InstanceNorm`. #2149 fixes that.
