### ISSUE TITLE
v0.12.10 => v0.13.4 breaks `Dropout` on CUDA

### ISSUE THREAD

**Issue by marmarelis** [FluxML/Flux.jl#2018]
Hi all, it seems that an update to the `Dropout` layer at some point following Flux `v0.12.10` caused an incompatibility with CUDA on Julia 1.6.0, `CUDA.versioninfo()`:
```
CUDA toolkit 11.7, artifact installation
NVIDIA driver 470.57.2, for CUDA 11.4
CUDA driver 11.4
```

A minimal example
```julia
model = Chain(Dense(4,4), Dropout(0.1)) |> gpu
Flux.train!(Flux.params(model), [randn(4)|>gpu], ADAM(1e-1)) do x; model(x) |> sum; end
```
crashes with
```
julia: /buildworker/worker/package_linux64/build/src/jitlayers.cpp:958: void jl_merge_module(llvm::Module*, std::unique_ptr<llvm::Module>): Assertion `dG->isDeclaration() || (dG->getInitializer() == sG->getInitializer() &&
 dG->isConstant() && sG->isConstant())' failed.
```

The trace also includes the following line:
```
#_dropout_mask#317 at [...]/layers/normalise.jl:45
```

**Comment by ToucheSir** [comment]
That line just calls rand!, so this ought to be reported to CUDA.jl. If I had to guess, toolkit 11.7 is too new and has some outstanding bugs when used with CUDA.jl.
