### ISSUE TITLE
`using Flux` is broken on the Julia nightly

### ISSUE THREAD

**Issue by bvdmitri** [FluxML/Flux.jl#2097]
### Package Version

[587475ba] Flux v0.13.7

### Julia Version

Julia Version 1.9.0-DEV.1696

### OS / Environment

GitHub Actions 

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 2 × Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-[14](https://github.com/biaslab/ReactiveMP.jl/actions/runs/3362833505/jobs/5575115623#step:3:15).0.6 (ORCJIT, icelake-server)
  Threads: 1 on 2 virtual cores

### Describe the bug

`using Flux` does not work on the latest Julia nightly.

### Steps to Reproduce

Call `using Flux` on the latest Julia nightly or check the https://github.com/biaslab/ReactiveMP.jl/actions/runs/3362833505/jobs/5575115623

### Expected Results

`using Flux` should not throw any error.

### Observed Results

```
ERROR: LoadError: type DataType has no field size
Stacktrace:
  [1] getproperty(x::Type, f::Symbol)
    @ Base ./Base.jl:32
  [2] (::MLStyle.AbstractPatterns.RedyFlavoured.var"#ap_literal#21")(#unused#::MLStyle.AbstractPatterns.RedyFlavoured.CompileEnv, target::MLStyle.AbstractPatterns.Target)
    @ MLStyle.AbstractPatterns.RedyFlavoured ~/.julia/packages/MLStyle/8rUyA/src/AbstractPatterns/impl/RedyFlavoured.jl:224
...

ERROR: LoadError: Failed to precompile MLStyle [d8e11817-5142-5d16-987a-aa16d5891078] to /home/runner/.julia/compiled/v1.9/MLStyle/jl_xEydSQ.
Stacktrace:

ERROR: LoadError: Failed to precompile JuliaVariables [b14d175d-62b4-44ba-8fb7-3064adc8c3ec] to /home/runner/.julia/compiled/v1.9/JuliaVariables/jl_1y2vAF.
Stacktrace:

ERROR: LoadError: Failed to precompile FLoops [cc61a311-1640-44b5-9fba-1b764f453329] to /home/runner/.julia/compiled/v1.9/FLoops/jl_D5ngkw.
Stacktrace:
...

in expression starting at /home/runner/.julia/packages/Flux/nJ0IB/src/Flux.jl:1
in expression starting at stdin:1
```

**Comment by ToucheSir** [comment]
Try `] up`dating your environment. This error comes from an upstream package that was fixed recently: https://github.com/thautwarm/MLStyle.jl/issues/147

**Comment by bvdmitri** [comment]
I'm not sure `julia` uses any `Manifest.toml` in case of `] test`. In any case, we do not have `Manifest.toml` in our repository. Also as you can see from the [link](https://github.com/biaslab/ReactiveMP.jl/actions/runs/3362833505/jobs/5575115623) I've attached in the issue the GH actions does use the `[d8e11817] MLStyle v0.4.15` version.

**Comment by bvdmitri** [comment]
The CI does indeed uses the previous version `[d8e11817] MLStyle v0.4.14`, so we can wait till the update is propagated. After that if everything is working I can close the issue.

**Comment by mcabbott** [comment]
Seems to work now
