### ISSUE TITLE
Method Error when using Flux.withgradient

### ISSUE THREAD

**Issue by wpeguero** [FluxML/Flux.jl#2148]
Hello everyone,

I am currently encountering an issue where I have tried to train a simple GRU model and it seems that the data which I am feeding in with the DataLoader is not within the right format. I am unsure what format the data may have to be in order to train the model.

```
Using Flux
Using DataFrames
using DelimitedFiles
"""
Load CSV data into a DataFrame.
"""
function read_csv(filename::String, delimiter::Char=',')
    data, headers = readdlm(filename, delimiter, header=true)
    df = DataFrame(data, vec(headers))
    return df
end

df = read_csv("../data/heating oil prices.csv")

names(df)
# for the weekly price of dollars per gallon columns
df[!, :"weekly__dollars_per_gallon"] = convert.(Float32, df[!, :"weekly__dollars_per_gallon"])

# Convert string columns to the date types
df[!, :"\ufeffdate"] = Date.(df[!, :"\ufeffdate"], Dates.DateFormat("u d, yyyy"))
first(df, 10)
df[!,:"years"] = year.(df[!,:"\ufeffdate"])
df[!,:"months"] = month.(df[!,:"\ufeffdate"])
df[!,:"weeks"] = week.(df[!,:"\ufeffdate"])
first(df, 10)
X_train = Array(first(df[!, [:years,:months,:weeks]], Int(nrow(df)*0.75)))'
X_test = last(df[!, [:years,:months,:weeks]], Int(nrow(df)*0.25))
y_train = Array(first(df[!, :weekly__dollars_per_gallon], Int(nrow(df)*0.75)))'
y_test = last(df[!, :weekly__dollars_per_gallon], Int(nrow(df)*0.25))
train_loader = DataLoader((data=X_train, label=y_train), batchsize=64, shuffle=true);
test_loader = DataLoader((data=X_test, label=y_test), batchsize=64, shuffle=true);
first(X_train, 10)
model = GRU(3 => 1)
optim = Flux.setup(Adam(0.01), model)
losses = []
for epoch in 1:10
    for (x,y) in train_loader
        loss, grads = Flux.withgradient(model) do m
            # Evaluate model and loss inside gradient context:
            y_hat = m(x)
            crossentropy(y_hat, y)
        end
        update!(optim, model, grads[1])
[heating oil prices.csv](https://github.com/FluxML/Flux.jl/files/10329201/heating.oil.prices.csv)

        push!(losses, loss)
    end
end
```

The nature of the data is the following:
![image](https://user-images.githubusercontent.com/59205371/210180088-bed7544a-b6e6-4c8a-9a60-c7aa0b59879a.png)
[heating oil prices.csv](https://github.com/FluxML/Flux.jl/files/10329203/heating.oil.prices.csv)

Below is the error that I am currently encountering:
MethodError: no method matching (::Flux.GRUCell{Matrix{Float32}, Matrix{Float32}, Vector{Float32}, Matrix{Float32}})(::Matrix{Float32}, ::Matrix{Int64})
Closest candidates are:
  (::Flux.GRUCell{I, H, V, <:AbstractMatrix{T}})(::Any, ::Union{AbstractVector{T}, AbstractMatrix{T}, OneHotArrays.OneHotArray}) where {I, H, V, T} at C:\Users\wpegu\.julia\packages\Flux\kq9Et\src\layers\recurrent.jl:379

Stacktrace:
  [1] macro expansion
    @ C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface2.jl:0 [inlined]
  [2] _pullback(::Zygote.Context{false}, ::Flux.GRUCell{Matrix{Float32}, Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, ::Matrix{Float32}, ::Matrix{Int64})
    @ Zygote C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface2.jl:9
  [3] _pullback
    @ C:\Users\wpegu\.julia\packages\Flux\kq9Et\src\layers\recurrent.jl:134 [inlined]
  [4] _pullback(ctx::Zygote.Context{false}, f::Flux.Recur{Flux.GRUCell{Matrix{Float32}, Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}}, args::Matrix{Int64})
    @ Zygote C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface2.jl:0
  [5] _pullback
    @ b:\Documents\Github\grove-cost-predictors\case studies\heating_oil_consumption.ipynb:8 [inlined]
  [6] _pullback(ctx::Zygote.Context{false}, f::var"#19#20"{LinearAlgebra.Adjoint{Float32, Vector{Float32}}, Matrix{Int64}}, args::Flux.Recur{Flux.GRUCell{Matrix{Float32}, Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}})
    @ Zygote C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface2.jl:0
  [7] pullback(f::Function, cx::Zygote.Context{false}, args::Flux.Recur{Flux.GRUCell{Matrix{Float32}, Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}})
    @ Zygote C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface.jl:44
  [8] pullback
    @ C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface.jl:42 [inlined]
  [9] withgradient(f::Function, args::Flux.Recur{Flux.GRUCell{Matrix{Float32}, Matrix{Float32}, Vector{Float32}, Matrix{Float32}}, Matrix{Float32}})
    @ Zygote C:\Users\wpegu\.julia\packages\Zygote\SmJK6\src\compiler\interface.jl:132
 [10] top-level scope
    @ b:\Documents\Github\grove-cost-predictors\case studies\heating_oil_consumption.ipynb:6

**Comment by mcabbott** [comment]
I think this is https://github.com/FluxML/Flux.jl/issues/1972 -- at present the RNN layers don't accept input of any eltype except the same as their weights. 

The work-around is to insert `X_train = Float32.(X_train)` or something equivalent, for all the inputs. It may work just to do something like `Array(first(df[!, [:years,:months,:weeks]], nrow(df)*0.75f0))'` i.e. remove the `Int` and use Float32 literal, not Float64 `0.75`.

**Comment by wpeguero** [comment]
Hello,

thanks for the quick reply. I just tried this and I was able to train the model.
