### ISSUE TITLE
MNIST in browser

### ISSUE THREAD

**Issue by jw3126** [FluxML/Flux.jl#215]
The [MNIST in browser idea](http://fluxml.ai/experiments/mnist/) is very cool! However it seems that something is wrong. If I play with it, it gets only about 30% of the numbers correct (I did not try to confuse it deliberately).

**Comment by ViralBShah** [comment]
Needs a more complex model, which needs some more work...

**Comment by jekbradbury** [comment]
The problem is that FluxJS doesn't yet support convolutiomal layers, and fully connected nets (while solving MNIST itself fairly well) don't generalize well to freeform user inputs because they lack translational invariance.

**Comment by jw3126** [comment]
I see thank! There is already an issue here https://github.com/FluxML/FluxJS.jl/issues/4

**Comment by MikeInnes** [comment]
It's significantly improved now.

**Comment by jw3126** [comment]
Its better I guess, but still not really good. Its maybe 60% correct for me. I think this issue should stay open.

**Comment by jw3126** [comment]
Is the issue, that the MNIST images are not really representative for these browser images? Or is the issue that we can't complie a decent net to javascript? Or something else?

**Comment by MikeInnes** [comment]
At this point we have a convnet but it's probably still overfitting on well centred/sized images. If you want to take a crack at building a model with a better dataset (e.g. augmented with translated, rotated and scaled images), we'd be happy to port that instead.
