### ISSUE TITLE
0.2 tutorial at the top of google for "flux mnist"

### ISSUE THREAD

**Issue by anandijain** [FluxML/Flux.jl#2163]
if i google "flux mnist", i get a link to https://fluxml.ai/Flux.jl/v0.2/examples/logreg.html which is quite old

**Comment by pebeto** [comment]
Hello! Maybe we could add the [Model Zoo](https://github.com/FluxML/model-zoo/tree/master/) into that section. There you can find some examples (the specific one you need is on the vision directory).

**Comment by mcabbott** [comment]
From slack:

> Set canonical url to makedocs 
> 
> And use https://github.com/JuliaDocs/DocumenterTools.jl/blob/master/src/OutdatedWarning.jl#L135-L146 for versions built with very old documenter versions

**Comment by Bhavay-2001** [comment]
Hi @mcabbott, is anyone working on this issue? I am a beginner. Can I start working on this?
