### ISSUE TITLE
Binding Flux.setup does not exist

### ISSUE THREAD

**Issue by Vilin97** [FluxML/Flux.jl#2169]
The [docs](https://fluxml.ai/Flux.jl/stable/training/training/#Optimisation-Rules) use `Flux.setup` but it does not exist.

```
julia> using Flux

help?> Flux.setup
  No documentation found.

  Binding Flux.setup does not exist.
```

**Comment by ToucheSir** [comment]
Most likely something else in your environment is holding Flux back. If it's not 0.13.11, Try adding the latest version and see if it errors. If so, you can follow the usual guidance for troubleshooting conflicts with Pkg.
