### ISSUE TITLE
Update GH Actions across all repos

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/Flux.jl#2170]
![image](https://user-images.githubusercontent.com/4062143/215923038-da489a10-9988-41da-aa8e-6f25156d232d.png)
etc. Wanted to track this for anyone who has some spare cycles.

**Comment by Arman49** [comment]
Hello Sir. I'm new to  opensource. could you suggest or reffer any issues or documentation.

**Comment by ToucheSir** [comment]
Just to set expectations up front, I would only recommend taking this on if you have existing experience working with GitHub Actions and some level of exposure to Julia. The changes shouldn't be difficult, but they do require working knowledge of both.

**Comment by skyleaworlder** [comment]
Hi! I can take this. I think I'm familiar with Actions more. Related PR will come soon.

**Comment by ToucheSir** [comment]
Just merged your PRs, thanks!

**Comment by skyleaworlder** [comment]
I've updated some. But I have to say it's too many repos. 😭

"all repos" is really a huge and boring work. I think there are some repos aren't updated very often, so I plan to update them after they are updated.

**Comment by ToucheSir** [comment]
No worries. The idea was that we'd slowly tackle these over time and whoever had some spare cycles could pick off one or two, but having the major repos covered in so little time is wonderful.

**Comment by vnegi10** [comment]
Looks like an easy but repetitive change. I will help out with some of the remaining repos.

**Comment by ToucheSir** [comment]
Thanks for this! If you or anyone else is interested, we should probably also add https://github.com/FluxML/Flux.jl/pull/2212 to the other relevant FluxML repos so that this process can be more automatic in the future.

**Comment by Jay-sanjay** [comment]
@ToucheSir  Sir can this issue be closed now
