### ISSUE TITLE
Docs Revamp 

### ISSUE THREAD

**Issue by shivance** [FluxML/Flux.jl#2174]
### Motivation and description

#2105 

Having contributed to Metalhead and gathering some experience in Flux, I realise that flux needs a lot of documentation and more How Tos. While #2105 described the entire roadmap... What is the immediate item of action where I can start to contribute towards documentation improvement?

I believe that improving docs will make me understand flux more deeply

**Comment by ToucheSir** [comment]
We don't have such a fine-grained priority list, but have a look at all the [issues](https://github.com/search?q=org%3AFluxML%20is%3Aopen%20is%3Aissue%20label%3Adocumentation%20&type=issues) with the documentation label.

**Comment by mcabbott** [comment]
One thing you can do is to flag things you find unclear / confusing on the first pass. These can be hard to see for those who've been involved too long.

In the manual, of the section now called "Guide" I think the last three sections (GPU, Saving, Performance) are over-due for a re-write. But they intersect with functional changes (like #1907, #2156) so it may be too soon to try.

It would be nice to have useful tutorials. Besides being out of date, much of what's in http://fluxml.ai/tutorials/  isn't very helpful.

**Comment by shivance** [comment]
@mcabbott @ToucheSir I wrote two Julia blogs [here](https://medium.com/@shivance), worth putting in tutorial?

several medium blogs can be adopted as well [this](https://sebastien-dejean.medium.com/juliaml-flux-a-very-beginner-example-part-3-18a3a6842e06?source=search_post---------16----------------------------) and [this](https://towardsdatascience.com/a-swift-introduction-to-flux-for-julia-with-cuda-9d87c535312c)

**Comment by shivance** [comment]
Is there a specific topic Flux would like to have a tutorial on, @ToucheSir @mcabbott ?

**Comment by mcabbott** [comment]
I think the most urgent place which needs attention is really the model zoo. In the past we had many examples which look like this:

https://github.com/FluxML/model-zoo/blob/master/vision/conv_mnist/conv_mnist.jl

and they got expanded into pages like this, by adding words:

http://fluxml.ai/Flux.jl/stable/tutorials/2021-02-07-convnet/

We shouldn't do that, it's not helpful. And it goes out of date easily.

Instead, I think that whole example should be under 50 lines. It should be as close to self-explanatory as possible. It should be made easy to step through at the REPL to try out the bits you don't follow. No `@kwdef` structs, no TensorBoardLogger, 1/4 as many functions.
