### ISSUE TITLE
Conv not defined

### ISSUE THREAD

**Issue by datnamer** [FluxML/Flux.jl#218]
I've check out master and conv doesn't seem to be defined, causing an error saying the same,   in the MetalHead example.  

Any ideas? 

Thanks 
Edit: Now `@fix` not defined when trying to precompile Flux on atom.

Edit 2: This is on windows 7, Juliapro 0.62

**Comment by datnamer** [comment]
It's working on a separate fresh Julia (not JuliaPro) installation on the same machine.

**Comment by MikeInnes** [comment]
Sounds like nnlib is out of date. On juliapro it's a good idea to leave the packages alone and see the older version of the docs.
