### ISSUE TITLE
Un-intended behaviour? Should Flux be able to reduce StaticArrays?

### ISSUE THREAD

**Issue by AhmedSalih3d** [FluxML/Flux.jl#2180]
Hello

I am trying:

using CUDA
S      = rand(SVector{3,Float32},5)
DST = zeros(SVector{3,Float32},5)
I       = [3,1,2,5,4]

# Works great on CPU

@CUDA.time NNlib.scatter!(+, DST,S,I)
0.000004 seconds
5-element Vector{SVector{3, Float32}}:
[1.3667885, 1.081403, 1.1134366]
[1.6543723, 0.50424564, 1.1448298]
[0.8695842, 1.8623418, 1.398939]
[1.0094697, 0.0052466393, 0.09184897]
[1.9389011, 0.3291297, 1.2308507]

# Bugs out on GPU

 @CUDA.time NNlib.scatter!(+, CuArray(DST),CuArray(S),CuArray(I))
ERROR: InvalidIRError: compiling kernel #scatter_kernel!(typeof(+), CuDeviceVector{SVector{3, Float32}, 1}, CuDeviceVector{SVector{3, Float32}, 1}, CuDeviceVector{Int64, 1}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to atomic_cas!)

Anyone knows why?

This is an example, I need it to work on GPU for a more complex case

Kind regards

**Comment by mcabbott** [comment]
This is https://github.com/FluxML/NNlibCUDA.jl/issues/64 right?

You could try pinging those who wrote the `scatter` code, e.g. going by https://github.com/FluxML/NNlibCUDA.jl/pulls?q=is%3Apr+scatter

**Comment by AhmedSalih3d** [comment]
> This is [FluxML/NNlibCUDA.jl#64](https://github.com/FluxML/NNlibCUDA.jl/issues/64) right?
> 
> You could try pinging those who wrote the `scatter` code, e.g. going by https://github.com/FluxML/NNlibCUDA.jl/pulls?q=is%3Apr+scatter

I am not sure, I just went "using Flux" and then it exposes NNlib to me. I suppose the GPU version might be using NNlibCUDA in the background, but I have not tested that

**Comment by mcabbott** [comment]
If the issue is different, can you explain how? Do you think it's an independent bug or just a slightly different example? 

(The last issue got moved to NNlibCUDA, because that's where the GPU implementation of `scatter` lives, even though that package isn't really user-facing.)

**Comment by AhmedSalih3d** [comment]
To be honest  I had forgotten I had made the first issue.

I made an updated comment there, thank you

**Comment by ToucheSir** [comment]
Let's not duplicate this discussion between 2 GitHub issues and Discourse.
