### ISSUE TITLE
 loadmodel! example in the docs doesn't work

### ISSUE THREAD

**Issue by jonathanBieler** [FluxML/Flux.jl#2191]
The docs (http://fluxml.ai/Flux.jl/stable/saving/) say you can load a model with : 

`model = loadmodel!(model, @load("mymodel.bson"))` 

but `@load("mymodel.bson")` returns nothing.

I think it should be something like `loadmodel!(model, load("mymodel.bson")[:model])`. Also it looks like this case is not tested (can't find it in test/utils.jl).

Flux v0.13.11 & BSON v0.3.6

**Comment by ToucheSir** [comment]
Good catch, mind filing a PR?

**Comment by jonathanBieler** [comment]
Will do.
