### ISSUE TITLE
Flattern removal

### ISSUE THREAD

**Issue by potaslab** [FluxML/Flux.jl#2195]
Hi there, the removal of Flatten in version 0.13.13 means that models trained and saved from legacy versions of Flux are not loaded properly (the flatten layer is completely gone). Is there a way to ensure the flatten layer is still imported? The models loaded correctly under version 0.12.8. The models were imported from JLD2 files, and the entire model, except the flatten layer was missing, without any way to recover it.

**Comment by CarloLucibello** [comment]
ou will have to load the model with an older Flux version, replace `Flux.flatten` with `MLUtils.flatten` and save again the model. Something like this:
```
pkg> add Flux@0.13.12
```
```julia
using Flux, MLUtils, JLD2

struct MLP
    net
end

model = MLP(Chain(
            Flux.flatten,
            Dense(10 => 10)
            ))

JLD2.jldsave("model.jld2"; model)

model2 = JLD2.load("model.jld2")["model"]

model3 = MLP(Chain(MLUtils.flatten, model2.net.layers[2:end]...))

# This is compatible also with Flux v0.13.13
JLD2.jldsave("model3.jld2"; model=model3)
```

I'm not sure if we can do something better than this. Maybe using the custom serialization API https://juliaio.github.io/JLD2.jl/dev/customserialization/
it is possible to convert the missing symbol `Flux.flatten` into `MLUtils.flatten` but I don't know how.

**Comment by mcabbott** [comment]
Is it possible that Flux should have `const flatten = MLUtils.flatten`, until 0.14?

**Comment by CarloLucibello** [comment]
right, that should solve the issue!

**Comment by potaslab** [comment]
Thanks for your hard work guys, I appreciated it!
