### ISSUE TITLE
FLux and Lux upon using: ERROR: LoadError: ArgumentError: invalid version string: local

### ISSUE THREAD

**Issue by mscott99** [FluxML/Flux.jl#2202]
I am trying to run Flux on a server (digital research alliance of canada). It is on notebook through Jupyter Hub. I use the `CUDA.set_runtime_version!("local")` to access the local cuda runtime, and restart Julia. Then Cuda works (can add number to CuArray). Then running `using Flux` fails with error ``ERROR: LoadError: ArgumentError: invalid version string: local``. `using Lux` fails with the same error.

Package versions
Julia 1.8.1
IJulia kernel 1.8
CUDA.jl 4.0.1
CUDA runtime 11.7, local installation
CUDA driver 11.8
Flux v0.13.13 (or Lux v0.4.40)

Stacktrace:
![Screenshot 2023-03-02 at 12 11 29 PM](https://user-images.githubusercontent.com/15056843/222939191-4da1f800-ed64-44c8-b6f4-c556c28a4518.png)

I have yet to hear back from the system admin for this, and also these versions are the most recent ones I have access to on the server. Also let me know if this issue belongs somewhere else (i.e. it is not an issue but something I am doing wrong). Thanks!

**Comment by ToucheSir** [comment]
This isn't an issue with Flux but with the `cuDNN` package, which is a [subpackage](https://github.com/JuliaGPU/CUDA.jl/tree/master/lib/cudnn) of CUDA.jl. You should be able to replicate it by `] add`ing `cuDNN` to your environment and importing it. For that reason, it's also not an issue we or Lux can handle. I would recommend reporting this in the CUDA.jl issue tracker instead.

P.S. I do not believe `CUDA.set_runtime_version!("local")` is necessary to access CUDA functionality if you're simply running in a JupyterLab/Hub notebook server. If you remove that line and reset that option, that might be enough to make things work.

**Comment by mscott99** [comment]
Okay, thanks!
