### ISSUE TITLE
Quick start tutorial doesn't work; Flux.setup not defined

### ISSUE THREAD

**Issue by jonathanfischer97** [FluxML/Flux.jl#2217]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/69228453/226792648-2784ec03-6d71-4759-8f1d-57c919703425.png">

New to Flux and tried to run the quick start demo from the documentation to try it out, but found that the function call "setup()" for the optimizer in that example isn't defined. No modifications on my part, just copy and pasted into a local file

Thought you should know just for sake of making the documentation friendly and frictionless for new users

**Comment by ToucheSir** [comment]
Most likely your Flux version is out of date. I would check the installed packages in your current environment.
