### ISSUE TITLE
need help from an expert

### ISSUE THREAD

**Issue by alerem18** [FluxML/Flux.jl#2233]
if anyone can help me with this, i'd appreciate it so much, i've not solved this problem for 3 weeks of working
i've implemented PPO algorithm in flux.jl, it'll work well on most of environments but not on LunarLander-v2 while implementation of PPO with Monte Carlo estimation instead of Generalized Advantage Estimation solves the Env easily
here is my code
https://discourse.julialang.org/t/help-wanted-with-ppo-implementation-in-flux-jl/97734

i'm really broke right now and i don't know what i have done wrong, please help me if you have time

here are results for LunarLander-v2 which are not good
Episode : 20 | avg_reward : -226.31964818118453
Episode : 40 | avg_reward : -194.98543850057015
Episode : 60 | avg_reward : -233.81122823154473
Episode : 80 | avg_reward : -198.02512226575564
Episode : 100 | avg_reward : -222.09373224897476
Episode : 120 | avg_reward : -190.33036129053795
Episode : 140 | avg_reward : -121.95674345596574
Episode : 160 | avg_reward : -121.37326082678483
Episode : 180 | avg_reward : -44.696021505910366
Episode : 200 | avg_reward : -37.29211731010206
Episode : 220 | avg_reward : -85.64308332015761
Episode : 240 | avg_reward : -85.26293222180868
Episode : 260 | avg_reward : -74.38208975999467
Episode : 280 | avg_reward : -105.52916660305058
Episode : 300 | avg_reward : -65.01123080010515
Episode : 320 | avg_reward : -53.49171057697971
Episode : 340 | avg_reward : -60.326857354924755
Episode : 360 | avg_reward : -65.49151792535757
Episode : 380 | avg_reward : -73.18681003020264
Episode : 400 | avg_reward : -95.59069884372849
Episode : 420 | avg_reward : -90.49312717197981
Episode : 440 | avg_reward : -75.14535074998588
Episode : 460 | avg_reward : -98.34592364334415
Episode : 480 | avg_reward : -83.02940008860521
Episode : 500 | avg_reward : -75.40652646924171
Episode : 520 | avg_reward : -93.61820440538798
Episode : 540 | avg_reward : -126.43225082330487
Episode : 560 | avg_reward : -139.35426210569395
Episode : 580 | avg_reward : -129.56041322020042
Episode : 600 | avg_reward : -118.66954201794015
Episode : 620 | avg_reward : -117.46227410168383
Episode : 640 | avg_reward : -111.52444196983916
Episode : 660 | avg_reward : -117.17595038098884
Episode : 680 | avg_reward : -109.69933526561053
Episode : 700 | avg_reward : -115.3682967014862
Episode : 720 | avg_reward : -103.29355527321863
Episode : 740 | avg_reward : -108.22939017245164
Episode : 760 | avg_reward : -127.97245851174607
Episode : 780 | avg_reward : -104.21920278419262
Episode : 800 | avg_reward : -93.63517854608475
Episode : 820 | avg_reward : -113.91158055873632
Episode : 840 | avg_reward : -104.61870088213591
Episode : 860 | avg_reward : -112.4860687070784
Episode : 880 | avg_reward : -94.52115950785347
Episode : 900 | avg_reward : -152.92614491307123
Episode : 920 | avg_reward : -143.57724561826103
Episode : 940 | avg_reward : -122.248353301206
Episode : 960 | avg_reward : -143.70092847027348
Episode : 980 | avg_reward : -123.84620771871035
Episode : 1000 | avg_reward : -139.0209933090586
Episode : 1020 | avg_reward : -118.11087610012831
Episode : 1040 | avg_reward : -113.78118779063948
Episode : 1060 | avg_reward : -133.7282604617721
Episode : 1080 | avg_reward : -123.20248215991694
Episode : 1100 | avg_reward : -131.29204187013198
Episode : 1120 | avg_reward : -120.53608531477849
Episode : 1140 | avg_reward : -129.46887214957354

**Comment by darsnack** [comment]
I am closing this issue, since Discourse is a better forum for problems like this. Those of us that maintain Flux and can help should respond directly on Discourse.
