### ISSUE TITLE
Code block in documentation not rendering properly

### ISSUE THREAD

**Issue by ayushpatnaikgit** [FluxML/Flux.jl#2248]
A code block in [RNN's documentation](http://fluxml.ai/Flux.jl/stable/models/layers/#Flux.RNN) isn't rendering properly. Attaching screenshot. 

![image](https://user-images.githubusercontent.com/20169423/235346466-24599ad0-f374-4c51-a7ca-a0b484afb793.png)

I tried to fix it, but I am unable to compile the docs. When I try `julia docs/make.jl` (before making any changes), I find that a bunch of doctests are failing. Do I need to alter the command to compile the documentation?

**Comment by darsnack** [comment]
Did you activate the `docs` folder as your Julia project when running that command? You can see the CI workflow under `.github` for a reference on running docs.

**Comment by mcabbott** [comment]
It's sometimes a bit of a pain to run locally. Unfortunately, if you make a PR (on a fork) CI won't check this... but since I have privileges to make them on the root, it does... so I made #2249 quickly.

**Comment by ayushpatnaikgit** [comment]
Thanks, @darsnack. 
I tried it, but I am still not able to run the tests. This time, there is no output, Julia seems stuck on doctests. 

I didn't find anything on this in the contribution guidelines. 

@mcabbott any suggestions on how I can run the tests locally? I want to contribute to this package going ahead.

**Comment by mcabbott** [comment]
Something like this works for me locally. This is what Kyle means by activate the folder:
```
cd docs
rm Manifest.toml
julia --project
] instantiate
exit()
julia --project make.jl
```
It will print many warnings, some of which are things we should fix, and should report that doctests pass:
```
┌ Warning: invalid local link: unresolved path in gpu.md
│   link.text =
│    1-element Vector{Any}:
│     "basic example"
│   link.url = "@ref man-basics"
└ @ Documenter.Writers.HTMLWriter ~/.julia/packages/Documenter/H5y27/src/Writers/HTMLWriter.jl:2081
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: Skipped ExpandTemplates step (doctest only).
[ Info: Skipped CrossReferences step (doctest only).
[ Info: Skipped CheckDocument step (doctest only).
[ Info: Skipped Populate step (doctest only).
[ Info: Skipped RenderDocument step (doctest only).
Test Summary:  | Pass  Total     Time
Doctests: Flux |    1      1  1m19.9s
```
