### ISSUE TITLE
adding type arguments for common NN component constructors

### ISSUE THREAD

**Issue by ExpandingMan** [FluxML/Flux.jl#225]
Following the discussion [here](https://discourse.julialang.org/t/knet-vs-mxnet-for-programmer-new-to-ml/10073/19?u=expandingman), it would be nice if common NN component constructors such as `Dense` or `LSTMCell`, etc were easier to construct with weights of a specific type, e.g. `Float32`.  When using the GPU you probably mostly want to use `Float32` anyway, so perhaps `Float32` would even be a more reasonable default than `Float64`.  Another possibility might be making this some sort of feature of the `gpu` function.

**Comment by MikeInnes** [comment]
The best way to do this is via `mapleaves`; I'll add some utilities around that.

**Comment by MikeInnes** [comment]
Done in #572.
