### ISSUE TITLE
Flux.state binding does not exist

### ISSUE THREAD

**Issue by banachtech** [FluxML/Flux.jl#2256]
Hi - The documentation refers to using Flux.state for saving and loading models. However, I get the error that state does not exist.

The old way of saving and loading using BSON.@save and BSON.@load do not work anymore without explicitly importing MLUtils. It used to work before without that import.

**Comment by ToucheSir** [comment]
What version of Flux are you using? If it's not the most recent v0.13.16 then you won't have `Flux.state`.

> The old way of saving and loading using `BSON.@save` and `BSON.@load` do not work anymore without explicitly importing MLUtils. It used to work before without that import.

This seems like a separate issue (though it shows you why we're moving away from this approach). Do you have a MWE?

**Comment by ToucheSir** [comment]
https://github.com/FluxML/Flux.jl/pull/2205 exists precisely to avoid this loading issue, and indeed I get a different output when I create the same model:

```julia-repl
julia> model = @autosize (60,30,1,1) Chain(
                          Conv((2,2), 1 => 2, pad = SamePad()),
                          MaxPool((2,2)),
                          BatchNorm(_),
                          Dropout(0.5),
                          Flux.flatten,
                          Dense(_,60,relu),
                          softmax,
                      )
Chain(
  Conv((2, 2), 1 => 2, pad=(1, 0, 1, 0)),  # 10 parameters
  MaxPool((2, 2)),
  BatchNorm(2),                         # 4 parameters, plus 4
  Dropout(0.5),
  Flux.flatten,
  Dense(900 => 60, relu),               # 54_060 parameters
  NNlib.softmax,
)         # Total: 6 trainable arrays, 54_074 parameters,
          # plus 2 non-trainable, 4 parameters, summarysize 212.102 KiB.
```

It was added in v0.13.14 as a bugfix, so it looks like you're exactly one version behind!

**Comment by banachtech** [comment]
Oops. Thanks!
