### ISSUE TITLE
GPU/CUDA memory leak

### ISSUE THREAD

**Issue by RomeoV** [FluxML/Flux.jl#2261]
I have a somewhat complicated training setup and have recently started encountering CUDA-out-of-memory issues which only show up after a number of epochs.

I have managed to construct a minimum working example here:
```julia
using Flux
using FastAI
using MLUtils

function main()
    DEVICE = gpu
    model = Chain(Dense(32*32*3=>2048), Dense(2048=>6), Dense(6, 32*32*3))

    make_data_sample_test(i) = (rand(Float32, 32*32*3),
                                rand(Float32, 32*32*3))
    data = mapobs(make_data_sample_test, 1:1024)
    dl     = DataLoader(data; batchsize=32, collate=true)
    dl_val = DataLoader(data; batchsize=32, collate=true)

    loss = Flux.Losses.logitbinarycrossentropy
    opt = Flux.Adam(3e-4)
    learner = FastAI.Learner(model, loss;
                             optimizer=opt,
                             data=(dl, dl_val),
                             callbacks=[FastAI.ToGPU(), ])

    fit!(learner, 2_000)
end
```

After about 50 epochs (~1 minute on my laptop), I get an error that CUDA cannot allocate any more memory.
Empirically, it seems to always occur in here:
```
 [13] apply!(o::Adam, x::CUDA.CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, Δ::CUDA.CuArr
ay{Float32, 2, CUDA.Mem.DeviceBuffer})
    @ Flux.Optimise ~/.julia/packages/Flux/EHgZm/src/optimise/optimisers.jl:179
```
which is why I am filing this issue in `Flux.jl` instead of `FastAI.jl`.

I am on Julia 1.9 with the latest version of `Flux`, `FastAI`, and `MLUtils` installed. The above MWE works (fails) in an isolated project with no other dependencies.

Can anybody confirm whether this problem occurs for them to, and possibly have a pointer? I already spend a lot of time trying out all kinds of tweaks, and bringing it down to this MWE.

Possibly related (but old): https://github.com/JuliaGPU/CUDA.jl/issues/137

**Comment by RomeoV** [comment]
Ok it seems that plugging in `Optimisers.Adam` instead of `Flux.Adam` solves the issue.
Perhaps then the issue stems from https://github.com/FluxML/FluxTraining.jl/commit/4c9e98bd7d760bc2c5a56e7096a80bd70073918b, when `FluxTraining.jl` was aiming to adapt to `Optimisers.jl` (?!)

**Comment by DrChainsaw** [comment]
A common issue with the old stateful optimisers is that any form of parameter transformation makes the parameters in the model and the parameter to state Dict in the optimisers different objects. This causes the state to  grow indefinitely since it is never cleared and it will just keep seeing new parameters to add to the state.

For example, if that ToGpu callback is done once per training iteration and it does not simultaneously transform the optimiser and the model then this will happen. 

A simple way to test this is to run a few iterations and see if the optimiser now has many more parameters stored than the model.

**Comment by RomeoV** [comment]
Thanks @DrChainsaw. That seems spot on!
Adding
```julia
using FastAI.FluxTraining
for _ in 1:5
  FluxTraining.epoch!(learner, FluxTraining.TrainingPhase())
  @show length(opt.state)
end
```
to the above code snippet yields
```
length(opt.state) = 6
length(opt.state) = 12
length(opt.state) = 18
length(opt.state) = 24
length(opt.state) = 30
```
where each state consists of a bunch of GPU arrays.

**Comment by DrChainsaw** [comment]
>Do I understand you correctly that the ToGpu callback should also apply to the optimizer to fix this problem?

Yes, that would be the only fix I can think of. Perhaps open an issue at FluxTraining.jl pointing to this one (which perhaps should be closed).
