### ISSUE TITLE
have buildkite run GPU tests only

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#2271]
Currently buildkite is running both cpu and gpu tests. 
Since cpu tests take quite some time and they run on the github CI already we should let buildkite run only the gpu tests.

**Comment by codetalker7** [comment]
For this, how about: adding a new environment variable "FLUX_TEST_CPU", and run each CPU test block only if this variable is true?

**Comment by ToucheSir** [comment]
Sounds reasonable to me, but it should be true by default to support running tests locally.
