### ISSUE TITLE
Explicitly calling the optimizers

### ISSUE THREAD

**Issue by jbrea** [FluxML/Flux.jl#228]
There are situations where I would like to call the optimizer explicitly, e.g. ```opt(params, grad)``` or ```update!(params, grad, opt)```. I think this could be achieved while maintaing modularity with e.g.
```julia
mutable struct Momentum
    ρ
    η
    v
    schedule
end
function (m::Momentum)(g)
    m.schedule(m)
    @. m.v = m.ρ * m.v - m.η * g
end

mutable struct SGD
    η
    momentum
    schedule
end
function (opt::SGD)(p, g)
    opt.schedule(opt)
    @. p -= opt.η * opt.momentum(g)
end
```
where schedule could be expdecay or invdecay.
What do you think?

**Comment by MikeInnes** [comment]
Addressed by #379.
