### ISSUE TITLE
@autosize macro is not working

### ISSUE THREAD

**Issue by alerem18** [FluxML/Flux.jl#2296]
it's not a part of Flux package
i used Flux.@autosize or using Flux
@autosize is not available

**Comment by ToucheSir** [comment]
There's a 90% chance you have a too old version of Flux. Check to make sure other packages in your environment aren't holding it back.

**Comment by alerem18** [comment]
Status `C:\Users\Administrator\.julia\environments\v1.9\Project.toml`
  [587475ba] Flux v0.14.1
  
  also not working with autocomplete
using Flux doesn't show it methods, like Losses, gradient, params, etc

**Comment by darsnack** [comment]
We need more information about your environment. How are you running the code? VS Code and running a file? Opening a REPL and running commands?

**Comment by alerem18** [comment]
open repl and running commands line by line, like the jupyter notebook

**Comment by darsnack** [comment]
Can you reproduce the issue and copy-paste the **full contents** of your REPL here? Please run `] status` before reproducing the issue.
