### ISSUE TITLE
MethodError: Cannot `convert` an object of type TrackedArray{…,Array{Float64,0}} to an object of type Float64 

### ISSUE THREAD

**Issue by DimitriKolnikov** [FluxML/Flux.jl#230]
Hello,
I'm new to Flux, and trying to make simple tests, with a very classical loss function : 
loss(x, y) = sum(Flux.mse.(m.(x), y))
with in my case 
X and Y are: Vector{Array{Float64,1}}
the result of the loss function is of type: 
Tracked 0-dimensional Array{Float64,0}
but it seems that the train! function expects at some point a simple Float64, and it cannot convert
from Tracked 0-dimensional Array{Float64,0} to Float64.

It seems related to Issue #164, except the latter was solved.
Thank you for the help you could provide !

**Comment by MikeInnes** [comment]
Can you provide a minimal example that I can run?

**Comment by bhvieira** [comment]
Tracker has been phased out in favor of Zygote. Can this be closed? @dhairyagandhi96

**Comment by dhairyagandhi96** [comment]
We could move it to Tracker, possibly?

**Comment by bhvieira** [comment]
Sure, I'm just skimming the Issues queue to see the ones that are in need right now
