### ISSUE TITLE
No cudnn implementation of Conv((1,) N=>M)

### ISSUE THREAD

**Issue by ludvigk** [FluxML/Flux.jl#2322]
When doing 1d convolutions with a kernel size of 1 I get a warning that no valid algorithms are found. 

**Julia Version 1.9.3**
```julia
using Flux, CUDA
c = Conv((1,), 1=>1) |> gpu
x = randn(1,1,1) |> gpu
c(x)
```

`Warning: No valid algorithm found, probably bad params for convolution.`

**Comment by ludvigk** [comment]
Interestingly, `ConvTranspose` works perfectly fine with kernel size 1.  The following gives no warning:

```julia
using Flux, CUDA
c = ConvTranspose((1,), 1=>1) |> gpu
x = randn(1,1,1) |> gpu
c(x)
```

**Comment by ToucheSir** [comment]
Can you post the other package versions in your environment? The Julia version alone doesn't tell us much. The version info from CUDA.jl as well. Lastly, make sure you have ample memory available before running the code. This error can pop up if you're near the memory limit of your GPU.

**Comment by ludvigk** [comment]
> ...make sure you have ample memory available before running the code.

I was not aware of this. When you pointed it out, I thought this might have been the case, but I re-checked, and this time I had plenty of available memory.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:2D:00.0 Off |                  N/A |
| 27%   30C    P8    20W / 250W |   2195MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

I tested on a clean environment with only the following packages:
CUDA v4.4.1
Flux v0.14.3
cuDNN v1.1.0

```julia
CUDA.versioninfo()

CUDA runtime 11.8, artifact installation
CUDA driver 11.7
NVIDIA driver 515.65.1

CUDA libraries: 
- CUBLAS: 11.11.3
- CURAND: 10.3.0
- CUFFT: 10.9.0
- CUSOLVER: 11.4.1
- CUSPARSE: 11.7.5
- CUPTI: 18.0.0
- NVML: 11.0.0+515.65.1

Julia packages: 
- CUDA: 4.4.1
- CUDA_Driver_jll: 0.5.0+1
- CUDA_Runtime_jll: 0.6.0+0

Toolchain:
- Julia: 1.9.3
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce RTX 2080 Ti (sm_75, 7.367 GiB / 11.000 GiB available)
```

It's worth noting that Conv and ConvTranspose are equivalent in this case, so I can work around it using ConvTranspose. I don't know if that's helpful for fixing the issue with Conv though. 

```julia
c = Conv((1,), 2 => 3);
ct = ConvTranspose(permutedims(c.weight, (1,3,2)), c.bias);
x = randn(Float32, 2,2,1);
c(x) == ct(x)
```

**Comment by ludvigk** [comment]
It turns out `ConvTranspose` runs into the same issue when the number of input channels is just slightly larger. 
```julia
c = ConvTranspose((1,), 8=>1) |> gpu
x = randn(1,8,1) |> gpu
c(x)
``` 
`Warning: No valid algorithm found, probably bad params for convolution.`

At the point of testing, I had more than 9GB of available VRAM, so I don't see how that could be the issue. With 2d convolutions, there is no problem, even with over 10,000 input channels.

**Comment by ToucheSir** [comment]
I tried replicating the first example and wasn't able to:
```
CUDA runtime 12.1, artifact installation
CUDA driver 12.1
NVIDIA driver 530.30.2

CUDA libraries:
- CUBLAS: 12.1.3
- CURAND: 10.3.2
- CUFFT: 11.0.2
- CUSOLVER: 11.4.5
- CUSPARSE: 12.1.0
- CUPTI: 18.0.0
- NVML: 12.0.0+530.30.2

Julia packages:
- CUDA: 4.4.0
- CUDA_Driver_jll: 0.5.0+1
- CUDA_Runtime_jll: 0.6.0+0

Toolchain:
- Julia: 1.9.3
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: Tesla V100S-PCIE-32GB (sm_70, 30.976 GiB / 32.000 GiB available) 
```
Comparing versions, the main difference appears to be having newer CUDA libraries because of a new driver. Are you able to update the Nvidia drivers on your system?

**Comment by ludvigk** [comment]
I updated to Nvidia driver 535, but I can't seem to figure out how to upgrade the CUDA libraries. I deleted the whole artifact folder, but it re-downloaded the same CUDA library versions. The only difference is that it upgraded the NVML from 11.0.0 to 12.0.0. Seems likely that this is the root cause though if you can't replicate the behavior.

**Comment by ToucheSir** [comment]
Your best bet may be to ask how to upgrade said libraries in the Julia GPU help channels. As-is I'm pretty stumped.

**Comment by ludvigk** [comment]
I updated the CUDA runtime version to 12.1 to match yours, and the first example still gives me the same warning. The CUDA runtime libraries are the same version, but my NVIDIA driver installation is 535 instead of 530. The first time I used version driver version 515. It would be surprising if 530 was the version that works.

```
CUDA runtime 12.1, artifact installation
CUDA driver 12.2
NVIDIA driver 535.86.10

CUDA libraries: 
- CUBLAS: 12.1.3
- CURAND: 10.3.2
- CUFFT: 11.0.2
- CUSOLVER: 11.4.5
- CUSPARSE: 12.1.0
- CUPTI: 18.0.0
- NVML: 12.0.0+535.86.10

Julia packages: 
- CUDA: 4.4.1
- CUDA_Driver_jll: 0.5.0+1
- CUDA_Runtime_jll: 0.6.0+0

Toolchain:
- Julia: 1.9.3
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce RTX 2080 Ti (sm_75, 8.606 GiB / 11.000 GiB available)
  ```

**Comment by ToucheSir** [comment]
I doubt that's the case either. Just a quick sanity check, have you restarted your system after installing newer drivers?

To proceed, we definitely need more information on where this error is coming from. Can you re-run your original example with the `JULIA_DEBUG=CUDA,cuDNN` environment variable set?

**Comment by ToucheSir** [comment]
Ok, can you run a quick `] up`, ensure you have cuDNN v1.1.1 and try again? What I think is happening is that a change we made to avoid a spurious warning never made it into an actual cuDNN.jl release, so I asked the CUDA.jl maintainers for a new one.

**Comment by ludvigk** [comment]
That did it! Thank you.
