### ISSUE TITLE
`using Flux, cuDNN` freezes, but `using Flux, CUDA, cuDNN` works

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/Flux.jl#2346]
I am trying to load `Flux` and then `cuDNN` but it freezes at `using cuDNN`. However, loading `Flux`, then `CUDA`, then `cuDNN` works. Any idea why?

**Comment by darsnack** [comment]
cuDNN has its own extension that triggers on CUDA + cuDNN. I don't see what would hang in the extension itself, so maybe the partial overlap of CUDA is causing issues for the extension system?
```
[extensions]
FluxAMDGPUExt = "AMDGPU"
FluxCUDAExt = "CUDA"
FluxCUDAcuDNNExt = ["CUDA", "cuDNN"]
FluxMetalExt = "Metal"
```

**Comment by CarloLucibello** [comment]
I cannot reproduce this
```julia
julia> using Flux

julia> using cuDNN
Precompiling FluxCUDAcuDNNExt...
  1 dependency successfully precompiled in 17 seconds. 217 already precompiled.

julia>
```
