### ISSUE TITLE
precompilation issue on Julia 1.10

### ISSUE THREAD

**Issue by truedichotomy** [FluxML/Flux.jl#2354]
When installing Flux (both released v0.14.6 or master) on Julia 1.10, the precompilation of the package and its dependencies will take place whenever the Pkg.precompile command is issued, it doesn't matter if it's already been done previously. The precompilation state of the package does not seem to be saved. There are about 27 dependencies that do this.

versioninfo:
```
Platform Info:
  OS: macOS (arm64-apple-darwin23.1.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by ToucheSir** [comment]
I can't repro this on Linux with the latest 1.10 RC. It may be a MacOS thing with Julia 1.10, or maybe some dependency is causing issues. Either way, the issue probably doesn't lie with Flux itself.
