### ISSUE TITLE
Android/iOS support

### ISSUE THREAD

**Issue by alicewith** [FluxML/Flux.jl#2357]
### Motivation and description

Is there any plan to support Android and iOS for inference of given models?

**Comment by darsnack** [comment]
Currently, this is more of a question for Julia itself. I'm sure someone out there has gotten it to run on Android (I doubt iOS has been successful). But until running Julia on these platforms is standard, we can't really plan Flux specific support. Note that "support" here means optimizations for the hardware and lower level NN libraries. In general, Flux will run anywhere Julia runs as long as you use standard types (but it may be slow).

I'm closing this as not planned.
