### ISSUE TITLE
Dimensions check for `Conv` is incomplete, leading to confusing error

### ISSUE THREAD

**Issue by BioTurboNick** [FluxML/Flux.jl#2398]
### Motivation and description

This is the sort error message produced when a 3d array is passed to `Conv` which expects WHCD.

```
ERROR: DimensionMismatch: layer Conv((5, 5), 1 => 16, relu, pad=2) expects size(input, 2) == 1, but got 64×64×32 CUDA.CuArray{Float32, 3, CUDA.Mem.DeviceBuffer}
Stacktrace:
  [1] _size_check(layer::Flux.Conv{…}, x::CUDA.CuArray{…}, ::Pair{…})
    @ Flux C:\Users\nicho\.julia\packages\Flux\qZO6T\src\layers\basic.jl:195
```

The intended error is that the second to last dimension, which is the channel dimension, is expected to be 1 to match the input channels for the layer, but what it actually says is that the second dimension of the input is expected to be 1, and it's just not clear why that is unless you already know how it should work.

The check function currently just ensures that the input array is at least 2 dimensions. It should really check that the input array matches the kernel dimensions + 2, no? And this may be naive, but it looks like the weights array dimensions matches the expected input dimensions, and could be used for this purpose?

**Comment by mcabbott** [comment]
Code is here:

https://github.com/FluxML/Flux.jl/blob/85d953af58aa270f27cd4a4bdc971715a0545653/src/layers/conv.jl#L197-L198

and here:

https://github.com/FluxML/Flux.jl/blob/85d953af58aa270f27cd4a4bdc971715a0545653/src/layers/basic.jl#L192-L197

Looks like it assumes you got ndims right, which it should not.
