### ISSUE TITLE
Adding Simple Recurrent Unit as a recurrent layer

### ISSUE THREAD

**Issue by Jafagervik** [FluxML/Flux.jl#2408]
### Motivation and description

The recurrent.jl file already has implementations for RNN, LSTM and GRU layer, and I'm starting to work on implementing my own SRU to use in Julia as well. Its based on this [paper](https://arxiv.org/pdf/1709.02755.pdf). I thought this could be of general usage as well

### Possible Implementation

I don't have any code yet so far for it, so heres the attached pseudocode for a single layer: 

![1711203661](https://github.com/FluxML/Flux.jl/assets/20770505/b3f1f8de-5662-45b7-a204-637585e491b0)

**Comment by CarloLucibello** [comment]
This repo https://github.com/MartinuzziFrancesco/RecurrentLayers.jl
has a good collection on less common recurrent layers. You could contribute the layer there.
