### ISSUE TITLE
Automatic gradient detaching

### ISSUE THREAD

**Issue by staticfloat** [FluxML/Flux.jl#244]
When training RNNs over very long sequences, it would be really neat to "automatically detach" gradients that have gone beyond a certain limit.  E.g. if I have an RNN operating upon a sequence, it's typical to `detach()` the gradients after a certain batch size, then continue feeding in values so as to train the RNN up on a long sequence without having a trail of gradients reaching back thousands of timepoints and creating precision nightmares by exponentiating a floating point value thousands of times.

I'm not sure what the best API for something like this would be:

* Tree based; automatically prune anything with a multiplicative depth over some threshold?  E.g. walk the tracked array tree and eliminate gradients that flow through something that has been multiplied by parameters more than `N` times

* Sequence based; give gradients a "time to live" and every time we call `back!()`, eliminate any gradients on parameters that existed `N` time steps ago.

This would enable RNNs to have a more "streaming" functionality to them, instead of operating on the blocks and chunks that they typically do.

**Comment by iblis17** [comment]
why `truncate!` can fit for these cases?

**Comment by MikeInnes** [comment]
How about:
```julia
h, y = rnn(h, x)
h = cut!(h, 10)
```
`cut!` does two things -- first, it inserts a node into the graph (without altering the value of `h`). Second, it walks the graph to look for the *last* cut node (or the second last, or whatever) and drops the gradient.

The layer-level API for this is a little ugly though.

```julia
m = Chain(LSTM(10,5),LSTM(5,2))
m[3].state = cut!(m[3].state)
```
but I'm not sure how to express this better.

Anyway, this should be fairly easy to get working (@staticfloat happy to give any guidance if you want to take a crack). At some point we'll have to think about how this all interacts with #86, which I think may make this nicer.

**Comment by staticfloat** [comment]
I'm not entirely sure what the API you're suggesting above means.  With `h, y = rnn(h, x)`, does `cut!(h, 10)` mean "insert a node in the graph here, then walk backward until you reach the 10th cut node away from here, and snip the gradients there"?  If so, that makes sense to me.

**Comment by MikeInnes** [comment]
Yup, that's it.

**Comment by MikeInnes** [comment]
#648 represents the latest thinking on this.
