### ISSUE TITLE
The dependency error about `Flux->FluxMPIExt` occurs when updating to Julia 1.11

### ISSUE THREAD

**Issue by pinkieli** [FluxML/Flux.jl#2490]
When updating to Julia 1.11, I resolve to update all necessary changes for the installed packages. The following error occurs.
![image](https://github.com/user-attachments/assets/ad6b6ec7-9a99-48c0-9073-fe268472ec11)

Further, when I instantiate all packages in Julia 1.11, it still exists, as shown in the figure below.
![image](https://github.com/user-attachments/assets/e6d488ed-fe5a-4ee2-a688-ed4e4f856861)

Following its hint, the `julia> err` presents the following information:
![image](https://github.com/user-attachments/assets/6bd3ceff-c86a-4353-9c9f-c52bc0a91299)

Are there some ways to resolve this issue? I welcome any suggestions you may have. Thanks a lot.

**Comment by ToucheSir** [comment]
See also the discussion on https://github.com/FluxML/Flux.jl/pull/2488.
