### ISSUE TITLE
Flux has no Lecun Normalization weight init function?

### ISSUE THREAD

**Issue by neoareslinux** [FluxML/Flux.jl#2491]
### Motivation and description

Flux has no buildin Lecun Normalization weight init function?

i can't found any information in doc, or shoud i implement my own version?

**Comment by mcabbott** [comment]
This is #2290, for which there are [two PRs](https://github.com/FluxML/Flux.jl/pulls?q=is%3Apr+is%3Aopen+Lecun+), which seem to have fallen through the cracks.  #2311 looks OK, needs tests.
