### ISSUE TITLE
fft() within `Chain` breaks things

### ISSUE THREAD

**Issue by staticfloat** [FluxML/Flux.jl#250]
Something funky is happening to my model's ability to train when I include a `x -> abs.(fft(x))` within my `Chain()`; the training accuracy stays at 50%, which is random chance.  Here is a working example:

```julia
using Flux, Compat

import Base: start, next, done, length

struct SinTestDatasource
    batch_size::Int64
    sequence_len::Int64
    w1::Float64
    w2::Float64
    x::Array{Float64,2}
    y::Array{Float64,2}
end

function SinTestDatasource(batch_size, sequence_len, w1, w2)
    x = Array{Float64}(undef, sequence_len, batch_size)
    y = Array{Float64}(undef, 2, batch_size)
    
    return SinTestDatasource(batch_size, sequence_len, w1, w2, x, y)
end

function next_batch(st::SinTestDatasource)
    for batch_idx in 1:st.batch_size
        y = rand(0:1)
        ϕ = 0 #2*π*rand()
        t = 2*π*(1:st.sequence_len)./st.sequence_len
        if y == 0
            t .*= st.w1
        else
            t .*= st.w2
        end
        st.x[:, batch_idx] .= sin.(t .+ ϕ) .+ 0.01*randn(st.sequence_len)
        st.y[:, batch_idx] .= vcat(y, 1-y)
    end
    
    return st.x, st.y
end

start(st::SinTestDatasource) = 1
next(st::SinTestDatasource, idx) = (next_batch(st), idx+1)
done(st::SinTestDatasource, idx) = idx >= length(st)
length(st::SinTestDatasource) = 10000


batch_size = 2
sequence_len = 900
datasource = SinTestDatasource(batch_size, sequence_len, 2, 30)
model = Chain(x -> abs.(fft(x))./900, Dense(sequence_len, 2), softmax)
opt = Flux.Optimise.SGD(Flux.params(model), 1e-3)
Flux.train!((x, y) -> Flux.crossentropy(model(x), y), datasource, opt)
```

The above code will not train properly at all, however if I take away the `x -> abs.(fft(x))./900` from the `Chain()` and instead put it into `next_batch()` such that the assignment to `st.x` becomes:

```julia
st.x[:, batch_idx] .= abs.(fft(sin.(t .+ ϕ) .+ 0.01*randn(st.sequence_len)))./900
```

Then it trains perfectly.  I don't understand what could be happening here, since the only parameters that are being tweaked are "downstream" of this.

**Comment by MikeInnes** [comment]
Haven't looked at your code in detail but I'm not sure why it would work at all – we don't have a gradient of `fft` defined, or any strategy for complex numbers (#217).

```julia
julia> xs = param([1,2,3])
Tracked 3-element Array{Float64,1}:
 1.0
 2.0
 3.0

julia> ys = fft(xs)
ERROR: MethodError: Cannot `convert` an object of type Flux.Tracker.TrackedReal{Float64} to an object of type Float64
```

What am I missing?

**Comment by staticfloat** [comment]
The `fft()` is "upstream" of any parameters; I thought that the `TrackedArray` stuff was introduced by the parameters of the model, and since there are no parameters involved in the model until you hit the `Dense` layer in my model, it seemed that we wouldn't have to worry about backpropagating through this.

My understanding was that Flux's AD works by tracking operations through `TrackedArray` objects that, when combined with "normal" arrays, propagate the `TrackedArray` type and keep a record of the operations applied.  However, since there are no `TrackedArray` objects involved until we hit the `Dense` layer, I don't understand why having the `abs.(fft(x))` within the `Chain`, or done just before the Chain would matter.

**Comment by MikeInnes** [comment]
Ah, I see. That's pretty weird then, I'll have to take a look.

Using `Tracker.gradient` might help to narrow down what's going on with the gradients a bit better.

**Comment by MikeInnes** [comment]
Is this still an issue on 1.0?

**Comment by staticfloat** [comment]
Sigh, no and it never was.  Turns out that Julia does a multidimensional `fft()` by default, so when things get batched together I was doing an FFT across the batches as well as across time.  This was completely my fault. :P
