### ISSUE TITLE
ERROR: UndefVarError: `ADAM` not defined in `Main` in flux

### ISSUE THREAD

**Issue by Liuxiu1512** [FluxML/Flux.jl#2507]
Hi, i get this error when try to using flux
julia> using Pkg
julia> Pkg.add(“Flux”)
Resolving package versions…
No Changes to C:\Users\lbtvi\.julia\environments\v1.11\Project.toml
No Changes to C:\Users\lbtvi\.julia\environments\v1.11\Manifest.toml
julia> Pkg.add(“Images”)
Resolving package versions…
No Changes to C:\Users\lbtvi\.julia\environments\v1.11\Project.toml
No Changes to C:\Users\lbtvi\.julia\environments\v1.11\Manifest.toml
julia> Pkg.add(“BSON”)
Resolving package versions…
No Changes to C:\Users\lbtvi\.julia\environments\v1.11\Project.toml
No Changes to C:\Users\lbtvi\.julia\environments\v1.11\Manifest.toml
julia> using Flux
julia> using Flux.Optimise
julia> using BSON
julia> using Images

julia> opt = ADAM(0.001) # Khai báo tối ưu hóa ADAM với learning rate là 0.001
ERROR: UndefVarError: ADAM not defined in Main
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name may be made accessible by importing Optimisers in the current active module Main
Stacktrace:
[1] top-level scope
@ REPL[10]:1

julia>
julia> @epochs 10 Flux.train!(loss, params(model), data, opt) # Huấn luyện mô hình
ERROR: LoadError: UndefVarError: @epochs not defined in Main
Suggestion: check for spelling errors or missing imports.
in expression starting at REPL[12]:1

julia> using Flux: @epochs # Nhập @epochs từ Flux
WARNING: could not import Flux.@epochs into Main

julia>
How can i fix this, thanks alot

**Comment by CarloLucibello** [comment]
that seems old code. Please read the manual. 
https://fluxml.ai/Flux.jl/stable/guide/training/training/
