### ISSUE TITLE
Flux + Julia ecosystem docs

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#251]
@oxinabox mentioned MLDataUtils.jl in https://github.com/FluxML/Flux.jl/pull/220#issuecomment-384870015. It seems @evizero has a bunch of great stuff that will work with Flux, and even more broadly we can work with things like DifferentialEquations.jl really nicely.

We can't cover everything, but even a few examples would give people a sense of what's possible.

**Comment by ToucheSir** [comment]
I believe this should be addressed by #1057 and the great GSOD work we had recently.
