### ISSUE TITLE
The Great Cat Issue

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#252]
Recording all the PRs I have on this in one place – #156, #184, #243, #194. Will have to merge all of these in some way.

Also issue #213.

**Comment by philtomson** [comment]
Is there a fix for this? Pretty sure I'm running into the same problem.

**Comment by gustafsson** [comment]
Worth to mention: https://github.com/JuliaLang/julia/pull/20815

**Comment by gustafsson** [comment]
I had a go at merging these into #243.

I added tests from the different PRs and issues as well as the implementation of `cat(dims, x...)` from #156

**Comment by MikeInnes** [comment]
Ok, that's great! Could you [credit the PR authors](https://blog.github.com/2018-01-29-commit-together-with-co-authors/) in the commit for that, and I'll take a look at merging?

**Comment by gustafsson** [comment]
Done! Thanks for the link about co-authorship

**Comment by MikeInnes** [comment]
#243 is merged including everyone's work -- thanks @gustafsson!
