### ISSUE TITLE
broken image in the quickstart

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#2530]
In the [quickstart](https://fluxml.ai/Flux.jl/dev/guide/models/quickstart/), After "Here's the loss during training:" the image is not displayed.

I don't know what is wrong with this line
https://github.com/FluxML/Flux.jl/blob/0a324f8f7eaeeb01f5c43c60322b6a2585b24ab4/docs/src/guide/models/quickstart.md?plain=1#L65

**Comment by mcabbott** [comment]
Presumably broken by moving things in https://github.com/FluxML/Flux.jl/pull/2422 ? The relative path no longer points to the same place.
