### ISSUE TITLE
Getting gradients in a recurrent system

### ISSUE THREAD

**Issue by rcnlee** [FluxML/Flux.jl#259]
In the flux.jl documentation, it says that I can get the gradients by declaring weights W as a ``param``, calling`` back!(l)``, and then inspecting the ``grad`` field. How do I do this for a recurrent system? I want to get the sequence of gradients for a sequence of inputs.

In another application, I am also interested in getting the gradient with respect to the input (not the weights).  How do I do this for a recurrent system?

Thanks!

**Comment by MikeInnes** [comment]
Depending on what exactly you're looking for, you probably just want to call forward and `back!` repeatedly, collecting and zeroing out the gradients each time. `Tracker.gradient` might make this easier if you can write your model using it.

To get the gradient of the input, just wrap it in a `param` as if it's a weight, and you'll get gradients the same way.
