### ISSUE TITLE
How does dense layer work ?

### ISSUE THREAD

**Issue by Julien281** [FluxML/Flux.jl#271]
Hello

I would like use the function `Dense`  to create a dense layer in the beginning of my neural network.

I created my weights with the following function:
```

function weight_variable(shape)
    initial = map(Float32, rand(Normal(0,0.001), shape...)) 
   return Variable(initial)
end

weight = weight_variable([36,1])  # 36 random values
```
If I have a batch of 10, I will have something like this in input:

`input = reshape([1.0 2 3 4 5 6 7 8 9 10], (10,1)) `

After that, I'm using using the Dense function to crerate my first layer like this:

`layer = Chain(Dense(10,36), BatchNorm(10, λ = relu))`

In the source code, there is the following:

```
Dense(in::Integer, out::Integer, σ = identity)
Creates a traditional `Dense` layer with parameters `W` and `b`.
    y = σ.(W * x .+ b)

```
So, I tried the following:

`logits = layer(weight, input)` and  `logits = layer(input)` 

These command does not work. So, how to use your function to create a dense layer with given  inputs and weights ? 

Thank you

**Comment by avik-pal** [comment]
The layer definition is incorrect. It should be: `layer = Chain(Dense(10,36), BatchNorm(36)`

Also weight should have a dimension `36 x 10`

As for custom weights try the following
```julia
julia> weights = rand(36,10);
julia> a = Dense(param(weights), param(zeros(36)), identity);
julia> layer = Chain(a, BatchNorm(36));
julia> layer(input)
```

**Comment by Julien281** [comment]
Thank you for your help

I have the following error with the last command ( `layer(input)`)

`ERROR: LoadError: KeyError: key Flux.Tracker.TrackedReal{Float64} not found`

My input is: `<Tensor Reshape:1 shape=(10, 1) dtype=Float32>`

**Comment by avik-pal** [comment]
Can you share the exact code with which other libraries you are using?

**Comment by Julien281** [comment]
After some try, I think it is because I declared a placeholder in my complete code ( I can't share it here, it is too long and not appropriate). Maybe I can open a new issue for this problem ?
