### ISSUE TITLE
GPU support failing on Ubuntu 16.04 with Julia 0.6.2

### ISSUE THREAD

**Issue by tymokvo** [FluxML/Flux.jl#272]
Hello,

I was trying to build the dependencies for CUDA support with Flux. However, the LLVM package fails to build with:

```
julia> Pkg.build("LLVM")
INFO: Building LLVM
=================================[ ERROR: LLVM ]=================================

LoadError: could not find LLVM installation providing llvm-config
```

On the LLVM [ReadMe](https://github.com/maleadt/LLVM.jl) it states that it must be built against Julia 0.7 or newer. This is also the case for CUDAnative.

There should perhaps be a note on the GPU support page about this? It conflicts with Flux's requirement for Julia version >= 0.6.0

Let me know any other info I can provide!

**Comment by maleadt** [comment]
> On the LLVM ReadMe it states that it must be built against Julia 0.7 or newer. This is also the case for CUDAnative.

... with the sentence after that specifying:

> Only older versions of this package, v0.5.x, work with Julia 0.6, and require a source-build of Julia.

So you probably aren't using a source build of Julia. On 0.7, you don't need a source build anymore, and everything will work out of the box. :slightly_smiling_face:
