### ISSUE TITLE
can't download datasets from flux

### ISSUE THREAD

**Issue by merckxiaan** [FluxML/Flux.jl#277]
When I try to run one of the models from the model-zoo, I get the following error:
`automatic download failed (error: 2148270088): http://cs.stanford.edu/people/karpathy/char-rnn/shakespeare_input.txt
download(::String, ::String) at interactiveutil.jl:598
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80
`
My pc has windows 10 home, I'm using Juno, but when I run the script in REPL, I get the same error?
Any ideas what's causing this?

Thanks in advance, 
Jules

**Comment by ViralBShah** [comment]
Perhaps we should host datasets where licensing permits.

**Comment by avik-pal** [comment]
Might be some windows related issue for the download, because the script runs fine on my Linux Based Machine
