### ISSUE TITLE
Training pipeline inappropriate for large datasets

### ISSUE THREAD

**Issue by avik-pal** [FluxML/Flux.jl#278]
Currently, we need to push the entire dataset to GPU before calling the `Flux.train!` function. But this is very inappropriate for large datasets where `CUDA runs out of memory`. Hence it would be better to have something where a single batch is pushed to GPU at the time of evaluation. A manual fix for this would be something like
```julia
for i in train
    l = loss(i[1] |> gpu, i[2] |> gpu)
    Flux.back!(l)
    opt()
end
```
@MikeInnes would this be an appropriate solution?

**Comment by MikeInnes** [comment]
The way to augment the training pipeline is to modify the data that you pass to `train!`. As a toy example, 

```julia
Flux.train!(m, (gpu(x) for x in data), ...)
```

It'd be great to have more patterns and utilities around the common cases here, though.
