### ISSUE TITLE
Tracker.gradient should take Tuple for parameter arguments 

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#281]
Where `f` is a multivariate function `Tracker.gradient` should take a tuple of its arguments as its second argument.
```
f(x1,x2) = scalarblablabla(x1,x2)
Tracker.gradient(x->f(x...),(x1,x2)) # This
Tracker.gradient((x1,x2)->f(x1,x2),x1,x2) #Not This
```

**Comment by jessebett** [comment]
My attempt:
```
function Tracker.gradient(f, xs::Tuple)
  xs = param.(xs)
  back!(f(xs))
  Tracker.grad.(xs)
end

f(x,y,z) = x.^2 + y.^4 + z.^5
Tracker.gradient(x->sum(f(x...)),([1.],[1.],[1.]))
```
This might not be great because it changes the splat from before which had it in the call to `Tracker.gradient` whereas now it's in the first argument lambda function... So there's probably a way to keep that consistent. 

Also, Tuple could probably be specified to have Tuple of `AbstractArrays`

**Comment by MikeInnes** [comment]
The way to do this is to make recursive functions of the `param` and `grad` functions. e.g. `_param(x::Tuple) = _param.(x)` etc. Then the rest of the code should do the right thing automatically.

**Comment by jessebett** [comment]
Hm... where are these `_param` internal functions, I don't see that anywhere.
I tried doing `grad(x::Tuple) = grad.(x)` and `param(xs::Tuple) = param.(xs)` but that doesn't stop there being a method error with `Tracker.gradient` not having a method matching `Tuple`.

**Comment by MikeInnes** [comment]
You'd have to define those, with appropriate fallbacks (`_param(x) = param(x)`). Then you'll need to remove the type restriction on `gradient` as well.

Adding the tuple method to `param` and `grad` would work fine, but I'm not sure about adding those to the official API right now, so having the internal method lets us make that decision later.

**Comment by MikeInnes** [comment]
Will go away with #669.
