### ISSUE TITLE
Tracker.grad on a non-param StackOverflows

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#284]
```
using Flux.Tracker
Tracker.grad(0.5) # StackOverflow
Tracker.grad([0.5]) # StackOverflow 

ERROR: StackOverflowError:
Stacktrace:
 [1] grad(::Void) at /Users/jessebett/.julia/v0.6/Flux/src/tracker/Tracker.jl:12 (repeats 80000 times)
```

This especially isn't great on Juno because Atom freezes and needs to be restarted...
Would it be possible maybe to return `nothing` or something?

I ran into this right now passing a mix of tracked and untracked weights into a function
` w = ( param(w1), w2, param(w3))` and then later doing something like `Tracker.grad(w)` stackoverflows. If this returned nothing it would be nice because then the return statement would give the grads for `w1` and `w3` without any finicking. Though maybe isn't nice for other reasons?

In any case it probably should at least return an error and not overflow?

**Comment by MikeInnes** [comment]
I actually fixed this as part of #283 so we just need to move that one line on to master.

**Comment by jessebett** [comment]
And your fix even returns `nothing`! Sweet!

**Comment by jessebett** [comment]
How likely is that to be included into master soon?
I could submit a PR with just this one change or just sit on this for my local branch until that all goes through.

**Comment by MikeInnes** [comment]
As it turns out, that PR is stalled for a while. Added the fix on master.
