### ISSUE TITLE
back!. for elementwise gradients

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#285]
If I have `L is scalar` then `back!(L)` gives `(dL/dx1, dL/dx2,...)`

What I’d like is if 
`L = [L1,L2,...]`
then `back!.(L) = ([dL1/dx1,dL2/dx1,...],[dL1/dx2,dL2/dx2,...])`

Essentially computing the gradient for each of the components of a L vector with respect to it's parameters.

Would this be the same thing that `jacobian` does but in `back!` syntax?

**Comment by MikeInnes** [comment]
We've now moved away from `back!` in favour of `gradient`, and have a `jacobian` function.
