### ISSUE TITLE
Error messages when CUDNN is not loaded.

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#287]
e.g. when running `conv` (at least until we have Julia implementations).

**Comment by maleadt** [comment]
https://discourse.julialang.org/t/flux-failing-on-gpu/18948
I'm not sure who is responsible for triggering `conversion to pointer not defined for CuArray{Float32,2}` when cuDNN isn't available, but it's pretty tough to debug for users and there's been multiple reports already.

**Comment by MikeInnes** [comment]
At a guess, the `gemm!` inside `conv` in NNlib. We should just have a generic `conv` fallback in CuArrays, even if it only errors out.

**Comment by darsnack** [comment]
Doesn't CUDA.jl do something like this now?

**Comment by maleadt** [comment]
Yes, you should always get a nice error when trying to use CUDNN when it isn't available.
