### ISSUE TITLE
Flux.Conv documentation somewhat unclear

### ISSUE THREAD

**Issue by fps** [FluxML/Flux.jl#309]
Quote: "Data should be stored in WHCN order. In other words, a 100×100 RGB image would be a 100×100×3 array, and a batch of 50 would be a 100×100×3×50 array.", but:

<pre>
julia> m = Flux.Chain(Flux.Conv((2,2), 1=>1))
Chain(Conv((2, 2), 1=>1))

julia> m(randn(28,28,1))
ERROR: MethodError: no method matching conv(::Array{Float64,3}, ::TrackedArray{…,Array{Float64,4}}; stride=(1, 1), pad=(0, 0), dilation=(1, 1))
Closest candidates are:
  conv(::Flux.Tracker.TrackedArray{#s54,N,A} where A<:AbstractArray{#s54,N} where #s54<:Real, ::Flux.Tracker.TrackedArray{#s53,N,A} where A<:AbstractArray{#s53,N} where #s53<:Real; stride, pad, dilation) where N at /home/fps/.julia/v0.6/Flux/src/tracker/array.jl:339
  conv(::AbstractArray{#s55,N} where #s55<:Real, ::Flux.Tracker.TrackedArray{#s54,N,A} where A<:AbstractArray{#s54,N} where #s54<:Real; stride, pad, dilation) where N at /home/fps/.julia/v0.6/Flux/src/tracker/array.jl:341
  conv(::Flux.Tracker.TrackedArray{#s55,N,A} where A<:AbstractArray{#s55,N} where #s55<:Real, ::AbstractArray{#s54,N} where #s54<:Real; stride, pad, dilation) where N at /home/fps/.julia/v0.6/Flux/src/tracker/array.jl:343
  ...
Stacktrace:
 [1] (::Flux.Conv{2,Base.#identity,TrackedArray{…,Array{Float64,4}},TrackedArray{…,Array{Float64,1}}})(::Array{Float64,3}) at /home/fps/.julia/v0.6/Flux/src/layers/conv.jl:44
 [2] mapfoldl_impl(::Base.#identity, ::Flux.##82#83, ::Array{Float64,3}, ::Array{Any,1}, ::Int64) at ./reduce.jl:43
 [3] (::Flux.Chain)(::Array{Float64,3}) at /home/fps/.julia/v0.6/Flux/src/layers/basic.jl:31
</pre>

Instead:

<pre>
julia> m(randn(28,28,1,1))
Tracked 27×27×1×1 Array{Float64,4}:
[:, :, 1, 1] =
  0.00452705  -0.0158127   -0.00711783   -0.00425715   0.0126382    …   0.00690474  -0.00713287    0.00496944   -0.00089717 
 -0.00274597  -0.00860457   0.00224724    0.00428337  -0.0186072        0.00410133   0.0267978     0.00527785   -0.00262631 
 -0.00697042   0.00435134  -0.0162859     0.021379    -0.00868529      -0.0052452    0.00446321    0.0327112    -0.00741287 
  0.00276405  -0.0145412   -0.00156656    0.0116986    0.0157532       -0.00786687  -0.00844344    0.0117134     0.0191242  
 -0.00439462  -0.00834209  -0.0267615    -0.00172025   0.0184832        0.00914797  -0.00215158    0.00307102   -0.00137879 
 -0.0134309   -0.00904393   0.0132471    -0.022718     0.00990268   …  -0.0024227    0.000489397   0.0120996     0.0148565  
  0.019957    -0.0167273   -0.010491      0.0103657    0.012845        -0.0158557   -0.0056088    -0.0225837    -0.00284451 
 -0.0169463    0.00362061   0.0003689     0.00192318   0.0169185        0.00765813   0.00362393    0.0119263    -0.0360615  
  0.00537716  -0.0118078    0.0177413    -0.0109077   -0.00887527      -0.00141734   0.0119095    -0.00617883    0.0277553  
  0.0249389    0.00205984   0.00659043    0.0104754    0.000681798      0.0115112   -0.0177994     0.00612122   -0.0159975  
 -0.0123112    0.0231232   -0.0150869    -0.00332219  -0.00215843   …   0.04083     -0.00214884   -0.014193      0.00818866 
  0.00888536  -0.00458879   0.0257786    -0.0239647    0.0194446       -0.0142714    0.0303414    -0.014513     -0.0059888  
  0.00098344  -0.00952765  -0.0180906     0.00259094  -0.00796661       0.027703    -0.0173049     0.000537885  -0.0180938  
 -0.00445927  -0.00493032   0.0117001    -0.0265736    0.0237252       -0.00991881   0.037704     -0.00967326   -0.0140083  
 -0.00675133   0.0157974   -0.00558512   -0.00447603  -0.0156403        0.0106239    0.0083231     0.0169085    -0.000884823
 -0.0100885   -0.0258378    0.0187921    -0.0191554   -0.0022069    …   0.0235969   -0.00345381    0.0250993     0.0109221  
  0.0136559    0.00332236  -0.0184954     0.0100634   -0.00778242      -0.00640122  -0.00385855    0.00494265    0.0265078  
  9.08998e-5   0.0211906    0.0114366     0.00463025  -0.00657308       0.0130702    0.0150735     0.00430149   -0.0222405  
  0.00807575  -0.00515197   0.0158206    -0.0112765    0.0275924       -0.0255945   -0.00947143   -0.0168492     0.00298624 
 -0.0132081    0.0135017    0.0114807     0.0141236   -0.0218414        0.0268045   -0.0253236    -0.0207675    -0.00155249 
 -0.0178998   -0.00127928   0.0126481    -0.0056472    0.00346426   …   0.00540533   0.0185262     0.0033542    -0.0246373  
  0.0100656    0.0144122    0.00635413    0.00345084  -0.00815359      -0.0102869    0.0077127     0.0323822     0.012502   
 -0.0171601    0.0205483    0.0259474     0.0137634   -0.0143359       -0.0223696   -0.00939653    0.0130898     0.0129155  
 -0.00135595  -0.0152599    0.044399      0.0170742    0.00681287      -0.023081     0.00315987    0.000493892  -0.00741404 
  0.0105868    0.00312098  -0.000420794   0.00379435  -0.0118727       -0.00118307  -0.0405051     0.0086667     0.0117971  
  6.80024e-5  -0.00838617   0.0176051     0.00691881   0.013862     …  -0.00728283   0.00746388   -0.004062     -0.0146695  
 -0.00670676   0.0207388   -0.00457279    0.00364217  -0.00544621      -0.0118644   -0.00703656    0.0119832     0.00645383 
</pre>

I would expect the Conv layer type to work on a single image of dims (w, h, 1).

**Comment by ayush1999** [comment]
@fps  An image is represented in 4 dimensions in Flux: `(W,H,C,N).` For a single image, `N` = 1. Hence the input should be of shape `(W,H,C,1)`. For the MNIST images, W=H=28 and C=1(Grey-scale). So, the input shape becomes `(28,28,1,1)`.
You should reshape your input image to 4 dimensions using `reshape(img, (28,28,1,1))` if your input is 3 dimensional.

**Comment by fps** [comment]
Yeah, this is now clear to me, after fiddling around a little. My point was that the docs could be clearer to save others from having to fiddle around to get the drift. I wasn't familiar with the "WHCN" term. After a little thought it's clear that it stands for width, height, channels, number.

What added to my confusion was the fact that e.g. the Dense layer works either with column vectors or with matrices since the involved operations nicely generalize over this distinction. So it surprised me that the same did not hold for the Conv layer.

**Comment by MikeInnes** [comment]
Yeah, ideally the conv operators should handle non-batched images so that the obvious thing works. We can make the docs a bit clearer in the mean time though.

**Comment by Marviel** [comment]
Ran into same issue here -- do you guys accept documentation update PRs?

**Comment by MikeInnes** [comment]
Docs PRs are great (apologies for not seeing this sooner).
