### ISSUE TITLE
Iterators for batches and epochs

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#317]
These are simple to do but it's just convenient to have explicit versions of them. We should also document patterns such as using `partition` for batches; and really any other patterns that come up in models a lot.

**Comment by shreyas-kowshik** [comment]
I've implemented a basic function with the following code for generating batches. This could be useful for generating batches.

```
using Base.Iterators: partition

function batch_iter(x::AbstractArray{T,N},batch_size::Int64) where {T,N}
    """
    Given an array of N-dimensions, this function will return an iterator over batches on this array
    """
    num_examples = size(x)[end]
    remaining_size = size(x)[1:end-1]
    BATCH_ALL = prod(remaining_size)
    
    return [reshape(float(hcat(data)),remaining_size) for data in partition(x,BATCH_ALL)]
end
```

Was this what was required? @MikeInnes

**Comment by Tokazama** [comment]
Would it be warranted to have some sort of batch type that annotates width, height, channels, minibatch size, etc.? As I've been doing digging I see these values extracted frequently in the code.

**Comment by MikeInnes** [comment]
That sounds more like #326. I do think something AxisArrays-like would be great for that kind of use case though.
