### ISSUE TITLE
Image upsampling with fractional stride

### ISSUE THREAD

**Issue by merckxiaan** [FluxML/Flux.jl#319]
I'm trying to implement a image detection network wich needs upsampling layers. I've read that an efficient way of doing upsampling is by using a convolutional layer with a fractional stride. Is there a way to implement this in Flux?
Any chance someone could implement an upsample layer like in other frameworks such as pytorch https://pytorch.org/docs/stable/_modules/torch/nn/modules/upsampling.html ?

Thanks in advance,
Jules

**Comment by avik-pal** [comment]
The linked layer in Pytorch is not the same as what you are looking for. As per your description, you are talking about `ConvTranspose` which is performed by Fractionally Strided Convolutions.
The `ConvTranspose` is currently in a WIP PR #311.
For simple `NearestUpsampling` you can just use the `Base.repeat` function.

**Comment by merckxiaan** [comment]
Oh, thanks!
