### ISSUE TITLE
segmented_sum

### ISSUE THREAD

**Issue by pevnak** [FluxML/Flux.jl#32]
Hello,
is there a simple way, how I can use segmented_sum in the model? I would like to use Flux to implement multi-instance learning problems as described in 
[Using Neural Network Formalism to Solve Multiple-Instance Problems](https://arxiv.org/abs/1609.07257).

Thank you very much for help.
Tomas

**Comment by MikeInnes** [comment]
You may want to mention it to @alha02 who's implementing a lot of tf ops in #28. It's pretty easy to do. I should add some docs for this.

**Comment by alha02** [comment]
@pevnak I added segment_sum op to my TODO-list in #28

**Comment by pevnak** [comment]
Thanks a lot. I am curious how flux will look like with it.

**Comment by pevnak** [comment]
For those interested in, it can be easily added as multiplication with sparse vector:

> function sparse_segmented_mean(x,segments::Vector{UnitRange{Int64}})
    s = zeros(eltype(x),size(x,2),length(segments))
    for (i,segment) in enumerate(segments)
        s[segment,i]=1./length(segment)
    end
    x*sparse(s)
end

or slightly faster version

>function fast_segmented_mean(x,segments::Vector{UnitRange{Int64}})
    rowval = collect(1:size(x,2))
    nzval = zeros(eltype(x),size(x,2))
    colptr = zeros(Int,length(segments)+1)
    colptr[end] = size(x,2)+1
    for (i,segment) in enumerate(segments)
        colptr[i] = segment.start
        nzval[segment] = 1./length(segment)
    end
    m = size(x,2)
    n = length(segments)
    x*SparseMatrixCSC(m,n,colptr,rowval,nzval)
end

**Comment by MikeInnes** [comment]
FWIW, while I don't know your use case exactly, this seems like a fairly strange construction to me. Often TensorFlow has things like this because it can't handle things like variable-length lists of tensors. So in Flux it might be possible to just use an array of matrices, and map the appropriate function over that list.
