### ISSUE TITLE
Catenate layer?

### ISSUE THREAD

**Issue by unhandyandy** [FluxML/Flux.jl#324]
Do you have any tool for merging tensors?  I didn't see one in the docs.

**Comment by MikeInnes** [comment]
In general we reuse all of Julia's normal array tools for many basic things like this, e.g. you can do

```julia
julia> vcat([1,2],[3,4])
4-element Array{Int64,1}:
 1
 2
 3
 4
```

or the more general `cat`.

(let me know if that's not what you were looking for.)

**Comment by unhandyandy** [comment]
Cool, thanks.

**Comment by unhandyandy** [comment]
Oops, I meant merging tensors from more than one NN layer into a single new one.  Is that possible?

**Comment by MikeInnes** [comment]
NN layers are just functions, you need to call them and do things with the results as usual. e.g.

```julia
a, b = Dense(...), ...
net(x) = vcat(a(x), b(x))
```
