### ISSUE TITLE
Pkg.update() in Julia 0.6.x gets you an incompatible version of Flux

### ISSUE THREAD

**Issue by philtomson** [FluxML/Flux.jl#341]
After doing a Pkg.update() in 0.6.3, I got a version of Flux that was incompatible with Julia 0.6:

```
ERROR: LoadError: ArgumentError: Module Statistics not found in current path.
Run `Pkg.add("Statistics")` to install the Statistics package.
```
Then when I tried to Pkg.add("Statistics") as suggested, It reported that the package was not found.

I found that I had to do:

Pkg.pin("Flux", v"0.5.4")

to get Flux to work in Julia 0.6.3 again.

**Comment by MikeInnes** [comment]
I'm not seeing this; is it possible that you ran `Pkg.checkout("Flux")` at some point? What happens if you do `Pkg.free("Flux")`?
