### ISSUE TITLE
Irrational power gradient bug?

### ISSUE THREAD

**Issue by mcabbott** [FluxML/Flux.jl#350]
I was upgrading some code to use `@grad` instead of `back(...)` for Flux 0.5.4, and eventually think that an error I was getting comes from this:  
```
v = param([0.0, 1.0])
Flux.Tracker.back!(sum(v .^ π))
v.grad ## [NaN, 3.14159]

Flux.Tracker.gradient(x -> x[1]^π + x[2]^π, [0.0, 1.0] )[1] ## [0.0, 3.14159]
```
Using power `e` or `Float64(π)` gives the same NaN. Using 3.14 does not. 
This also avoids the NaN: `Flux.Tracker.back!(v[1]^π + v[2]^π)`.

**Comment by johnnychen94** [comment]
I ran your code here and didn't get `NaN` for `e` or `Float64(π)` in Flux v0.6.1

**Comment by mcabbott** [comment]
OK, thanks for taking a look. I still get the same NaN for `π`, `Float64(π)` and `ℯ`, on both Flux v0.6.1 and on master. But am on Julia 0.7.0, Mac OS. (And on Flux v0.5.4 on Julia 0.6.3.)

**Comment by MikeInnes** [comment]
I can't reproduce this with latest packages on 0.7 or 1.0, on mac – are you still seeing the issue? My guess is it's something upstream with ForwardDiff or similar.

**Comment by mcabbott** [comment]
Just checked & it seems to be fixed now, which is great. Am on Flux 0.7.0 and status says
```
[587475ba] Flux v0.6.6 
[f6369f11] ForwardDiff v0.9.0
```
