### ISSUE TITLE
Flux doesn't preserve Element types

### ISSUE THREAD

**Issue by SimonDanisch** [FluxML/Flux.jl#365]
... and e.g. `Conv` is defined to work on arrays with the same element types.
So beside the performance loss, it also errors if you feed a Conv layer with Float32 arrays!

**Comment by MikeInnes** [comment]
See #225, you have to change the weight types for this to be meaningful. We just need some utilities around that.

**Comment by SimonDanisch** [comment]
Thanks, looks pretty much like a duplicate!
