### ISSUE TITLE
Regression with Flux

### ISSUE THREAD

**Issue by wesleymdurand** [FluxML/Flux.jl#386]
Does Flux have a linear regression output layer, similar to the `LinearRegressionOutput()` from MXNet?  Looking through the documentation, it seems not, but I'm curious if one is in development. Thank you!

**Comment by jekbradbury** [comment]
In general, the answer in Flux-land is "just write the math." I'm not sure what `LinearRegressionOutput` actually does (and the source code and docstring aren't much of a help) but it seems like it's equivalent to some combination of identity, subtraction, and L2 norm.

**Comment by rahulunair** [comment]
There is no specific output layer like LinearRegressionOutput(), but if it is just l2 loss function we could  use:  sum((y .- y_pred).^2) # y being the label.

**Comment by darsnack** [comment]
Yeah I think the right way to do this is define the loss to be the regression loss (MSE).
