### ISSUE TITLE
LSTM sequence processing

### ISSUE THREAD

**Issue by scrcro** [FluxML/Flux.jl#393]
Hello
This a a question not an issue.

Lets say I have defined my LSTM layer like:
`l1= LSTM(20, 5)` and I pass a matrix of size (40, 1). Will the LSTM then consider it as two entries of (20,1) each and process it one by one? I mean will the result of calling `l1` with (40,1) be same as calling it twice with (20,1) each?
Thanks

**Comment by MikeInnes** [comment]
No -- our RNNs currently always accept a single input at a time (aside from the batch dimension, but those are always independent). See also #705.
