### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#402]
We have a basic implementation of this [here](https://github.com/FluxML/Flux.jl/blob/b3a08baf55b898092f112419616c55c7d0fab007/src/tracker/Tracker.jl#L93), but we need to make sure it works with implicit parameters, is documented, etc.

**Comment by darsnack** [comment]
Believe this is addressed in https://github.com/FluxML/Zygote.jl/pull/886.
