### ISSUE TITLE
Layer normalisation does not work for images

### ISSUE THREAD

**Issue by skariel** [FluxML/Flux.jl#406]
The layer uses the `normalise` (stateless) function as defined [here](https://github.com/FluxML/Flux.jl/blob/master/src/layers/stateless.jl#L42-L53). This function calculates mean and std on `dims=1` but for images we need `dims=(1,2,3)` leaving out only the batch dimension. The following function should work:
```julia
function normalise(x)
    d = ndims(x) == 4 ? [1,2,3] : [1,]
    mu = Flux.mean(x, dims=d)
    sd = Flux.std(x, dims=d, mean=mu)
    return (x.-mu)./sd
end
```
also the type of `x` has to change in the function signature to allow for images, currently `x::AbstractVecOrMat` fails for e.g. `rand(Float32, 84,84,1,1)` since it allows only 1d or 2d arrays.

**Comment by johnnychen94** [comment]
I think the Julia way of using images is not to represents images as 4-D array `Array{Float64,4}`, but instead as Array of images, e.g., `Array{Array{Gray,2},1}`

For example,
```julia
julia> Flux.Data.MNIST.images() |> summary
"60000-element Array{Array{ColorTypes.Gray{FixedPointNumbers.Normed{UInt8,8}},2},1}"
```

**Comment by skariel** [comment]
and how do you do channels in general, sometimes you have channels that don't represent images. Say I want to feed a stack of 4 images for Atari reinforcement learning using RGB so I would need 12 channels, how do you do it?

it could be Array{Float32, 4} of size (84,84,12,batchsize) or... ?

**Comment by MikeInnes** [comment]
We do actually end up using 4D arrays for this since it what the convolutions take (and the format is documented more there).

I suggest we just make `dims` an input keyword argument, with `1` being the default.

**Comment by skariel** [comment]
@MikeInnes sounds good, also the type would have to change from `AbstractVecOrMat` to `AbstractArray`
