### ISSUE TITLE
Saving-loading-saving model will cause error using BSON.jl

### ISSUE THREAD

**Issue by xiaodaigh** [FluxML/Flux.jl#432]
I can save a model and load it, but if I try to save it again then it will give error message

```julia
# this is the 2nd attempt; in this attempt I will try use MCTS and gradients
using StatsBase, DataFrames, Flux, JLD2, Plots, JLD2, FileIO, BSON

policy = Flux.Chain(
  x -> reshape(Float64.(x), (4,4,1,1)),
  Conv((2,2), 1=>64, relu),
  x -> meanpool(x, (2,2)),
  x -> reshape(x, (64,)),
  Dense(64, 32, relu),
  Dense(32, 4, relu),
  softmax);

BSON.@save "actor_critic_model1.bson" policy
BSON.@load "actor_critic_model1.bson" policy
BSON.@save "actor_critic_model2.bson" policy # errors
```

**Comment by mleprovost** [comment]
I got the same problem to save and load models with BSON.jl. So I save and load only the coefficients of the NN and it seems to work.

Short example:
`# To save the NN
weights = Tracker.data.(Flux.params(Net));
@save path*"NN.bson" weights

# To reload the NN
@load path*"NN.bson" weights
Flux.loadparams!(Net, weights)`

**Comment by dominusmi** [comment]
Thank you @mleprovost for the suggestion.
This really should be part of the source code.
