### ISSUE TITLE
Allowing users to specify their default data folder

### ISSUE THREAD

**Issue by boathit** [FluxML/Flux.jl#436]
In the current implementation, Flux saves all data in the `Flux/*/deps/` folder. As a result, every time I update `Flux` it will attempt to re-download the data due to the new package management mechanism introduced in Julia 1.0. 

So I think it is more reasonable to allow the users to specify their wanted data folder, just like what PyTorch does
```python
datasets.MNIST(root="../data")
```

**Comment by boathit** [comment]
@johnnychen94 Sounds good to me. Perhaps we could also extend the `Flux.Data` to incorporate more datasets such as `cifar10`, `cifar100`, `omniglot` etc.

**Comment by johnnychen94** [comment]
An alternative to this is to use [MLDatasets](https://github.com/JuliaML/MLDatasets.jl)

Take the example of MNIST, it will be downloaded to `~/.julia/datadeps/MNIST` by default (rather than the `PATH/TO/MLDatasets/deps`), optional `dir` argument can be passed if you want to specify the download location.

**Comment by Paethon** [comment]
I am also not sure if it such a good idea to have MNIST-loading in Flux if there is MLDatasets ...
Any reason this has to be in Flux?

**Comment by MikeInnes** [comment]
Partly historical as at the time, we only had MNIST.jl which wasn't well maintained, and it was hard to have additional dependencies in the model-zoo. It's also useful to load datasets in a format that shows up nicely in notebooks and can immediately be put into a Flux model, but if that's convenient with MLDatasets too I'd be fine with replacing it.

**Comment by johnnychen94** [comment]
@Paethon I think the main reason for this is to provide an out-of-box demo of Flux, e.g., according to [this commit](https://github.com/FluxML/Flux.jl/commit/19f691d3426894215f4d7b0287072a2a2b39c432)
> Let's at least make sure that if our tests break due to server outages
it's our fault.

So if we stick into this principle, then Flux should only contain the minimal dataset to run a demo.

**Comment by cossio** [comment]
Also consider maybe using Artifacts?

**Comment by darsnack** [comment]
With MLDatasets.jl this shouldn't be an issue right?

**Comment by CarloLucibello** [comment]
Yes, MLdatasets allows that
