### ISSUE TITLE
Glorot initialization not correctly implemented

### ISSUE THREAD

**Issue by Paethon** [FluxML/Flux.jl#442]
I think the Glorot initializations are not correctly implemented.

https://github.com/FluxML/Flux.jl/blob/cb773e54c0dbb5337bbd3318acb3ae79c1979b01/src/utils.jl#L4-L5

e.g. `glorot_uniform` should sample from a uniform distribution [-limit, limit] where limit = sqrt(6 / (fan_in + fan_out))

For a dense layer the `sum(dims)` will give the correct result for (fan_in + fan_out), but I think this does not hold in the case of convolutions anymore. I think here it should be `*(dims[1:end-1]...) + dims[end]`

**Comment by Paethon** [comment]
I think the calculation of the `fan_out` is also not correct in the previous comment. Will try to do a correct implementation and do a PR

**Comment by Sleort** [comment]
My back-of-the-envelope calculation agrees with your first observation, i.e. the constant factor of `glorot_uniform` should be sqrt(6) instead of sqrt(24), since a uniform distribution on [-sqrt(3),sqrt(3)] has unit variance. 

Your observation
> For a dense layer the sum(dims) will give the correct result for (fan_in + fan_out), but I think this does not hold in the case of convolutions anymore. I think here it should be *(dims[1:end-1]...) + dims[end]

seems also correct to me. So what do you mean by
> I think the calculation of the fan_out is also not correct in the previous comment.

? For the convolutions, (only) the last dimension of the weights determine the output channels, right?

I can fix this (if my thinking is correct)...

**Comment by Sleort** [comment]
Hmm... But what about `DepthwiseConv` and `ConvTranspose`? Their `weight` matrices seem to be organized differently than `Conv`'s...

**Comment by lihebi** [comment]
Here is the compute_fans function from [tensorflow's init_ops implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/init_ops_v2.py#L714-L738):

```py
def _compute_fans(shape):
  """Computes the number of input and output units for a weight shape.
  Args:
    shape: Integer shape tuple or TF tensor shape.
  Returns:
    A tuple of scalars (fan_in, fan_out).
  """
  if len(shape) < 1:  # Just to avoid errors for constants.
    fan_in = fan_out = 1
  elif len(shape) == 1:
    fan_in = fan_out = shape[0]
  elif len(shape) == 2:
    fan_in = shape[0]
    fan_out = shape[1]
  else:
    # Assuming convolution kernels (2D, 3D, or more).
    # kernel shape: (..., input_depth, depth)
    receptive_field_size = 1.
    for dim in shape[:-2]:
      receptive_field_size *= dim
    fan_in = shape[-2] * receptive_field_size
    fan_out = shape[-1] * receptive_field_size
  return fan_in, fan_out
```

**Comment by Sleort** [comment]
Sure, but I think the issue is that `glorot_uniform` (or `nfan`) depends on the type of the layer (`Dense`, `Conv`, `ConvTranspose`, etc.), hence `glorot_uniform` (or, in general, the weight initialization) has to have a layer type argument in addition to `dims...`. But that requires a breaking API change...(?)

**Comment by lihebi** [comment]
There are not a lot of different types. For dense layer, it is `dimIn+dimOut`;  Conv and ConvT should be the same?

```julia
nfan() = 2
nfan(a) = 2 * a
nfan(a,b) = a + b
# FIXME might need to specify size(dims)>=3
nfan(dims...) = prod(dims[1:end-2]) * sum(dims[end-1:end])
```
Also, for one of your previous comment:

> sqrt(6) instead of sqrt(24)

I think the current `sqrt(24)` is correct, which is `2 * sqrt(6)`, and it is shifted by `.- 0.5` to be centered on 0. As a reference, the glorot uniform is uniform within `[-limit, limit]` where limit is `sqrt(6 / (fan_in + fan_out))` [[keras](https://keras.rstudio.com/reference/initializer_glorot_uniform.html)] [[paper](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf)]

**Comment by lihebi** [comment]
I'm also copying the [tensorflow implementation of `_compute_fans`](https://github.com/tensorflow/tensorflow/blob/6e9af41e346e487abd04c3c4c0cda1a91af79b36/tensorflow/python/ops/init_ops_v2.py#L714-L738) here for convenience.

```py
def _compute_fans(shape):
  """Computes the number of input and output units for a weight shape.
  Args:
    shape: Integer shape tuple or TF tensor shape.
  Returns:
    A tuple of scalars (fan_in, fan_out).
  """
  if len(shape) < 1:  # Just to avoid errors for constants.
    fan_in = fan_out = 1
  elif len(shape) == 1:
    fan_in = fan_out = shape[0]
  elif len(shape) == 2:
    fan_in = shape[0]
    fan_out = shape[1]
  else:
    # Assuming convolution kernels (2D, 3D, or more).
    # kernel shape: (..., input_depth, depth)
    receptive_field_size = 1.
    for dim in shape[:-2]:
      receptive_field_size *= dim
    fan_in = shape[-2] * receptive_field_size
    fan_out = shape[-1] * receptive_field_size
  return fan_in, fan_out
```

which is [used here to compute glorot_uniform](https://github.com/tensorflow/tensorflow/blob/6e9af41e346e487abd04c3c4c0cda1a91af79b36/tensorflow/python/ops/init_ops.py#L501-L519):

```py
    fan_in, fan_out = _compute_fans(scale_shape)
    if self.mode == "fan_in":
      scale /= max(1., fan_in)
    elif self.mode == "fan_out":
      scale /= max(1., fan_out)
    else:
      scale /= max(1., (fan_in + fan_out) / 2.)

    ......

      limit = math.sqrt(3.0 * scale)
      return random_ops.random_uniform(
          shape, -limit, limit, dtype, seed=self.seed)
```

**Comment by Sleort** [comment]
> There are not a lot of different types. For dense layer, it is `dimIn+dimOut`; Conv and ConvT should be the same?

Yeah, (though `DepthwiseConv` is slightly different again, I think,) but my point is that the weight initialization function `init ∈ (glorot_uniform, glorot_normal, ...)` has to change from `init(dims...)` to something like `init(::Conv, dims...)`, `init(::Dense, dims...)`, etc. (Or another design pattern passing on the necessary information). I.e. some API design decisions have to be made...

> I think the current `sqrt(24)` is correct, which is `2 * sqrt(6)`, and it is shifted by `.- 0.5` to be centered on 0. As a reference, the glorot uniform is uniform within `[-limit, limit]` where limit is `sqrt(6 / (fan_in + fan_out))` [[keras](https://keras.rstudio.com/reference/initializer_glorot_uniform.html)] [[paper](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf)]

You are of course right. I will immediately complain to my envelope supplier! :grimacing:

**Comment by lihebi** [comment]
> weight initialization function init ∈ (glorot_uniform, glorot_normal, ...) has to change from init(dims...) to something like init(::Conv, dims...), init(::Dense, dims...)

No. `init` only takes `dims`. It is used like

```julia
glorot_uniform(100,10)   # for dense
glorot_uniform(3,3,1,16) # for conv
```

and you can tell which kind of layer by checking `size(dims)`.

**Comment by Sleort** [comment]
Isn't it a bad design choice to base the dispatch on something "arbitrary" like the internal storage pattern of the weight array? I mean, what if someone introduces a different/new kind of layer that is neither `Dense` nor `Conv`?

**Comment by lihebi** [comment]
> what if someone introduces a different/new kind of layer

That's a valid point, ideally `glorot_uniform` should take a kwarg with a default implementation:

```julia
nfan(dims) = ...
glorot_uniform(dims...; nfan=nfan) = ...
```

and a new layer can pass in it's own fan-in fan-out computation function if necessary.

But I don't think we need to worry about this now, as that's exactly how init ops in tensorflow are implemented, and it seems to work fine all these years.
