### ISSUE TITLE
Concatenate transposed array

### ISSUE THREAD

**Issue by merckxiaan** [FluxML/Flux.jl#449]
When using Flux, I get a StackOverflowError when I try to concatenate 2 arrays, one of which is transposed.
```julia
julia> using Flux

julia> [rand(2, 3) rand(3, 2)']
ERROR: StackOverflowError:
```

**Comment by johnnychen94** [comment]
duplicate of https://github.com/FluxML/Flux.jl/issues/378

Sorry that It’s now a little tricky for me to fix this.

**Comment by johnnychen94** [comment]
duplicate of https://github.com/FluxML/Flux.jl/issues/378 

@MikeInnes This's a bug introduced by Flux, shall we make a temporary patch for this, if not so easy to fixed?

**Comment by merckxiaan** [comment]
Sorry, I hadn't seen that issue.
