### ISSUE TITLE
Slurping and splatting unnecessary in onehotbatch?

### ISSUE THREAD

**Issue by harryscholes** [FluxML/Flux.jl#453]
https://github.com/FluxML/Flux.jl/blob/cb773e54c0dbb5337bbd3318acb3ae79c1979b01/src/onehot.jl#L54-L55

I'm not sure what it would mean to provide multiple `unk`s, but doing so gives a `MethodError` 
```julia
julia> using Flux: onehotbatch

julia> onehotbatch(1:4, 1:3, 3, 4)
ERROR: MethodError: no method matching onehot(::Int64, ::UnitRange{Int64}, ::Int64, ::Int64)
```

There is, possibly, a similar problem in `onecold`:

https://github.com/FluxML/Flux.jl/blob/cb773e54c0dbb5337bbd3318acb3ae79c1979b01/src/onehot.jl#L59-L60

**Comment by MikeInnes** [comment]
This is just a way to make `unk` optional; you can provide one or zero `unk` arguments and it works. You could change it to explicitly disallow more than one, but it's a little more duplication.

**Comment by harryscholes** [comment]
Ah I see. Nice trick!

For reference If anyone's ever interested:

```julia
julia> f(x, y) = true;

julia> f(x) = false;

julia> g(x, y...) = f(x, y...);

julia> g(1)
false

julia> g(1, 1)
true

julia> g(1, 1, 1)
ERROR: MethodError: no method matching f(::Int64, ::Int64, ::Int64)
Closest candidates are:
  f(::Any, ::Any) at REPL[1]:1
  f(::Any) at REPL[2]:1
Stacktrace:
 [1] g(::Int64, ::Int64, ::Vararg{Int64,N} where N) at ./REPL[3]:1
 [2] top-level scope at none:0
```
