### ISSUE TITLE
Export `data` as well?

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#457]
https://github.com/FluxML/Flux.jl/blob/bbccdb3eec62acd3c972441080fcec673fcf4618/src/tracker/Tracker.jl#L16

I notice the custom gradient part's example (http://fluxml.ai/Flux.jl/stable/internals/tracker.html#Custom-Gradients-1) directly use `data` but didn't import it. This can be confusing, and I guess it would be convenient to export it directly?

**Comment by johnnychen94** [comment]
For Flux-only users it might be convenient, but export it would introduce some misunderstanding of the function. 

For example, what does `data` mean in more general codes? To explain what `data` mean you then need to explain what a `Tracker` has...

Perhaps what we need is not `export data`, but a more useful tool, e.g., `getdata(c::Chain, idxs...)`(Roughly speaking)

**Comment by Roger-luo** [comment]
I mean to export the data in Tracker, rather than Flux. And you can always use import to solve the problem. It's not a big deal. But this is causing the example in doc to have error.

**Comment by Roger-luo** [comment]
And I don't see any difference by changing a function name. This does not solve name conflict.

**Comment by MikeInnes** [comment]
I think we should probably just fix the docs here. `data` is a bit to generic to export.
