### ISSUE TITLE
Is view implemented?

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#458]
It looks not, I don't get the correct result

```julia
julia> a = param(rand(5, 5));

julia> c = view(a, 1:2, 1:2);

julia> c
2×2 view(::TrackedArray{…,Array{Float64,2}}, 1:2, 1:2) with eltype Flux.Tracker.TrackedReal{Float64}:
 0.433861 (tracked)   0.320137 (tracked)
 0.0861302 (tracked)  0.418549 (tracked)

julia> Tracker.back!(c, ones(2, 2))

julia> a.grad
5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
```

But I don't get any errors...

**Comment by MikeInnes** [comment]
This is happening because you have a view of a tracked array, rather than a tracked view. Easy to fix by adding a gradient for `view`. Not sure why you don't get an error here, but that would be better also.

**Comment by Roger-luo** [comment]
I think this is because `TrackedArray` implements the `Array` Interface as an `AbstractArray`, and `view` is implemented for `AbstractArray`, thus, you can `view` a `TrackedArray`, but by default, this returns a `SubArray` rather than a `TrackedArray` of `SubArray`.
