### ISSUE TITLE
Lots of functions no longer defined on master

### ISSUE THREAD

**Issue by baggepinnen** [FluxML/Flux.jl#46]
On current master, the following functions are no longer defined
- `back!` seems to have moved to FluxCore but is not exported
- `onehot` the file containing the function seems not to be included 
- `tobatch

**Comment by ExpandingMan** [comment]
For a while I was running into a `back!` not defined error.  Then it went away for a while.  Now it's back again.

**Comment by ExpandingMan** [comment]
I looked into this again today and I am still getting this error with tensorflow.

**Comment by MikeInnes** [comment]
On the latest release, the examples should all work out of the box. I tried to make sure all of Flux's exports were fairly obvious; things like `back!` are quite generic and better off explicitly imported.
