### ISSUE TITLE
Shouldn't gradcheck compares Jacobian?

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#462]
https://github.com/FluxML/Flux.jl/blob/bbccdb3eec62acd3c972441080fcec673fcf4618/test/tracker.jl#L11

Why it is `sum` and use a `sin` here?

**Comment by MikeInnes** [comment]
`sum` is equivalent to taking the Jacobian-vector product with `[1, 1, 1, ...]`. Really it's just that numerically taking a gradient is easier than a jacobian, and is sufficient for most purposes.

The `sin` is for things like `softmax` where doing a normal `sum` will erase the gradients. Again, not overly principled but it gets the job done. Other suggestions are definitely welcome though.

**Comment by ToucheSir** [comment]
I assume this no longer applies in a post-Tracker world?

**Comment by Roger-luo** [comment]
This should be resolved by FinteDifference and ChainRuleTestUtils now
