### ISSUE TITLE
Binding Flux.Optimise.call does not exist.

### ISSUE THREAD

**Issue by mcabbott** [FluxML/Flux.jl#484]
I'm getting the following error: 
```julia
ERROR: UndefVarError: call not defined
Stacktrace:
 [1] (::getfield(Flux.Optimise, Symbol("##3#4")){Array{Any,1}})() at /Users/me/.julia/packages/Flux/LLT8V/src/optimise/train.jl:15
```
I'm struggling to cook up a quick MWE, but it must be to do with a callback I pass to `train!`; 
the line `runall(fs::AbstractVector) = () -> foreach(call, fs)` seems to be the only place `call` appears right now -- as per the title this seems to have been deleted.

**Comment by dhairyagandhi96** [comment]
I believe this happens with multiple callbacks

```
fs = [() -> (), () -> ()]
cbs = runall(fs)
cbs() # errors
```
