### ISSUE TITLE
Tied Weights

### ISSUE THREAD

**Issue by jtmatamalas** [FluxML/Flux.jl#488]
Hi guys,

I'm trying to build an autoencoder with tied weights between the encoder and the decoder. The model is easy to encode, just transposing the weights of the encoder layers on the decoder layers. Here's an example with just one layer for the encoder and one for the decoder:

```
data = [rand(10,2), rand(10,2)]

encoder = Dense(10, 5, relu)
decoder = Dense(transpose(encoder.W), zeros(Float64, 10), relu)

m = Chain(encoder, decoder)

loss(x) = mse(m(x), x)
opt = ADAM(params(m))

evalcb = throttle(() -> @show(loss(data[1])), 5)

Flux.train!(loss, zip(data), opt, cb = evalcb)
```
This model works quite well when I run it on CPU. However, when I'm trying to execute it on GPU:
```
data = gpu.([rand(10,2), rand(10,2)])

encoder = Dense(10, 5, relu) |> gpu
decoder = Dense(transpose(encoder.W), gpu(zeros(Float64, 10)), relu)

m = Chain(encoder, decoder)

loss(x) = mse(m(x), x)
opt = ADAM(params(m))

evalcb = throttle(() -> @show(loss(data[1])), 5)

Flux.train!(loss, zip(data), opt, cb = evalcb)
```
I got a pretty ugly error message, see below. I'm pretty sure that there is something wrong with the broadcasting over the transposed array on the GPU.

Do you have any clue about what's happening?

```
> ERROR: GPU compilation of #25(CuArrays.CuKernelState, CUDAnative.CuDeviceArray{Float32,2,CUDAnative.AS.Global}, Base.Broadcast.Broadcasted{Nothing,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},typeof(+),Tuple{Base.Broadcast.Extruded{CUDAnative.CuDeviceArray{Float32,2,CUDAnative.AS.Global},Tuple{Bool,Bool},Tuple{Int64,Int64}},Base.Broadcast.Extruded{Base.ReshapedArray{Float32,2,LinearAlgebra.Adjoint{Float32,CuArray{Float32,2}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}},Tuple{Bool,Bool},Tuple{Int64,Int64}}}}) failed
> KernelError: passing and using non-bitstype argument
```

**Comment by ckneale-ccri** [comment]
This problem should probably be restated more plainly as a transpose issue rather then one specific to autoencoders. I also have several models that do just fine on CPU, but when passed to the GPU they fail to backprop. The culprit is again transposes and matrix multiplications/inner products.

**Comment by CarloLucibello** [comment]
This is fixed now,
```julia
x = rand(10,2) |> gpu
encoder = Dense(10, 5, relu)
decoder = Dense(transpose(encoder.W), zeros(Float32, 10), relu) 
m = Chain(encoder, decoder) |> gpu
gradient(() -> Flux.Losses.mse(m(x), x), Flux.params(m))
```
works fine
