### ISSUE TITLE
Documentation Pitfall: Saving Model weights does not preserve untracked values

### ISSUE THREAD

**Issue by CarpeNecopinum** [FluxML/Flux.jl#492]
In [saving.md](https://github.com/FluxML/Flux.jl/blob/master/docs/src/saving.md) it is suggested to use `params` to extract the weights from a model and then to use BSON to save it.

This breaks when e.g. a `BatchNorm` layer is present, because it has parameters that are updated as part of the training procedure, but which are not picked up by `params` (which makes sense, since they're not parameters to the optimization directly).

This is a pitfall that should probably be mentioned alongside the suggestion in the docs.

**Comment by CarpeNecopinum** [comment]
Would be interesting to have a variant on the technique in saving.md that works with BatchNorm layers, too, at some point in the future.

Storing the whole model, rather than just the weights, increases the file size significantly (from ~300MB to ~600MB for a model I'm working with).

Or is that increase due to tracking-related information with an easy way to omit saving that?

**Comment by CarloLucibello** [comment]
this has been fixed
