### ISSUE TITLE
Throw error for nested tracked type?

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#495]
I was wondering if we should throw an error for nested tracked type? Or how to make this work?

```Julia
X = [param(rand(2)) for i in 1:4]
out = [prod(cosh, z) for z in X]
W = param(rand(2, 4))
z = sum(W * out)
Tracker.back!(z)
```

**Comment by MikeInnes** [comment]
Yeah, this should either error or work. We can add a check to the TrackedArray constructor.

**Comment by Roger-luo** [comment]
You mean check if the input is tracked then throw an error?

**Comment by MikeInnes** [comment]
Yeah exactly. It should be possible to write it such that the check gets elided in the common case.
