### ISSUE TITLE
Should the Manifest.toml be checked-in to the project?

### ISSUE THREAD

**Issue by sambitdash** [FluxML/Flux.jl#500]
This creates tight dependency and makes the module unusable with other modules. 

@MikeInnes please review if there is an absolute environment dependence mandated by the Flux library. This was a very recent introduction into the project.

**Comment by vchuravy** [comment]
I am not sure what you mean. The `Manifest.toml` is ignored when you import Flux from a different project, so it does not introduce an "absolute environment dependence".

You can activate the `Flux` environment and instantiate the environment, but again that is a very different act from using Flux in a different project.

**Comment by vchuravy** [comment]
I am not sure what you mean. The `Manifest.toml` is ignored when you import Flux from a different project, so it does not introduce an "absolute environment dependence".

You can activate the `Flux` environment and instantiate the environment, but again that is a very different act from using Flux in a different project.

**Comment by sambitdash** [comment]
@vchuravy, closing this bug as I guess I was in the same folder as the Flux folder and had not instantiated the project when I tried `test Flux`. The case seems remote.
