### ISSUE TITLE
CPU conversion doesn't work

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#508]
https://github.com/FluxML/Flux.jl/blob/43c5f90d934a911f9e1828aaec01db78b668254e/src/treelike.jl#L63

This doesn't work due to

```
x = CuArray(rand(2, 2))
adapt(Array, x)
```

will call

```
julia> @which adapt(Array, x)
adapt(to, x) in Adapt at /home/rluo/.julia/packages/Adapt/0qaBO/src/Adapt.jl:6
```

**Comment by Roger-luo** [comment]
I guess we should define some fallback method for `adapt_structure`, which allow the `adapt` fallback to conversion methods between "primitive" types.

**Comment by maleadt** [comment]
Thanks, didn't know `adapt` was used like that.
Even though there's no current tests, can't hurt to add some, eg. an `Adapt` testset in `test/base.jl`.

**Comment by KristofferC** [comment]
Can likely be closed (fixed by https://github.com/JuliaGPU/CuArrays.jl/pull/217).
