### ISSUE TITLE
onehot.md in docs should not have subtitle "Batches"

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#510]
Given that [Building a Language and Compiler for Machine Learning](https://julialang.org/blog/2018/12/ml-language-compiler) has a section on Automatic Batching it is especially confusing that searching the docs for "batch" returns the section on hot/cold matrix encodings. 

I think this section should be renamed to avoid "batch" confusion. Additionally, is automatic batching ready enough to be in the docs?

**Comment by darsnack** [comment]
As discussed during triage, I will submit a PR to fix this.
