### ISSUE TITLE
Repo tagged with the "the-human-brian" (potential typo)

### ISSUE THREAD

**Issue by eamartin** [FluxML/Flux.jl#512]
I'm unsure if the tag is supposed to be "brain" or is intentionally "brian" due to an inside joke or something.

If no one is particularly attached to "the-human-brian", then fixing the typo will add a little polish to the project (in a highly visible place). I would submit a PR, but I'm pretty sure the repo tags are not tracked in git.

**Comment by chriscoey** [comment]
I noticed this too and had a little chuckle

**Comment by datnamer** [comment]
A chuckle from here as well.

**Comment by kool7d** [comment]
i thought it was a joke

**Comment by TSGut** [comment]
I chuckled as well but it should probably be fixed.

**Comment by darsnack** [comment]
@DhairyaLGandhi can you fix this and close the issue?

**Comment by darsnack** [comment]
@CarloLucibello @DhairyaLGandhi can someone change this so we can close?

**Comment by DhairyaLGandhi** [comment]
It was a pun, but I've changed it
