### ISSUE TITLE
Concatenating Transposed Matrix Multiplications Breaks GPU

### ISSUE THREAD

**Issue by ckneale-ccri** [FluxML/Flux.jl#536]
Not really sure what's up here, can't say whether it's an easy fix or a hard one. It's showed up a few times in some of the models I've tried to build. This one is pretty close to a deal breaker for me, if there's anyway I can help please let me know.

There is obviously no issues with the forward pass, it's purely in the call to back! Below I have written a minimal example that represents this issue.

w1 = param(cu(rand(3, 1))) 
w2 = param(cu(rand(1, 3)))
function m(x)
    a = w1' * x
    b = w2  * x
    hcat(a,b)
end

sum(m( cu( rand(3,3) ) )) |> Flux.back!

**Comment by dhairyagandhi96** [comment]
Moving the final array over to the GPU should work as a workaround. 

For now, the `ReshapedArray` needs to be made GPU friendly

**Comment by ckneale-ccri** [comment]
Thanks @dhairyagandhi96 and @merckxiaan I will try that; seems like a simple fix. Doesn't sound like its the most efficient approach but, for now that works for me (provided it doesn't break the graph). I'll report back with any issues, but I still think we should get the GPU training to have the same functionality as the CPU, especially with this type of operation. I'm sure it looks ugly under the hood.

**Comment by dhairyagandhi96** [comment]
Per [CuArrays.jl](https://github.com/JuliaGPU/CuArrays.jl)'s README, the way to perform the transpose on `CuArray`s is to use `permutedims`. So a
 ```julia
tmp = permutedims(w1, [2,1])
a = tmp * x
```
should do the trick.

**Comment by MikeInnes** [comment]
Instead of `gpu(collect(w1'))` you can also do `CuArray(w1')`, which won't move the data off the GPU and back on again. It would be great to have the obvious thing working here though.

It might be as simple as adding `ReshapedArray` to adapt. Happy to help anyone implement that.

**Comment by ckneale-ccri** [comment]
@MikeInnes - even better, I'll update my methods to use that, bet I'll see a performance increase. Thanks again everyone for thinking this through. Seems kind of trivial but this operation pops up a lot for me in my day to day.

**Comment by MikeInnes** [comment]
Should be fixed, but let us know if you have further issues.
