### ISSUE TITLE
Docs for train! mismatch the actual method signature

### ISSUE THREAD

**Issue by KristofferC** [FluxML/Flux.jl#547]
```jl
"""
    train!(model, loss, data, opt)
For each datapoint `d` in `data` computes the gradient of `loss(d...)` through
....
"""
function train!(loss, ps, data, opt; cb = () -> ())
```

So the docstring for `train!` doesn't match the actual declaration. The docs also say to return `:stop` in `cb` if one wants to stop the training but this is deprecated in favour of `Flux.stop()`.

**Comment by dhairyagandhi96** [comment]
Ref: https://github.com/FluxML/Flux.jl/pull/493/commits/7484c54f035f9e6f81e880004694670273675010

**Comment by MikeInnes** [comment]
Ok, closing and we'll merge that today.
