### ISSUE TITLE
Test Flux on Julia master causes runaway consumption of memory

### ISSUE THREAD

**Issue by colbec** [FluxML/Flux.jl#549]
Here is my versioninfo():
```
Julia Version 1.2.0-DEV.141
Commit 0df9b8355b (2019-01-10 02:19 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

  [587475ba] Flux v0.6.10
  [2913bbd2] StatsBase v0.27.0
```

test Flux works correctly with the standard binary 1.0.3, but with Julia master Linux system monitor shows memory rapidly consumed and finally system cannot be recovered with ctrl c or ctrl d.

Edit:
Testing a few simple examples from the model zoo produces results perfectly, so it must be one test which is tripping up the system. Unfortunately it fails silently so there is nothing to say which test is being run at the time.

**Comment by MikeInnes** [comment]
Thanks for reporting! Fixed on master.
