### ISSUE TITLE
convert from Float64 to TrackedReal

### ISSUE THREAD

**Issue by mohamed82008** [FluxML/Flux.jl#574]
~~It seems that #256 is biting again in~~ https://github.com/TuringLang/TuringTutorials/issues/20. MWE:
```julia
using Flux.Tracker
using Distributions
MvNormal([param(1.0)], 1.0)
```
There is a conversion error caused by a type promotion and conversion in https://github.com/JuliaStats/Distributions.jl/blob/master/src/multivariate/mvnormal.jl#L220. I find it a bit weird that `promote(param(1.0), 1.0)` works but `promote_eltype(param(1.0), 1.0).((param(1.0), 1.0))` fails. Any thoughts on how to fix this? The only 3 I can think of are to: 1) define the `convert`, 2) modify the constructors in `Distributions` to be `Flux`-friendly, or 3) use type piracy in Turing. ~~I couldn't really find the reason in #256 for why the `convert` function is not defined. May someone please explain?~~ This is not the same as #256; I got confused.

**Comment by MikeInnes** [comment]
Completely fine to add the `convert` here. At one point Julia automatically forwarded `T(x)` to `convert(T, x)`, but that got turned off for 1.0 I think.

**Comment by mohamed82008** [comment]
Awesome thanks!
