### ISSUE TITLE
Export apply!, etc

### ISSUE THREAD

**Issue by ckneale-ccri** [FluxML/Flux.jl#588]
This isn't a major concern, but would it be damaging to export the apply! functions for the optimizers? 

I find it pretty useful to have access to them when I write custom training methods, etc. Otherwise I have to copy-paste them into my code-base. Being able to call Flux.apply!(...) would be pretty snappy.

**Comment by darsnack** [comment]
You can call `Optimise.apply!` directly, but we prefer not to export generically named functions. Probably you want to call `Optimise.update!` these days and not `apply!` btw. Re-open if you want to but I'm going to close this for now.
