### ISSUE TITLE
Documentation for `Over` a little unclear

### ISSUE THREAD

**Issue by ssfrr** [FluxML/Flux.jl#59]
In the [Sequences](https://github.com/FluxML/Flux.jl/blob/b49643e7d4d1c7bdcd77bf9e1cb698e102dddf81/docs/src/models/recurrence.md#sequences) section of the Recurrent docs it says:

> You can get this behaviour more generally with the Over wrapper.
> ```
> m = Over(Dense(10,5))
> m(seq) # returns a new Seq of length 10
> ```

But I'm not super sure what that's equivalent to. At first I thought it might be saying that it's the same as the last `m` model above, `m = Flux.Recur(rnn, h)`, but now I'm thinking that it takes a model that's designed for 1 timestep and makes it `Seq`-aware, but then I might expect that all the built-in layers in Flux would be `Seq`-aware by default, and you'd only need to use `Over` if you defined your own layer function.

Up to that point the docs do a great job of adding new features as equivalent sugar for things we've already seen, but that one felt like a bit of a jump.

**Comment by MikeInnes** [comment]
Yeah, the second interpretation is correct; only `Recur` is Seq-aware.

I thought about this some more and decided to get rid of this entirely. It's a lot nicer to just treat seqs as vectors and call `m.(seq)` in all cases (I updated the docs as well), so hopefully that's clearer too.

**Comment by ssfrr** [comment]
:+1:
