### ISSUE TITLE
Regression: Ambiguous *  between Transpose and TrackedArray

### ISSUE THREAD

**Issue by cshenton** [FluxML/Flux.jl#605]
The following causes Flux to error during backprop. Julia 1.1

This error occurs on 7.2, but not on 6.8:

```julia
using Flux
using Flux.Tracker: gradient
using LinearAlgebra

x = param(randn(5, 5))
z = param(randn(5))

loss(x, z) = transpose(z) * x * transpose(x) * z
gradient(loss, x, z) # amibguous * occurs here
```

This is one of a handful of regressions I've noticed since upgrading to 7, though I've yet to pin down examples for the others.

**Comment by dhairyagandhi96** [comment]
#599 Should help fix this particular MWE.

It'd be super to open issues for any problems you encounter. Thanks!
