### ISSUE TITLE
Method overwrite warning when precompiling

### ISSUE THREAD

**Issue by KristofferC** [FluxML/Flux.jl#618]
https://travis-ci.org/FluxML/Flux.jl/jobs/491652217#L476

These two methods:

https://github.com/FluxML/Flux.jl/blob/f17a5acd2bdf1c41c7574d1319522ac4a1ce6218/src/layers/stateless.jl#L47-L56

indeed look like they both match for `normalise(::AbstractArray)`

**Comment by MikeInnes** [comment]
Yeah, we should just remove the `=1` so that `dims` isn't optional.
