### ISSUE TITLE
elementwise assign

### ISSUE THREAD

**Issue by hughsalimbeni** [FluxML/Flux.jl#631]
Is elementwise assign supported with params? I get an error in the following:

```julia
x = param(1.)
a = zeros(1)
a[1] = x  # fails
```

**Comment by chengchingwen** [comment]
There is no derivative for assignment. If you need a param with different value, you should create a new one with the initial value you want.

**Comment by hughsalimbeni** [comment]
Ah ok thanks.

**Comment by aterenin** [comment]
The problem with the above is that the types don't match, because you're trying to assign a `TrackedReal{Float64}` to a `Float64`. The code below fixes the issue.

```
x = param(1.)
a = [Flux.Tracker.TrackedReal{Float64}(0.0)]

Flux.gradient(() -> begin 
  a[1] = x^2
  a[1]
end, params(x))[x]
```
