### ISSUE TITLE
Training with concurrent testing

### ISSUE THREAD

**Issue by datnamer** [FluxML/Flux.jl#632]
This is how swift is thinking about doing it: https://github.com/tensorflow/swift/pull/115/commits/b3232ec9659be3257f535ed201a8f0356964908b

**Comment by jekbradbury** [comment]
This isn’t necessary for Flux; like in PyTorch and other Python frameworks, Flux models are reference types and it’s possible to make a shallow model copy for inference. Swift is a rather special bird in having the default case for composite types be value semantics (with copy-on-write as an optimization); I’m honestly not sure if we’ll be able to stick with it forever in S4TF.
