### ISSUE TITLE
Something odd in the behaviour of truncate!

### ISSUE THREAD

**Issue by mkschleg** [FluxML/Flux.jl#636]
I've been playing with the recurrent layers in Flux for the past day and have been noticing some odd behaviour. Some context, I actively do research in ML/RL and need to finely tune the truncation levels of recurrent models, the best way to do this is through the truncate! function (I want to preserve state, but truncate gradients). 

Here is a simple example of things failing.

```julia

function test_recurr()

    model = Chain(
        Flux.RNN(1, 1, Flux.identity),
        Dense(1,1,Flux.identity; initW = ones))

    y = [1.0]
    x_seq = [[0.1], [0.2], [0.3], [0.4], [0.5]]

    loss(_x, _y) = Flux.mse(model.(_x)[end], _y)

    ps = params(model)
    println(ps)
    
    println("reset")

    grads = Tracker.gradient(() -> loss(x_seq, y), ps)
    println(grads[collect(ps)[4]])
    Flux.reset!(model)
    grads = Tracker.gradient(() -> loss(x_seq, y), ps)
    println(grads[collect(ps)[4]])
    Flux.reset!(model)
    println(grads[collect(ps)[4]])

    Flux.reset!(model)

    println("Truncate")

    grads = Tracker.gradient(() -> loss(x_seq, y), ps)
    println(grads[collect(ps)[4]])
    Flux.truncate!(model)
    grads = Tracker.gradient(() -> loss(x_seq, y), ps)
    println(grads[collect(ps)[4]])
    Flux.truncate!(model)
    println(grads[collect(ps)[4]])

    # Flux.reset!(model)

    println("reset")
    grads = Tracker.gradient(() -> loss(x_seq, y), ps)
    println(grads[collect(ps)[4]])
    Flux.reset!(model)
    grads = Tracker.gradient(() -> loss(x_seq, y), ps)
    println(grads[collect(ps)[4]])
    Flux.reset!(model)
    println(grads[collect(ps)[4]])

end

```

The expected output should be equal gradients for the first 3 prints, changing gradients for the middle 3 prints, and equal gradients for the last 3 prints. What I actually see

```
Chain(Recur(RNNCell(1, 1)), Dense(1, 1))
Params([Float32[-1.15701] (tracked), Float32[-0.811071] (tracked), Float32[-0.489136] (tracked), Float32[0.0] (tracked), [1.0] (tracked), Float32[0.0] (tracked)])
reset
[1.20948] (tracked)
[1.20948] (tracked)
[1.20948] (tracked)
Truncate
[1.20948] (tracked)
Float32[0.0]
Float32[0.0]
reset
Float32[0.0]
[1.20948] (tracked)
[1.20948] (tracked)
```

What is unexpected is the 3 zeros in a row. It seems the truncate is not only truncating the gradients, but also making the hidden state not a tracked parameter. My guess is it has to do with the call to `_tracker(x) = Tracker.data(x)`, but when I dug further into the source I can only find `data(x) = x`. I'm probably not looking in the correct spot.

I am willing to make a pull request, but some advice on where the issue actually lies from someone who is more familiar with the code base would be very useful.

As an aside: Flux is amazing for my research as I can write custom layers in Julia and get equal speed, I really need this issue fixed though.

**Comment by mkschleg** [comment]
I've found another version of the data function for tracked reals `data(x::TrackedReal) = x.data`. I'm not sure this is the correct function for the truncate function, but one thing we can hack in is add a param around the data to create a new tracked variable. This is not a great solution as it continuously changes the graph, and I assume will effect some of the nice optimizations going on under the hood.

**Comment by MikeInnes** [comment]
The `data` call does indeed drop tracking; that's intentional since dropping the graph is how we truncate gradients. It shouldn't set the state to `0` unless it was `0` already, though. It would be good to better understand the issue, if you can narrow it down to a smaller example that would help a lot.

**Comment by mkschleg** [comment]
This could just be a difference in how I am interpreting the truncate! function.
Take this example:
```Julia
using Flux
model = RNN(1, 1)
state_seq = [[0.1*i] for i in 1:9]
model.(state_seq)
model.state # Returns a tracked array of length 1.
truncate!(model)
model.state # Returns an array of length 1 (not tracked). I would expect it to be a fresh tracked variable.
```

What  I thought `truncate!` would do is reset the tracking information (i.e. truncate the gradients) but keep the hidden state fixed. And then you would have a clean tracked variable with no sequence data.

If truncate just resets the tracking information, then you can continue using the RNN in an online manner and accumulate gradients again.

**Comment by MikeInnes** [comment]
That is what it's doing – it's just that if you're going to through out the history, there's no reason for it to be a `TrackedArray` any more. You can just strip away the tracking and it'll behave the same.

**Comment by mkschleg** [comment]
Hm. Ok. I think part of the issue is that I'm outside of the typical use case. I would want it to be tracking still so to cut off the bptt, but keep track of gradients for another \tau timesteps (without resetting the hidden state).

 It seems like the behaviour is what you are expecting, so I'll close the issue.
