### ISSUE TITLE
RNN layer to skip certain time steps (like `Masking` layer in keras)

### ISSUE THREAD

**Issue by kota7** [FluxML/Flux.jl#644]
Is there a way to let an RNN layer to skip certain time steps?  Possible use cases will be

* Sequences contain missing values, which should be skipped 
* Sequences within a batch have different length, so want to skip time steps after the lengths

In keras, this is achieved by inserting `Masking` layer before recurrent layers.

Is there a way to do the same on Flux?

**Comment by MikeInnes** [comment]
You can just write the for loop and not call the RNN when you encounter a missing value. I could be misunderstanding what you need here, but if so we might need more description of what `Masking` would do.

**Comment by darsnack** [comment]
I think that something like `Masking` is not required with our vector-based model for recurrence. Probably we can close this.

**Comment by CarloLucibello** [comment]
How does triage work?

**Comment by darsnack** [comment]
When we have the community call (every other Tuesday @ 12PM EST), we set aside some time to go through the issues in the triage. Based on the discussion we will either move it to a high/low priority fix, needs input from maintainers, or should be closed. The possible outcomes are a PR submitted to fix, or we bring it up to the maintainers. Honestly, these issues will be the first real test of the system, so I don't know exactly how we'll do the second part. Probably, I will take the meeting notes and make comments on the issues that need maintainer input and ping someone to make the final decision.

The main idea is to get input from the community and use some extra bandwidth to talk through stale issues.

**Comment by ToucheSir** [comment]
From the triage meeting today, we concluded that keras-style masking is already supported as mentioned by just skipping certain time steps. However, there remains the question of how to mask only certain features in a given timestep (which AFAICT tf/keras does not support), and as such this issue can be refocused on that instead.

**Comment by CarloLucibello** [comment]
closing as this is something very specific and use case dependent, should be handled by the user.
