### ISSUE TITLE
ForwardDiff derivative on chain gives stackoverflow

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#645]
Taking the ForwardDiff derivative through a chain of dense layers gives a stackoverflow:

```
F = Chain(t->[t],Dense(1,10,σ),Dense(10,10,σ),Dense(10,10))
Ft = mapleaves(Flux.data,F)

ForwardDiff.derivative(F,1.) # stackoverflow
ForwardDiff.derivative(Ft,1.) # Also stackoverflow
```

**Comment by MikeInnes** [comment]
We can fix this, but just curious, why do you need it?

**Comment by jessebett** [comment]
:/ Just realized I never followed up on this.

**Comment by jessebett** [comment]
How difficult of a fix is this? As you know with TaylorSeries discussion, I have a usecase for Forward Mode Derivatives through these models.

**Comment by jsacks3** [comment]
I also have this problem. I am using ForwardDiff in conjunction with NLsolve, which in turn has a residual function that contains a Chain of Dense layers. NLsolve only supports finite difference and forward mode autodiff via ForwardDiff for Jacobian calculation. Would it be a difficult fix or is it something that we can do easily?

**Comment by aterenin** [comment]
Here's another broken example.
```
using Flux
using ForwardDiff
x = randn(Float32, 32,32,1,1)
v = randn(Float32, 32,32,1,1)
duals = ForwardDiff.Dual.(x,v)
layer = Conv((3,3),1=>2,relu;pad=(1,1))
layer(duals)
```
This one sometimes causes Julia to crash, depending on whether it is executed on CPU or GPU. Same issue if `Conv` is replaced with `Dense` and modified appropriately.

In my case, I'd like to implement WGAN-GP loss, where to avoid higher-order AutoDiff I'm defining custom gradients for the gradient penalty term `||\grad D||^2` using the chain rule `\grad||\grad D||^2 = H_D * (2 \grad D)` where `H_D` is the Hessian that I want to compute efficiently using the forward-mode/reverse-mode Hessian vector-product trick.

**Comment by martindvds** [comment]
I also desperately need this for taking **gradients** through functions mixing Flux models and other arbitrary Julia functions. I realized that this stopped working somewhere between Flux 0.6.9 and 0.7.2 already. 
My simple broken example:
```
using Flux
using ForwardDiff
using LinearAlgebra
y = rand(20)
f = (x) -> (norm(y - abs.(Dense(10, 20)(x).data)))
ForwardDiff.gradient(f, rand(10)) # Stackoverflow!
```

**Comment by MikeInnes** [comment]
Why don't you just take gradients using `Tracker` as usual?
