### ISSUE TITLE
ERROR: type LSTMCell is immutable

### ISSUE THREAD

**Issue by ngphuoc** [FluxML/Flux.jl#65]
I got this error when trying a sequence to sequence model as follow:

```julia
encode = LSTM(N, 256)
decode = Chain(LSTM(N, 256), Dense(256, N), softmax)
encode.(xs)
decode[1].cell.h = encode.cell.h
decode[1].cell.c = encode.cell.c
```

Shouldn't the states (h,c) be out of the LSTM model?

**Comment by MikeInnes** [comment]
The `cell.h` field contains an initial value for the hidden states, but not the actual state. Instead you should write something like `decode[1].state = encode.state`.

**Comment by MikeInnes** [comment]
I assume you figured this out, but let me know if there's anything else.
