### ISSUE TITLE
Silently dropped tracking when broadcasting on TaylorSeries

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#659]
I am experiencing what I believe is a bug with Flux where it is silently dropping gradient information when broadcasting on array of `Taylor1{Float64}` from `TaylorSeries.jl`. After investigating a bit I believe this is a bug on Flux's end.

```
using TaylorSeries
using Flux

shift_taylor(a,n) = a + Taylor1(typeof(a),n)
tu = shift_taylor(1.,3)     #type Taylor1, 1. +1.*t + O(t^4)

f(x) = param(2.) * x   # non-broadcast, tracked function
fb(x) = param(2.) .* [x]  # broadcast, tracked function

f(tu) # == 2.0 (tracked) + 2.0 (tracked) t + 𝒪(t⁴)
fb(tu) # 1-element Array{Taylor1{Float64},1}: 2.0 + 2.0 t + 𝒪(t⁴)
```

In the above example you see that evaluating a tracked function on a `Taylor1` results in a tracked `Taylor1` as expected. However, if that tracked function is broadcasted on an array of `Taylor1`s then the tracking is dropped.

I'd expect that the last line returns: 
`1-element Array{Taylor1{Flux.Tracker.TrackedReal{Float64}},1}: 2.0 (tracked) + 2.0 (tracked) t + 𝒪(t⁴)`

**Comment by jessebett** [comment]
Also tagging @dpsanders.

**Comment by jessebett** [comment]
What is possibly the cause of this is that I believe broadcasting a tracked function over an array returns a tracked array, and not an array of tracked values.

i.e. `param(2.).*[1.]` returns `Tracked 1-element Array{Float64,1}: 2.0` and not `1-element Array{Flux.Tracker.TrackedReal{Float64},1}: 2.0` i.e. tracked array, not array of tracked.

In that case, the expected return should probably be:
`Tracked 1-element Array{Taylor1{Float64},1}: 2.0 + 2.0 t + 𝒪(t⁴)`

@MikeInnes any idea why broadcasting is silently dropping the gradient where scalar evaluation isn't?

**Comment by jessebett** [comment]
Or alternatively, if there is a method I can define to override this collecting of tracking behviour over broadcasted operations.

i.e. a method that would allow `param(2.).*[1.] == 1-element Array{Flux.Tracker.TrackedReal{Float64},1}: 2.0`

Which would ideally result in what I previously expected: `fb(tu) == 1-element Array{Taylor1{Flux.Tracker.TrackedReal{Float64}},1}: 2.0 (tracked) + 2.0 (tracked) t + 𝒪(t⁴)`

**Comment by mcabbott** [comment]
Note that this is an error without Flux loaded, so perhaps something is wrong with broadcasting `Taylor1` (with the same `tu` as above):
```
julia> tu .* [2.0] 
ERROR: MethodError: no method matching Float64(::Taylor1{Float64})
```
Some examples with Flux: 
```
julia> [tu] .* [param(2.0)] # purely TrackedReal, ok
1-element Array{Taylor1{Flux.Tracker.TrackedReal{Float64}},1}:
  2.0 (tracked) + 2.0 (tracked) t + 𝒪(t⁴)

julia> [tu] .* param([2.0]) # TrackedArray, forgets tracking, this involves ForwardDiff
1-element Array{Taylor1{Float64},1}:
  2.0 + 2.0 t + 𝒪(t⁴)

julia> tu .* param([2.0])
ERROR: MethodError: no method matching Float64(::Taylor1{Float64})
 [1] convert(::Type{Float64}, ::Taylor1{Float64}) at ./number.jl:7
…
 [9] broadcast(::typeof(*), ::Taylor1{Float64}, ::Array{Float64,1}) at ./broadcast.jl:707
 [10] ∇broadcast 
```
Some attempts to trip up `ForwardDiff`, but it works fine here: 
```
julia> ForwardDiff.derivative(x -> (x * tu).coeffs[2], 2.0)
1.0
julia> ForwardDiff.derivative(x -> (x .* [tu])[1].coeffs[2], 2.0)
1.0
```

**Comment by mbauman** [comment]
One of the errors you're running into here is because TaylorSeries reports these `Taylor1`s as having an `eltype` of `Float64`, but if you actually iterate over them, you get back a `Taylor1{Float64}`.  Broadcast is taking it at its word, which apparently is leading to this strange behavior.  It's not the whole story, though, because after haphazardly patching things up, the MWE in the first post still drops tracking.

```julia
julia> eltype(tu)
Float64

julia> eltype(typeof(tu)) # this should match (and is the canonical method to implement)
Taylor1{Float64}

julia> typeof(first(tu))
Taylor1{Float64}

julia> eltype(tu)
Taylor1{Float64}

julia> tu .* [2.0]
1-element Array{Taylor1{Float64},1}:
  2.0 + 2.0 t + 𝒪(t⁴)
```

**Comment by mbauman** [comment]
It looks like the original issue is this line here:

https://github.com/FluxML/Flux.jl/blob/master/src/tracker/lib/array.jl#L454

Flux intentionally discards tracking information for non-`Real` numbers.

**Comment by MikeInnes** [comment]
Our assumption here is that if you return a non-real you're doing something non-differentiable (e.g. broadcasting `iseven` or something). That assumption of course isn't right in many cases; it might be safer to remove it entirely and just throw an error here.

It's possible to support Taylor series in forward-mode broadcast but a bit non-trivial. A creative solution might be possible here but probably the best route is (a) just use `map` and do things in a scalar way or (b) wait for Zygote.

**Comment by jessebett** [comment]
@MikeInnes what do you mean by just use map? do you mean not to use the layers like `Dense` which all internally have broadcast rules?

**Comment by jessebett** [comment]
Here's the current state of this:

I’m using @mbauman’s Flux branch where he extended tracking to `<:Number` not just `<:Real`. This breaks a lot of things, so isn’t a solution. But anyway, I also use his fix for `eltype` on Taylors:
`@eval TaylorSeries eltype(::Taylor1{S}) where S<:Number = Taylor1{S}`

which gets us to another bug requiring a promote_rule for Bools:
`promote_rule(::Type{Bool},T::Type{<:AbstractSeries}) = T`

This solved those initial problems, i.e., I can now get a tracked array of Taylors.

However, doing the gradients, both with the new Flux branch, and with Zygote I get probably related bugs about the behaviour of Taylor with ForwardDiff:

```
using TaylorSeries
using Flux
using Flux.Tracker:@grad
using Zygote

F = Chain(Dense(1,10,σ),Dense(10,10))

@eval TaylorSeries eltype(::Taylor1{S}) where S<:Number = Taylor1{S}

import Base.promote_rule
promote_rule(::Type{Bool},T::Type{<:AbstractSeries}) = T

shift_taylor(a,n) = a + Taylor1(typeof(a),n)
t = shift_taylor(1.,5)

w = param(2.)
f(t) =  w .* [t]
getindex.(f(t)[1],0) # First coefficient, scalar to backprop

g = Tracker.gradient(()->getindex.(f(t)[1],0),params(w)) # Flux on Matt's Branch

gz = Zygote.gradient(()->getindex.(f(t)[1],0),params(w))
```

On the Flux branch the error is:
`ERROR: ArgumentError: Cannot create a dual over scalar type Taylor1{Float64}. If the type behaves as a scalar, define FowardDiff.can_dual.`

On Zygote:
`ERROR: MethodError: no method matching getindex(::Taylor1{ForwardDiff.Dual{Nothing,Float64,2}}, ::ForwardDiff.Dual{Nothing,Int64,2})`

I think the Zygote error is coming from the getindex required to extract a backprop-able scalar from the Taylor coeffs.
