### ISSUE TITLE
Deprecate initialiser keyword arguments

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#671]
These don't really work, they aren't flexible enough and are no more convenient that just supplying your own weights e.g. 

```julia
Dense(randn(2, 5), rand(2))
```

This is partly a docs issue as people don't realise that this is a supported option. Although like most things, it will of course get more convenient with #669.

**Comment by shreyas-kowshik** [comment]
I am willing to work on this. 
But I need to clarify a few things beforehand : 
```
using Flux
using Distributions:Normal

dist = Normal(0.0,1.0)
function initW(out,in)
    W = rand(dist,out,in)
end

Dense(2,3,sigmoid,initW=initW,initb=zeros)
```

This piece of code does work right?...So why is there a need to depreciate it?...
I apologize if I'm being silly here. In case if this is not what is relevant to this issue, then can you please explain what needs to be done exactly?

**Comment by MikeInnes** [comment]
The original idea was that you could choose initilialisers for a large model with the `init` kwarg (e.g. `ResNet50(init = xorot_uniform)`. But we ended up using different initialisers on a per-parameters basis (`initW` and `initb`) which defeats the purpose, since now you have to deal with every weight separately anyway. On top of that, this extra API must be explicitly added to each new layer, which makes it harder to achieve consistency (most newer layers don't have it at all).

So given those issues and the fact that you can just as easily write this without `initW`, we can simplify things a fair bit by just removing it.

**Comment by shreyas-kowshik** [comment]
So all that needs to be done is to add deprecation warnings to ```Dense(...)```...?
Also for the warning, is this message fine : 
```
Dense(in,out,act,initW,initb) is deprecated; use Dense(in,out) instead
```
OR is this required : 
```
Dense(in,out,act,initW,initb) is deprecated; use Dense(in,out,init) instead
```

Accordingly I shall make changes to the API then.

Can you please clarify it a bit here @MikeInnes. 
Thank You.

**Comment by johnnychen94** [comment]
https://github.com/FluxML/Flux.jl/blob/7418a2d7d721451e4af5e5835abc424acfd2a80c/src/layers/basic.jl#L65-L71

`Dense(in,out,act,initW,initb) is deprecated; use Dense(in,out,init) or Dense(W, b, σ) instead`

**Comment by shreyas-kowshik** [comment]
@MikeInnes added the deprecation warning in #722 .
