### ISSUE TITLE
Backprop of sum of product takes very long time

### ISSUE THREAD

**Issue by mboratko** [FluxML/Flux.jl#674]
Running Julia 1.0.3, here's an example:

```julia
using Flux
w = param(randn(30,10))
Tracker.gradient(w->sum(prod(w,2)), w)
```
This took at least 30 seconds or so for me. Increasing 30 to, say, 100 makes it take several minutes. (I have not been patient enough to let it finish.)

**Comment by mboratko** [comment]
Verified this occurs on Juliabox as well.

**Comment by mboratko** [comment]
I just discovered that changing `prod(w,2)` to `prod(w,dims=2)` makes the gradient operation instantaneous.

**Comment by mcabbott** [comment]
See #524, which I've been meaning to get back to. 

Latest code may be here: https://github.com/FluxML/Tracker.jl/blob/master/src/lib/array.jl#L307

**Comment by mcabbott** [comment]
For completeness: be warned that `prod(w,2)` is actually giving you an incorrect gradient here (besides being slow, and Julia 0.6 notation). It ignores the `2`:
```julia
julia> using Flux, ForwardDiff

julia> w = reshape(1:6, 3,2) |> copy # Tracker.gradient does not need tracked w
3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

julia> Tracker.gradient(w->sum(prod(w)), w)
([720.0 180.0; 360.0 144.0; 240.0 120.0] (tracked),)

julia> Tracker.gradient(w->sum(prod(w,1)), w) # wrong answer!
([720.0 180.0; 360.0 144.0; 240.0 120.0] (tracked),)

julia> Tracker.gradient(w->sum(prod(w,2)), w) # wrong answer!
([720.0 180.0; 360.0 144.0; 240.0 120.0] (tracked),)

julia> Tracker.gradient(w->sum(prod(w, dims=1)), w)
([6.0 30.0; 3.0 24.0; 2.0 20.0] (tracked),)

julia> Tracker.gradient(w->sum(prod(w, dims=2)), w)
([4.0 1.0; 5.0 2.0; 6.0 3.0] (tracked),)

julia> ForwardDiff.gradient(w->sum(prod(w)), w)
3×2 Array{Int64,2}:
 720  180
 360  144
 240  120

julia> ForwardDiff.gradient(w->sum(prod(w, dims=1)), w)
3×2 Array{Int64,2}:
 6  30
 3  24
 2  20

julia> ForwardDiff.gradient(w->sum(prod(w, dims=2)), w)
3×2 Array{Int64,2}:
 4  1
 5  2
 6  3
```
The gradient defined for `prod(w,2)` is actually correct for `prod(w)`, done in a way which allows for `w` to contain zeros. `prod(w, dims=2)` is I think falling back to `TrackedReal`.
