### ISSUE TITLE
Member access fails when SparseVector is used

### ISSUE THREAD

**Issue by GenaBitu** [FluxML/Flux.jl#69]
Hi, I got this error while trying to use sparse matrices and vectors with Flux.
```julia
julia> a = TrackedArray(sparse([1, 2, 3]))
Tracked 3-element SparseVector{Int64,Int64}:
 1
 2
 3

julia> a[2]
ERROR: MethodError: no method matching spzeros(::Type{Int64})
Closest candidates are:
  spzeros(::Type{T}, ::Integer) where T at sparse/sparsevector.jl:47
  spzeros(::Type{Tv}, ::Integer, ::Integer) where Tv at sparse/sparsematrix.jl:1375
  spzeros(::Type{Tv}, ::Type{Ti<:Integer}, ::Integer) where {Tv, Ti<:Integer} at sparse/sparsevector.jl:48
  ...
Stacktrace:
 [1] getindex(::TrackedArray{…,SparseVector{Int64,Int64}}, ::Int64) at /home/user/.julia/v0.6/Flux/src/tracker/lib.jl:9
```

From what I know, the problem is a call to `similar` with empty tuple as last parameter (in function `toarray`) - In Julia, there isn't such a thing as a 0-dimensional sparse array AFAIK.

Thank you

**Comment by MikeInnes** [comment]
Yup, it fails for anything other than 1 or 2D:

```julia
x = sparse([1,2,3])
similar(x, ())
```

This seems like a Base bug to me -- `similar` should just return an `Array` if it can't do anything else.

You could solve it by monkey-patching `similar(::SparseVector, ::Tuple{})`.

**Comment by GenaBitu** [comment]
Agreed, opened JuliaLang/julia#23905.

**Comment by GenaBitu** [comment]
The issue JuliaLang/julia#23905 has been successfully resolved.
