### ISSUE TITLE
Tracker dependency

### ISSUE THREAD

**Issue by ayadlin** [FluxML/Flux.jl#695]
I am using  a package (DiffEqSensitivity) that requires Flux - adding the package works, but using ir fails because of flux. I solved the issue by adding Tracker on my own, but maybe there is way for Tracker to be installed as Flux is?

Thanks

┌ Info: Recompiling stale cache file /opt/julia/compiled/v1.0/SymPy/KzewI.ji for SymPy [24249f21-da20-56a4-8eb1-6a02cf4ae2e6]
└ @ Base loading.jl:1184
┌ Info: Recompiling stale cache file /opt/julia/compiled/v1.0/DifferentialEquations/UQdwS.ji for DifferentialEquations [0c46a032-eb83-5123-abaf-570d42b7fbaa]
└ @ Base loading.jl:1184
┌ Info: Recompiling stale cache file /opt/julia/compiled/v1.0/DiffEqSensitivity/02xYn.ji for DiffEqSensitivity [41bf760c-e81c-5289-8e54-58b1f1f8abe2]
└ @ Base loading.jl:1184
┌ Warning: Package Flux does not have Tracker in its dependencies:
│ - If you have Flux checked out for development and have
│   added Tracker as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Flux
└ Loading Tracker into Flux from project dependency, future warnings for Flux are suppressed.
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for DiffEqSensitivity [41bf760c-e81c-5289-8e54-58b1f1f8abe2]
│   exception = ErrorException("Required dependency Flux [587475ba-b771-5e3f-ad9e-33799f191a9c] failed to load from a cache file.")
└ @ Base loading.jl:963
┌ Info: Recompiling stale cache file /opt/julia/compiled/v1.0/Flux/QdkVy.ji for Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
└ @ Base loading.jl:1184
┌ Warning: Package Flux does not have Tracker in its dependencies:
│ - If you have Flux checked out for development and have
│   added Tracker as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Flux
└ Loading Tracker into Flux from project dependency, future warnings for Flux are suppressed.

**Comment by dhairyagandhi96** [comment]
Fixed with Flux v0.8.1, could you try adding DiffEqSensitivity in a new environment and see if that helps matters?

**Comment by ayadlin** [comment]
will do -
and let you know!
thanks

**Comment by ayadlin** [comment]
sorry for the late reply-

**Comment by ayadlin** [comment]
So upgrading Flux to 8.1 solved the problem - 
I think DiffEqSensitivity has 8.0 as its requirement and that generated the issue.

Thanks for the help!

**Comment by dhairyagandhi96** [comment]
DiffEqSensitivity.jl would try and use the latest tag of Flux in it's dependency. 

Glad that solved the issue for you, and thanks for pointing it out.

Closing this now
