### ISSUE TITLE
`activations` is broken

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#702]
In Flux v0.6.1, the last tutorial code sample in [regularisation](https://github.com/FluxML/Flux.jl/blob/d6a75e1289488945ade1cfa8867717fe1ed19557/docs/src/models/regularisation.md) fails

```julia
using Flux
c = Chain(Dense(10,5,σ),Dense(5,2),softmax)
Flux.activations(c, rand(10))
```
which raises `ERROR: MethodError: no method matching accumulate(::getfield(Flux, Symbol("##62#63")), ::Array{Float64,1}, ::Array{Any,1})`

It seems that `accumulate(op, A; dims::Integer, [init])` doesn't support multiple inputs as you wrote in `activations(c::Chain, x) = accumulate((x, m) -> m(x), x, c.layers)` anymore.

_Originally posted by @johnnychen94 in https://github.com/FluxML/Flux.jl/pull/174#issuecomment-414040344_

**Comment by johnnychen94** [comment]
Here's my original patch, I closed the PR https://github.com/FluxML/Flux.jl/pull/355 because @MikeInnes at that time you fixed it by yourself.

```julia
activations(m::Any, x, rst=[]) = push!(rst,m(x))
activations(c::Chain, x, rst=[]) = begin
    rst = activations(c[1], x, rst)
    if length(c) >= 2
        rst = activations(c[2:end], rst[end], rst)
    end
    return rst
end
```

**Comment by MikeInnes** [comment]
`reduce` is surprisingly broken in Julia. It'd be nice just to have a simple reduce-over-tuples (should be a couple lines) and use that. Or figure out why else this went wrong.

**Comment by johnnychen94** [comment]
A temporary patch is implemented in https://github.com/FluxML/Flux.jl/pull/710
However, this issue should be kept open unless fix on upstream is impossible or there's a real reason to have a Flux-version `reduce`

**Comment by MikeInnes** [comment]
Meh. That would be nice but the important thing is that this works, and your implementation is totally reasonable. So I think we can close this for now and change it if `accumulate` every improves.
