### ISSUE TITLE
`init` argument in `LSTMCell` unused

### ISSUE THREAD

**Issue by kleinschmidt** [FluxML/Flux.jl#73]
I was browsing the code and I noticed that while the `LSTMCell` constructor takes an `init` argument, all of the layers are initialized with `initn()` instead of `init()`: https://github.com/FluxML/Flux.jl/blob/a60a754d68df79aa6e19f7f7b3992164d47703b0/src/layers/recurrent.jl#L65-L68

**Comment by MikeInnes** [comment]
Good catch, thanks. Any chance of a PR?
