### ISSUE TITLE
sigmoid: multiplicative identity only defined for non-square matrices

### ISSUE THREAD

**Issue by aterenin** [FluxML/Flux.jl#730]
Getting this error when attempting to use `Dense(784,1,sigmoid)` on an MNIST minibatch.

The problem appears to be that `Dense` is attempting to apply `sigmoid`, which is defined at `one(x) / (one(x) + exp(-x))` in a non-elementwise fashion.

This does not appear to be intended behavior. It can probably be fixed with appropriate type annotations, but I am not familiar enough with the packages to know what they should be.

**Comment by MikeInnes** [comment]
It's built into the definition of `Dense` that it applies the activation `sigmoid` elementwise (via broadcasting). So it's hard to see how this would happen unless you have arrays-of-arrays somehow. A minimal test case would be greatly helpful.

**Comment by darsnack** [comment]
I believe this is resolved:
```julia
julia> m = Dense(784, 1, sigmoid)
Dense(784, 1, σ)

julia> m(rand(784, 1000))
1×1000 Array{Float64,2}:
 0.419374  0.42289  0.461  0.672985  0.483037  0.730562  …  0.438011  0.337419  0.288613  0.46692

julia> m = m |> gpu
Dense(784, 1, σ)

julia> m(gpu(rand(784, 1000)))
1×1000 CuArray{Float32,2}:
 0.550318  0.635071  0.533073  0.496118  0.562269  …  0.455415  0.616085  0.544929  0.387105
```

I am closing but feel free to re-open if you think I misinterpreted the issue.
