### ISSUE TITLE
Non-square convolution not working anymore?

### ISSUE THREAD

**Issue by bhvieira** [FluxML/Flux.jl#731]
This worked before, but I can't seem to get it working now.
See reproducible example below:

```
using Flux

#works, and return a (1,1,2,5) array
Conv((3,3), 1=>2)(randn(3,3,1,5))
#throws an error in Flux v0.8.2/v0.8.2+ #master
Conv((3,1), 1=>2)(randn(3,3,1,5))
```

The error message reads:

> `ERROR: DimensionMismatch("new dimensions (1, 1, 3, 1, 1) must be consistent with array size 9")

**Comment by KristofferC** [comment]
https://github.com/FluxML/Flux.jl/issues/700

**Comment by bhvieira** [comment]
> #700

Thanks! Didn't think about searching for "quadratic" specifically, stuck with "square" on my mind
