### ISSUE TITLE
1D Conv Broken

### ISSUE THREAD

**Issue by ckneale-ccri** [FluxML/Flux.jl#740]
Hey people, was just trying to do a 1-D Conv in flux and I'm pretty sure it is busted for the CPU so presumably also the GPU:

```julia
a = ones(7,1,1,1)
tst = Flux.Conv( ( 2, 1 ), 1 => 1 Flux.σ)
tst(a)[:,1,1,1]
```
throws:
```DimensionMismatch("new dimensions (6, 0, 2, 1, 1) must be consistent with array size 12")```

Tried to work around the issue by padding:
```julia
a = ones(7,1,1,1);
tst = Flux.Conv( ( 2, 2 ), 1 => 1, pad=(0, 1), Flux.identity)
tst(a)[:,:,1,1]

size(tst(a))
```

Think there's a one off error somewhere in the dimensionality calculation. 2-tensors work just fine.

**Comment by bhvieira** [comment]
It's been reported already. NNlib is (was?) missing a release tag to solve the problem. See #700

**Comment by caseykneale** [comment]
Sorry this can be closed!

**Comment by ckneale-ccri** [comment]
Just checked, installed the latest Flux and NNlib from the general registry, and no luck. I'll write my own 1D Conv operator for now, but it'd be good to have this fixed, or a fix posted.

**Comment by bhvieira** [comment]
You can rollback to the last commit before the one that induced this bug or
implement the fix locally in the meantime (I saw it on NNlib and it was
pretty straightforward)

**Comment by ckneale-ccri** [comment]
I am actively running Flux code for another project, that relies on the same environment as this code, and I'd have to sort out what the changes mean for my other code if there are conflicts. It just made more sense to write a naive 1-D conv for now.

**Comment by ckneale-ccri** [comment]
Tried to build the latest version of NNLib because I followed the discussion where this bug was fixed. Can't build from master, some methods are missing...

**Comment by gebodal** [comment]
> You can rollback to the last commit before the one that induced this bug or implement the fix locally in the meantime (I saw it on NNlib and it was pretty straightforward)

Any chance you could link to that local fix, please?

**Comment by bhvieira** [comment]
> 
> 
> > You can rollback to the last commit before the one that induced this bug or implement the fix locally in the meantime (I saw it on NNlib and it was pretty straightforward)
> 
> Any chance you could link to that local fix, please?

Sure, I haven't tested it though: https://github.com/FluxML/Flux.jl/issues/700#issuecomment-476614227

**Comment by bhvieira** [comment]
It has been merged as well to NNlib#master. See https://github.com/FluxML/NNlib.jl/issues/104 as well.

**Comment by gebodal** [comment]
> It has been merged as well to NNlib#master. See [FluxML/NNlib.jl#104](https://github.com/FluxML/NNlib.jl/issues/104) as well.

Apologies, still a little new to the Julia ecosystem: should this be fixable using
```(v1.0) pkg> add NNlib#master```
because I am getting conflicts with Flux (`ERROR: Unsatisfiable requirements detected for package Flux [587475ba]`).

Or would the fix here be `dev NNlib` and then change that function myself?

**Comment by caseykneale** [comment]
I had the same bug. Ended up switching to pytorch for my last project :/

**Comment by bhvieira** [comment]
I downgraded to `NNlib#ccc6dad` (not sure if this specific commit, because I've been messing with some projects, but give it a go), and it works fine on my end. @gebodal @caseykneale

**Comment by ckneale-ccri** [comment]
I'll give this a try later maybe. For my current project downgrading and rewriting the code from pytorch would be a bit of a hindrance at this point. For stability/deployment purposes it's also a tricky fix.

**Comment by jchen975** [comment]
Hi, I'm trying to build a 1d conv net as well and I'm not sure how to set `pad` and `stride`. I noticed that you used `pad = (0,1)` here, does that pad the your row vector input? I'm assuming it's a 7x1 row vector input because you used `ones(7,1,1,1)`. This question also applies to `stride`. Thanks!

> Hey people, was just trying to do a 1-D Conv in flux and I'm pretty sure it is busted for the CPU so presumably also the GPU:
> 
> ```julia
> a = ones(7,1,1,1)
> tst = Flux.Conv( ( 2, 1 ), 1 => 1 Flux.σ)
> tst(a)[:,1,1,1]
> ```
> 
> throws:
> `DimensionMismatch("new dimensions (6, 0, 2, 1, 1) must be consistent with array size 12")`
> 
> Tried to work around the issue by padding:
> 
> ```julia
> a = ones(7,1,1,1);
> tst = Flux.Conv( ( 2, 2 ), 1 => 1, pad=(0, 1), Flux.identity)
> tst(a)[:,:,1,1]
> 
> size(tst(a))
> ```
> 
> Think there's a one off error somewhere in the dimensionality calculation. 2-tensors work just fine.

**Comment by darsnack** [comment]
This should all be resolved for a while now.

```julia
julia> a = ones(7, 1, 1, 1)
7×1×1×1 Array{Float64,4}:
[:, :, 1, 1] =
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

julia> tst = Conv((2, 1), 1 => 1, σ)
Conv((2, 1), 1=>1, σ)

julia> tst(a)[:, 1, 1, 1]
┌ Warning: Slow fallback implementation invoked for conv!  You probably don't want this; check your datatypes.
│   yT = Float64
│   T1 = Float64
│   T2 = Float32
└ @ NNlib ~/.julia/packages/NNlib/KxOwM/src/conv.jl:206
6-element Array{Float64,1}:
 0.6246932724070121
 0.6246932724070121
 0.6246932724070121
 0.6246932724070121
 0.6246932724070121
 0.6246932724070121
```

@jchen975 I'm not sure exactly what your goal is, but can you take a look at [the latest docstring](https://github.com/FluxML/Flux.jl/blob/15a0ebfbf8446e913efdd0ce3fa2be26fbaaa080/src/layers/conv.jl#L32)? If there's still an issue, maybe we can open a specific docstring issue.
