### ISSUE TITLE
Implicit to Explicit Parameterization of Flux Models

### ISSUE THREAD

**Issue by jessebett** [FluxML/Flux.jl#742]
I think DiffEqFlux's `restructure` and `destructure` should be brought to Flux and documented as a way of defining Flux models as implicit, but then converting them to explicitly depend on their parameters. 

```
nn = Dense(1,1,tanh)
p = destructure(nn)
params = Params([p])
function f(z, p)
    m = restructure(nn,p)
    return m(z)
end
```

This can be useful for instance when defining hypernets -- networks whose parameters are the output of another network.

**Comment by yuehhua** [comment]
This should be solved in #986
