### ISSUE TITLE
Which data format should I use to put in the Flux.train! function?

### ISSUE THREAD

**Issue by masenka31** [FluxML/Flux.jl#746]
Hello,

I'm still new to Julia and Flux, therefore I am sorry if my question sounds silly.

I'm trying to do regression with Flux for a 3D problem - I have x and y coordinates and want to predict z. I want to put a single element array in the training function as

( [ [x1, x2, ... , xn], [y1, y2, ... , yn] ], [z1, z2, ... , zn] ).

But any version of how my data looks, it always throws an error. Is there any document where I can learn how to put data together so that it works? The documentation for Flux isn't very helpful, there's very little information.

There's how I'm trying to work with the data:

```
t = 1:0.2:5

a = 3 .+ 2 .* t .^2
b = -2 .+ 4 .* t .+ t .^3
c = -4 .- -1 .* t

an = a + 1/4*randn(size(t))
bn = b + 1/4*randn(size(t))
cn = c + 1/4*randn(size(t))

network = Chain(Dense(2, 5, swish), Dense(5, 1, swish))
net_loss(x, y) = Flux.mse(network(x), y)
net_opt = Descent(0.005)

x_net = [(an', bn')]
y_net = copy(cn')
net_data = [(x_net, y_net)]

iter = 5000
for i in 1:iter
    Flux.train!(net_loss, params(network), net_data, net_opt)
end
```

With this code it throws this error:

` MethodError: convert(::Type{Union{}}, ::Tuple{Adjoint{Float64,Array{Float64,1}},Adjoint{Float64,Array{Float64,1}}}) is ambiguous.`

And I've got many more errors, it just never works.

**Comment by aterenin** [comment]
Try `[(collect(an'), collect(bn'))]` so that your data doesn't have any transpose types, which are somewhat new and still a bit rough around the edges.

**Comment by masenka31** [comment]
Tried that, couldn't make it work. Nothing really works. I've tried everything I could think of.

I guess there's the dimensionality problem. I want to have the input in a form of two elements (two vectors) each having 21 sub-elements. The output should be one element (vector) of 21 sub-elements.

Does that mean that I have to create a network with 42 inputs and 21 outputs and go somehow from there?

**Comment by aterenin** [comment]
In your case, `train!` calls `net_loss(net_data[1]...)`, which expands to `net_loss(x_net, y_net)`, which expands to `net_loss([(an', bn')],cn)`. This attempts to call `network([(an',bn')])` which triggers the error.

Unless you have a very good reason for doing so, don't feed networks arrays of arrays or arrays of tuples or any similar types - this is very slow and prone to type errors. Instead, feed them a multidimensional array.

Assuming your batch dimension is 21, try 

```julia
x_net = vcat(an',bn')
y_net = collect(cn')
```
 which you can check works by running `network(x_net)` - this gives a 1x21 array - and `net_loss(x_net, y_net)` - this gives a scalar output. For me, running `train!` on your example works.

**Comment by masenka31** [comment]
Thank you very much for somewhat clearing that up for me. I wasn't sure which format would work the best, now I finally seem to start understanding it.

**Comment by darsnack** [comment]
I think the question here has been answered? I'm closing the issue, but please re-open if there are still doubts.
