### ISSUE TITLE
Error from mapchildren in normalise.jl

### ISSUE THREAD

**Issue by jctops** [FluxML/Flux.jl#748]
Apologies for the double-submission, am not familiar with best practice yet but pull request  #747 is a suggested fix for this

In calling GroupNorm from mapchildren (line 386) I believe "gn,G" should read "gn.G" to call G as an attribute rather than a (not defined) variable. I discovered this by using a Chain containing GroupNorm and trying to move it to the gpu, where it raised the error "ERROR: LoadError: UndefVarError: G not defined". This is also the case when trying to use GroupNorm in a neural_ode in DiffEqFlux

**Comment by dhairyagandhi96** [comment]
Closed from #747 

Thanks!
