### ISSUE TITLE
increasing GC time while training.

### ISSUE THREAD

**Issue by Menee** [FluxML/Flux.jl#751]
It takes 40% time to do GC during the 2nd epoch and then 50% for the 3rd epoch and then 60% for  the 4th epoch...

I have tried to call GC.gc() and CuArrays.gc()(in callback and/or after a epoch) but it didn't work.

What may be the reason? How can I solve it?
Thanks a lot.

Info.
DenseNet (both Metalhead's and mine) (The problem wont happen on a classifier)
CuArrays have been used.
Nvidia MX150 (2GB) 
Windows 10

**Comment by KristofferC** [comment]
Referencing this issue: https://github.com/JuliaGPU/CuArrays.jl/issues/323
