### ISSUE TITLE
BatchNorm gradients return Float64 instead of Float32

### ISSUE THREAD

**Issue by aterenin** [FluxML/Flux.jl#757]
MWE
```
x = randn(Float32, 8,8,3,16)
v = randn(Float32, 8,8,3,16)
bn = BatchNorm(3)
(y, back) = Flux.Tracker.forward(bn,x) # (Array{Float32,4}, λ)
back(v)[1] # Array{Float64,4)
```
Whatever the issue is, it's a bit subtle, because it occurs in `back` - the type of `y` in the forward pass is correct. I'll make a PR if I find out.

**Comment by bhvieira** [comment]
Tracker was deprecated, the issue is not reproducible anymore. BatchNorm might have changed as well, I can't even get the forward pass.

**Comment by aterenin** [comment]
Last I looked at Flux's source, the underlying issue is still present in spite of Tracker deprecation, and I suspect this will reproduce on Zygote. I am happy to finish my PR given appropriate input.

**Comment by bhvieira** [comment]
For sure! I've been running down the issues tracker searching for deprecated stuff, but on this issue of yours I actually thought it could be still active due to BN (it probably is), but I couldn't run your MWE, nor even the forward pass.

```
julia> bn(x)
ERROR: UndefVarError: isnothing not defined
Stacktrace:
 [1] _isactive(::BatchNorm{typeof(identity),Array{Float32,1},Array{Float32,1},Float32}) at C:\Users\bhebl\.julia\packages\Flux\NpkMm\src\layers\normalise.jl:5
 [2] (::BatchNorm{typeof(identity),Array{Float32,1},Array{Float32,1},Float32})(::Array{Float32,4}) at C:\Users\bhebl\.julia\packages\Flux\NpkMm\src\layers\normalise.jl:182
 [3] top-level scope at none:0
```

**Comment by CarloLucibello** [comment]
I don't see any conversion problem on master:
```julia
julia> x = rand(Float32, 2,3)
2×3 Array{Float32,2}:
 0.0336944  0.897612   0.230159
 0.503094   0.0609328  0.815861

julia> x = rand(Float32, 2,3);

julia> bn = BatchNorm(2);

julia> gradient(()->sum(bn(x)), params(bn)).grads
IdDict{Any,Any} with 5 entries:
  :(Main.x)         => Float32[4.76837f-7 -4.76837f-7 0.0; 2.38419f-7 0.0 0.0]
  :(Main.bn)        => RefValue{Any}((λ = nothing, β = Float32[3.0, 3.0], γ = Float32[-2.08616f-7, -1.19209f-7], μ = nothing, σ² = nothing, ϵ = 2.2011f-6, momentum = nothing, active = nothi…
  Float32[1.0, 1.0] => Float32[-2.08616f-7, -1.19209f-7]
  Float32[0.0, 0.0] => Float32[3.0, 3.0]
  BatchNorm(2)      => RefValue{Any}((λ = nothing, β = Float32[3.0, 3.0], γ = Float32[-2.08616f-7, -1.19209f-7], μ = nothing, σ² = nothing, ϵ = 2.2011f-6, momentum = nothing, active = nothi…
```

**Comment by aterenin** [comment]
Hmm, maybe this is a Tracker-specific issue that is gone as a result of deprecation of Tracker?

Looks like `m` in `(BN::BatchNorm)(x)` is going to be an Int64, which means that multiplying it against Float32 will produce another Float32. Thus, I don't see why any Float64 should show up to begin with in the gradients of the code as written.

I'm thus closing this issue and the PR - if someone can reproduce this, please re-open this.
