### ISSUE TITLE
ERROR: UndefVarError: derivative not defined

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/Flux.jl#768]
When I run` julia> using Flux.Tracker: derivative`... I am getting `ERROR: UndefVarError: derivative not defined`.  I have Flux downloaded and updated. 

I am trying to do the https://github.com/FluxML/model-zoo/blob/master/tutorials/60-minute-blitz.jl    example on line 122.

**Comment by dhairyagandhi96** [comment]
The tutorial need to be upgraded for the changes. The function was replaced by `gradient` to better describe what it's doing plus get API parity with Zygote moving forward.

Thanks for pointing it out

**Comment by anandijain** [comment]
Any idea when the 60 minute blitz will be updated?

**Comment by bhvieira** [comment]
It looks it was already @anandijain . Can this be closed?

**Comment by dhairyagandhi96** [comment]
I think so

**Comment by hafez-ahmad** [comment]
ERROR: UndefVarError: Tracker not defined

err = hcat(Flux.Tracker.data(loss(xtrn, ytrn)), Flux.Tracker.data(loss(xtst, ytst)))
ERROR: UndefVarError: Tracker not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:26
 [2] top-level scope at REPL[152]:1
 [3] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1088

Julia 1.5,.windows, [do I need to add an additional tracker package?]

**Comment by DhairyaLGandhi** [comment]
You might be on an older Flux version. You might want a newer release
