### ISSUE TITLE
Difference between params() and Params()

### ISSUE THREAD

**Issue by BenQLange** [FluxML/Flux.jl#781]
HI,

Through model-zoo I have figured out when to use params() and Params() but I would like to know the intended use case for both.  When do we use params() and Params()? What is the difference?

Thanks

**Comment by MikeInnes** [comment]
Only that `Params` is the raw constructor whereas `params` is designed to collect parameters from a model. For the most part you should be able to ignore `Params`, I expect.

**Comment by BenQLange** [comment]
Thanks.

**Comment by DoktorMike** [comment]
Should this not be closed then?

**Comment by BenQLange** [comment]
Yes. I am closing it now. Sorry.
