### ISSUE TITLE
Flux is not training model

### ISSUE THREAD

**Issue by francescoalemanno** [FluxML/Flux.jl#798]
```julia
using Flux,LinearAlgebra
function MWE()
    η=0.01
    model=Conv((64, 64), 1=>1, relu,stride=30)
    loss(x,y) = Flux.mse(model(x),y)
    dataset=[(rand(100,100,1,1),rand(2,2,1,1))]
    @show model(dataset[1][1])
    @show loss(dataset[1]...)
    opt=ADAM(η)
    for i in 1:10
        Flux.train!(loss,params(model), dataset, opt)
        @show i, loss(dataset[1]...)
    end
end

MWE();
```

    model((dataset[1])[1]) = [0.0 0.0; 1.46359 0.0] (tracked)
    loss(dataset[1]...) = 0.2001447729236289 (tracked)
    (i, loss(dataset[1]...)) = (1, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (2, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (3, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (4, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (5, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (6, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (7, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (8, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (9, 0.29602579662457984 (tracked))
    (i, loss(dataset[1]...)) = (10, 0.29602579662457984 (tracked))

```julia

```

I suspect that this is a bug in flux. Apparently the training procedure makes the parameters of the model null, and no further training happens.

If i used Flux incorrectly and this is not a Flux issue, i apologize in advance

**Comment by thebhatman** [comment]
Maybe you can try a different initialization of weights...

**Comment by bhgomes** [comment]
Running your code, it looks like the model weights do change. Just the loss is not changing.

**Comment by dellison** [comment]
There was some discussion of this on discourse, and it seems to have been figured out: https://discourse.julialang.org/t/flux-jl-is-not-modifying-the-loss/25646
