### ISSUE TITLE
BoundsError when using Batchnorm layer inside Maxout layer

### ISSUE THREAD

**Issue by HenriDeh** [FluxML/Flux.jl#810]
```
Chain( Maxout(() -> Chain(Dense(1,40), BatchNorm(40)), 3), Dense(40,1,relu))([10f0])
```
throws `ERROR: BoundsError: attempt to access (40,)  at index [0]`

This makes it impossible to use BatchNormalization before the Maxout non-linearity. This also happens in testmode. Additionnaly,
```
Chain(Dense(1,40), BatchNorm(40))([10f0])
```
throws ` ERROR: arraysize: dimension out of range`

**Comment by CarloLucibello** [comment]
The input needs the batch dimension
```julia
julia> Chain( Maxout(() -> Chain(Dense(1,40), BatchNorm(40)), 3), Dense(40,1,relu))(rand(Float32,1,1))
1×1 Array{Float32,2}:
 0.060646772
```
