### ISSUE TITLE
RNN behavior under different input shapes

### ISSUE THREAD

**Issue by danipozo** [FluxML/Flux.jl#811]
I'm confused by following behavior I have observed on recurrent models:
```
 julia> lstm(randn(20))
Tracked 2-element Array{Float64,1}:
 -0.029546426513383895
  0.09291522384115254 

julia> lstm(randn(20))
Tracked 2-element Array{Float64,1}:
 -0.302731441259433  
 -0.06277000263946321
```

but then, after calling it on a differently shaped array (a sequence),

```
julia> lstm(randn(20,3))
Tracked 2×3 Array{Float64,2}:
 -0.173689  -0.0628761   -0.226268 
  0.114719  -0.00120401   0.0431955

julia> lstm(randn(20,4)) # error
...

julia> lstm(randn(20))
Tracked 2×3 Array{Float64,2}:
 -0.217367   -0.157157   -0.217303  
  0.0844741  -0.0557372   0.00669047
```

It 1) no longer admits different length sequences, and 2) even when called on single vectors has 3 outputs.

**Comment by bhvieira** [comment]
What's `lstm`? Is it a `Flux.LSTM` layer?
Each time you apply a LSTM layer to an input batch (a single vector timepoint with possibly many samples, i.e. different sequences), the layer keeps it's state (so it can be used further into the sequence).

It makes no sense to apply the layer then to input with less samples (the state wouldn't propagate in time anymore, as dimensions do not match). This is what you did here:

    lstm(randn(20,3)) #20-dimensional input timepoint in 3 samples
    lstm(randn(20,4)) #20-dimensional input timepoint in 4 samples

**Comment by bhvieira** [comment]
Of course, when you're finished with your first 3 sequences, you can use `Flux.reset!` to set the state clean and start all over again on your other 4 sequences.

    #this works
    lstm(randn(20,3)) #20-dimensional input timepoint in 3 samples
    Flux.reset!(lstm)
    lstm(randn(20,4)) #20-dimensional input timepoint in 4 samples

**Comment by danipozo** [comment]
Thank you, I think I've understood this.
