### ISSUE TITLE
Can't get user defined model to work

### ISSUE THREAD

**Issue by danipozo** [FluxML/Flux.jl#812]
I can't seem to get a model similar to that described in https://arxiv.org/abs/1609.04938v2, in which a fully convolutional network is first applied to an image and then a recurrent network is applied to each row of the resulting features. The following code:

```julia
function (m::RowEncoder)(x)
    # Run recurrent net on each row
    out = [ m.bidir_lstm(x[i,:,:]) for i=1:m.rows ]
    # Concatenate and get desired shape
    out = cat(out...,dims=3)
    permutedims(out, (3,1,2))
end

Flux.@treelike RowEncoder
```

errors when training on MNIST:

```
BoundsError: attempt to access 4×4×20×128 Array{Float32,4} at index [1, Base.Slice(Base.OneTo(4)), Base.Slice(Base.OneTo(20))]
```

How should I handle batches in a call to `RowEncoder`? I've tried with a `for` loop approach but couldn't get it to work, and I am also unsure it is the right way to do it.

**Comment by ToucheSir** [comment]
Closing for age and bitrot, but a variant of this should be doable now without a custom layer, using the new built-in 3D RNN input support.
