### ISSUE TITLE
Custom serialization pass for intermediate states

### ISSUE THREAD

**Issue by Roger-luo** [FluxML/Flux.jl#845]
https://github.com/FluxML/Flux.jl/blob/aab3c4e05214b81a9cbbfa33d8da2a8d4cdba2f5/src/optimise/optimisers.jl#L96

Currently intermediate states in optimizers will cause it fail to read back from a serialization file like JLD. I think simply ignoring it when serializing the object would solve this problem.

**Comment by MikeInnes** [comment]
This would also be addressed by #637.

**Comment by ToucheSir** [comment]
Shall we close this as another handled by Optimisers.jl issue?
