### ISSUE TITLE
Should one(::TrackedArray) and zero(::TrackedArray) return TrackedArrays, instead of normal arrays?

### ISSUE THREAD

**Issue by kraftpunk97** [FluxML/Flux.jl#855]
```Julia
julia> zero(param(rand(4)))
4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
```

**Comment by ChrisRackauckas** [comment]
yes. See https://github.com/FluxML/Flux.jl/pull/505 and https://github.com/FluxML/Flux.jl/pull/491

**Comment by MikeInnes** [comment]
No, that's not the conclusion from those discussions. It's still not clear that this causes problems that can't be solved by e.g. fixing `similars` and friends, beyond your assertion.

**Comment by ChrisRackauckas** [comment]
It is the conclusion. Those fixed quite a few generic code examples, so for the most part I just type pirate to add those things in to fix issues when using packages that haven't been setup to work with Tracker (setup to work is using workarounds like `false .* u`). After a year of continually making those same changes, it's quite a solid result.

**Comment by MikeInnes** [comment]
I didn't say that making the change wouldn't fix the issue, I said it's not the right fix for the issue. In any case, we need a test case for this discussion to be productive.
