### ISSUE TITLE
Github stars in pkg.julialang.org

### ISSUE THREAD

**Issue by hossein-pourbozorg** [FluxML/Flux.jl#867]
Flux doesn't have stars in _https://pkg.julialang.org/docs/_
![Screenshot from 2019-09-24 14-09-51](https://user-images.githubusercontent.com/19240961/65505267-a9d1a580-ded5-11e9-843b-c2cb63f38677.png)

**Comment by vdayanand** [comment]
it has been updated

**Comment by dhairyagandhi96** [comment]
Thanks @vdayanand @hossein-pourbozorg !!
