### ISSUE TITLE
Convolution without bias

### ISSUE THREAD

**Issue by pshashk** [FluxML/Flux.jl#868]
Many [vision networks ](https://github.com/search?utf8=%E2%9C%93&q=%22bias%3DFalse%22+repo%3Apytorch%2Fvision+extension%3Apy&type=Code&ref=advsearch&l=&l=) doesn't add bias after convolution. Can we add a flag to disable it in layer constructor?

**Comment by MikeInnes** [comment]
About to be addressed by #873.

**Comment by CarloLucibello** [comment]
reopening until #873 gets merged

**Comment by dhairyagandhi96** [comment]
Closing through #873
