### ISSUE TITLE
gradient problem

### ISSUE THREAD

**Issue by kuro26** [FluxML/Flux.jl#869]
### 1. code
```
f(x) = 3x^2 + 2x + 1
f(5)
df(x) = gradient(f, x)
df(5)
ddf(x) = gradient(df, x)
ddf(5)
```
### 2. error
```
Function output is not scalar

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] losscheck(::Tuple{Tracker.TrackedReal{Float64}}) at /root/.julia/packages/Tracker/SAr25/src/back.jl:153
 [3] gradient_(::Function, ::Int64) at /root/.julia/packages/Tracker/SAr25/src/back.jl:91
 [4] #gradient#24 at /root/.julia/packages/Tracker/SAr25/src/back.jl:164 [inlined]
 [5] gradient at /root/.julia/packages/Tracker/SAr25/src/back.jl:164 [inlined]
 [6] ddf(::Int64) at ./In[23]:5
 [7] top-level scope at In[23]:6
```

**Comment by dhairyagandhi96** [comment]
You probably want

```julia
ddf(x) = gradient(x -> df(x) |> sum, x)
```
or similar

**Comment by kuro26** [comment]
> You probably want
> 
> ```julia
> ddf(x) = gradient(x -> df(x) |> sum, x)
> ```
> 
> or similar

this is just some code in model-zoo/60-min-blitz, I am just puzzling why it doesn't work, and I don't want to use sum here

**Comment by mcabbott** [comment]
`gradient` always returns a tuple, and with one `x` it’s a one-element tuple, that’s what `df(5)` prints. You just want the first element. 

If you are using Tracker I think you also need to tell it to allow second derivatives, like so: `df(x) = gradient(f, x; nest=true)[1]`

**Comment by kuro26** [comment]
> `gradient` always returns a tuple, and with one `x` it’s a one-element tuple, that’s what `df(5)` prints. You just want the first element, but `sum(df(5)) == df(5)[1]`.
> 
> Since you are using Tracker I think you also need to tell it to allow second derivatives, like so: `df(x) = gradient(f, x; nest=true)[1]`

Thank you for explaining, It works!

**Comment by hossein-pourbozorg** [comment]
By Zygote, you can use this syntax:
```julia
using Zygote
f(x) = 3x^2 + 2x + 1
f(5) # 86
f'(5) # 32
f''(5) # 6
```
or the gradient function:
```julia
f(x) = 3x^2 + 2x + 1
f(5) # 86
df(x) = gradient(f, x)[1]
df(5) # 32
ddf(x) = gradient(df, x)[1]
ddf(5) # 6
```

**Comment by dhairyagandhi96** [comment]
Would you say it's good to close the issue?

**Comment by kuro26** [comment]
> By Zygote, you can use this syntax:
> 
> ```julia
> using Zygote
> f(x) = 3x^2 + 2x + 1
> f(5) # 86
> f'(5) # 32
> f''(5) # 6
> ```
> 
> or the gradient function:
> 
> ```julia
> f(x) = 3x^2 + 2x + 1
> f(5) # 86
> df(x) = gradient(f, x)[1]
> df(5) # 32
> ddf(x) = gradient(df, x)[1]
> ddf(5) # 6
> ```
Thank you for one more solution! I will try both!
