### ISSUE TITLE
Functor differentiability

### ISSUE THREAD

**Issue by MikeInnes** [FluxML/Flux.jl#878]
`fmap` currently errors when differentiating it, which is an issue mainly for RNNs (because of `reset!`). I think it's mostly just a case of fixing up adjoints for things like the set operations used internally by `fmap`; everything else should be pretty simple.

One test case:

```julia
struct Foo
  x
  y
end

@functor Foo

gradient(Foo(1, 2)) do f
  f = fmap(x -> 2x, f)
  f.y
end
```

This is an immediate issue due to the fact that we want to differentiate `reset!` in RNNs.

**Comment by CarloLucibello** [comment]
it works now 
```julia
julia> using Flux, Functors

julia> struct Foo
         x
         y
       end

julia> @functor Foo

julia> gradient(Foo(1, 2)) do f
         f = fmap(x -> 2x, f)
         f.y
       end

((x = nothing, y = 2),)

```

**Comment by DhairyaLGandhi** [comment]
Yeah this was fixed some time back
