### ISSUE TITLE
Flux master does not precompile

### ISSUE THREAD

**Issue by kczimm** [FluxML/Flux.jl#881]
Maybe this is known and not concerning because it's the master branch and maybe we should be adding Flux from tagged releases but I'm unable to precompile the master branch. It failed with the error:

```
ERROR: LoadError: UndefVarError: pullback not defined
Stacktrace:
 [1] include at .\boot.jl:328 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1094
 [3] include(::Module, ::String) at .\Base.jl:31
 [4] top-level scope at none:2
 [5] eval at .\boot.jl:330 [inlined]
 [6] eval(::Expr) at .\client.jl:432
 [7] top-level scope at .\none:3
```

I know this is because pullback is not exported in Zygote v0.3.4 but is in the master branch. However, the master branch Project.toml in Flux is not updated to depend on Zygote#master.

I'm fine with just adding Flux#zygote at the moment. I just thought I'd share this in case others are struggling.

**Comment by MikeInnes** [comment]
In general, you can get a dev setup with all the right packages by cloning the flux repo and activating its project/manifest. You can also run `]status` to see the list of packages that need to be checked out (or even look in the manifest to see the exact commits).

**Comment by dhairyagandhi96** [comment]
Closing now as the compat bounds have been updated. Thanks for looking into this!
