### ISSUE TITLE
How do I get a list of all the trainable weights and their gradients?

### ISSUE THREAD

**Issue by AjinkyaPrabhu** [FluxML/Flux.jl#884]
given this model how do I get all the weights in a list?
`model = Chain(
        Dense(784,256,Flux.relu),
        Dense(256,128,Flux.relu),
        Dense(128,10),
        Flux.softmax,
)`

**Comment by MikeInnes** [comment]
You need to use the functions `gradient` and `params`, as described in the [docs](https://fluxml.ai/Flux.jl/stable/models/basics/).
