### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by andreasnoack** [FluxML/Flux.jl#89]
It would be great to

1) [ ] Turn on coverage in the Travis script and put the banner in the README.
2) [ ] Improve the coverage. Right now it is around 38% according to `Coverage.jl`

**Comment by ToucheSir** [comment]
Is this still something we want to pursue with GHA/Buildkite?

**Comment by CarloLucibello** [comment]
Adding a coverage badge to the readme would be good

**Comment by lassepe** [comment]
Seems like this could be closed.

**Comment by ToucheSir** [comment]
AFAICT we haven't had code coverage in ~2 years (coinciding with a CI changeover?). I can hopefully have time to look into this in around a month's time, but if anyone wants to jump on it help very much appreciated.
