### ISSUE TITLE
Regularisation docs missing norm() definition

### ISSUE THREAD

**Issue by pcerdam** [FluxML/Flux.jl#892]
Hi there,

Toying around with the [regularisation](https://fluxml.ai/Flux.jl/stable/models/regularisation/) tutorial throws `UndefVarError: norm not defined` if executed as-is. From what I gather, `using Distributions` appears to solve it.

It's a really minor issue but I thought I would point it out. Cheers!

**Comment by scheidan** [comment]
`norm` is part of standard library `LinearAlgebra`.  It is shipped with Julia, but you have to load to first via `using`.
