### ISSUE TITLE
t

### ISSUE THREAD

**Issue by LiborKudela** [FluxML/Flux.jl#895]

**Comment by dhairyagandhi96** [comment]
Seems like a mistake? Maybe let's close this and you can open a new one with the correct description?

**Comment by dhairyagandhi96** [comment]
Closing this for now. Feel free to open a new issue with.. the issue you're facing :)

**Comment by LiborKudela** [comment]
Oh, I am very sorry. It was a mistake (I did not even noticed I had opened this). But thank you for the nice and quick reply anyway :)
