### ISSUE TITLE
Jacobian for Conv layers

### ISSUE THREAD

**Issue by vitskvara** [FluxML/Flux.jl#896]
Hi, is there a way to compute Jacobian for convolutional layers? This works for dense layers:
```julia
using Flux
m = Dense(4,6)
x = randn(4)
j = Flux.Tracker.jacobian(m ,x)
```
However doing the same with a convolutional layer
```julia
m = Conv((4,4), 1=>1)
x = randn(4,4,1,1)
j = Flux.Tracker.jacobian(m ,x)
```
results in
```julia
ERROR: MethodError: no method matching jacobian(::Conv{2,4,typeof(identity),TrackedArray{…,Array{Float32,4}},TrackedArray{…,Array{Float32,1}}}, ::Array{Float64,4})
Closest candidates are:
  jacobian(::Any, ::AbstractArray{T,1} where T) at /home/vit/.julia/packages/Tracker/SAr25/src/back.jl:175
```
since the Jacobian only seems to be defined for 1D inputs. I understand that Jacobian of convolutional layer(s) is much more complicated, however is there any other way of computing it, or a plan to implement such functionality?

**Comment by MikeInnes** [comment]
The jacobian function is just expecting a vector, rather than an ND array. You should be able to get the jacobian by wrapping the Conv layer to accept a vector, reshape it, and then reshape back to a vector again after the convolution.

**Comment by vitskvara** [comment]
Yes, this works now
```julia
using Flux
mc = Conv((2,2), 1=>1)
x = randn(4,4,1,1)
x = reshape(x, :)
m = Chain(
	x -> reshape(x,4,4,1,1),
	mc,
	x -> reshape(x, :)
	)
j = Flux.Tracker.jacobian(m ,x)
```
Thanks for your help.
