### ISSUE TITLE
Gradient Through Trebuchet.jl Error

### ISSUE THREAD

**Issue by AjinkyaPrabhu** [FluxML/Flux.jl#897]
```
function run(p)
    state = Trebuchet.shoot(0,p,100)[1]
    solution = simulate(state)
    return solution.Projectile[end][1]
end
    
    
grad = gradient((p)->run(p)) do sim
    distance = sim(p)
    
    
end
```

gives the error
`Compiling Tuple{typeof(Trebuchet.shoot),Tuple{Int64,Float64,Int64}}: try/catch is not supported.`

can anyone explain why this isn't working?

**Comment by MikeInnes** [comment]
There's a working version in the model zoo, which makes use of `ForwardDiff` for the trebuchet internals. Worth giving that a go and opening issues there if it doesn't work with the manifest provided.
