### ISSUE TITLE
How to convert Tracked Number in Number?

### ISSUE THREAD

**Issue by massimilianocomin** [FluxML/Flux.jl#905]
Hello,

I can't find in the documentation nor here how to convert a tracked number (or array of tracked numbers, or tracked array, etc...) into a plain and simple number. For instance, I would like to save the loss of a model, or plot it, etc...

Thank you for your help.

**Comment by MikeInnes** [comment]
You can do this with the `data` function. There's more detail on it [here](https://fluxml.ai/Flux.jl/stable/internals/tracker/#Tracked-Arrays-1).

**Comment by massimilianocomin** [comment]
Thank you, actually I was having problems with this function because I did not convert my Array of Tracked Numbers into a Tracked array with Tracker.collect.  Now it's okay!
