### ISSUE TITLE
`train!` method for `Chain`

### ISSUE THREAD

**Issue by heliosdrm** [FluxML/Flux.jl#921]
The second argument of `train!` is meant to be a set of tracked parameters of the model, typicall obtained from `params(model)`. While there is no theoretical restriction on how the user makes that `model` -- except that it should contain tracked parameters --, it is typically made as a  `Chain` of multiple layers, i.e. `typeof(model) <: Flux.Chain`.

Is there any reason (e.g. performance, etc.) against defining a method for `train!(loss, model::Chain, data, opt; kwargs...) = train!(loss, params(model), data, opt; kwargs...)`? I think that this interface would be more intelligible, and straightforward in many use cases.

If this is a reasonable idea, I can make a PR.

**Comment by MikeInnes** [comment]
I think this would have the potential to cause confusion, without adding all that much. We're talking about the difference between `params(model)` and `model`, which isn't a big saving. We generally expect that people will learn how to write their own training loops quite quickly, so hiding `params` could make that process slower.

**Comment by heliosdrm** [comment]
I agree that this suggestion does not save much typing. The motivation was to provide an interface that is one step closer to the interface of other ML libraries, where the functions for training take the model as argument. Honestly, the current interface of `train!` did make me feel confused the first time I saw it. ("hm... where is the model?")

Perhaps this interface has the purpose of helping users understand that it is the parameters of the model what they actually "train" -- or modify in the training, not the model itself. If it is like that, I'm ok with leaving as it is. Maybe it's the documentation and not the function what might be modified to make this clearer?

**Comment by dhairyagandhi96** [comment]
Would really appreciate a note in the docs!
