### ISSUE TITLE
Looking for libcuda and failing on a device without CUDA

### ISSUE THREAD

**Issue by ianshmean** [FluxML/Flux.jl#928]
On MacOS, without CUDA, v1.3-rc4.1, Flux master gives me:
```
ERROR: LoadError: InitError: error compiling __init__: error compiling cuDeviceGetCount: could not load library "libcuda"
dlopen(libcuda.dylib, 1): image not found
```

**Comment by MikeInnes** [comment]
Assuming you can reproduce this just with e.g. CuArrays, it'd be best to open an issue there so they know about it.

**Comment by ianshmean** [comment]
Thanks. This was known about and is no longer an issue on flux master
