### ISSUE TITLE
Warning on fresh Flux install

### ISSUE THREAD

**Issue by AlCap23** [FluxML/Flux.jl#929]
After a fresh julia 1.2 install with a fresh install of Flux v0.9.0 and Tracker v0.2.4

```julia
[ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
WARNING: Method definition project(Any, Any, Any) in module NNlib at /home/alcap/.julia/packages/NNlib/mxWRT/src/impl/conv_direct.jl:66 overwritten at /home/alcap/.julia/packages/NNlib/mxWRT/src/impl/conv_direct.jl:66.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition project(Any, Any, Any) in module NNlib at /home/alcap/.julia/packages/NNlib/mxWRT/src/impl/depthwiseconv_direct.jl:41 overwritten at /home/alcap/.julia/packages/NNlib/mxWRT/src/impl/depthwiseconv_direct.jl:41.
  ** incremental compilation may be fatally broken for this module **
```

This is possibly related to https://github.com/FluxML/Zygote.jl/issues/397

**Comment by maximilian-gelbrecht** [comment]
Related to this issue `Conv` layers are broken for me. See also the quoted issue, https://github.com/FluxML/Zygote.jl/issues/397#issuecomment-552378150 Can somebody tell me which library to downgrade for a temporary fix? Just downgrading Flux does not work.

**Comment by kleskjr** [comment]
@maximilian-gelbrecht , what did the trick for me was to revert to an older manifest file (.julia/environments/v1.2/Manifest.toml). If you don't find one, please let me know I can share one with you.

**Comment by dhairyagandhi96** [comment]
Ffixed with the 0.5.2 tag of `TimerOutputs.jl`
