### ISSUE TITLE
setindex! not defined for TrackedArray

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#93]
currently
```julia
julia> w = param(rand(5));

julia> w[1] = 3
ERROR: indexing not defined for TrackedArray{…,Array{Float64,1}}
Stacktrace:
 [1] setindex!(::TrackedArray{…,Array{Float64,1}}, ::Int64, ::Int64) at ./abstractarray.jl:966
 [2] macro expansion at ./REPL.jl:97 [inlined]
 [3] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```
On the other hand `getindex` is available
```julia
julia> w[1]
Tracked 0-dimensional Array{Float64,0}:
0.686571
```

**Comment by MikeInnes** [comment]
What do you need this for, and/or how would you expect this to behave? We won't be able to differentiate this, so perhaps the error message should just expain that.

**Comment by CarloLucibello** [comment]
not really expecting anything, more a remainder than anything. close if you thing this should not be considered an issue

**Comment by MikeInnes** [comment]
Ok, I added more of an explanation, let me know if that isn't clear.

**Comment by cossio** [comment]
It seems natural to try to use something like this to set the initial conditions of an array. For example:

```
w = param(zeros(5,5))
w[1,1] = 1.0  # ERROR
```

But perhaps the intended way to do this is like this:

```
w = zeros(5,5)
w[1,1] = 1.0
w = params(w)
```

?

**Comment by MikeInnes** [comment]
Yes, if you're just setting up the parameter but not trying to differentiate the indexing, that'd be the way to do it.
