### ISSUE TITLE
Feature request: Weight normalization

### ISSUE THREAD

**Issue by ararslan** [FluxML/Flux.jl#942]
[Weight normalization](https://arxiv.org/abs/1602.07868) is a reparameterization of the weights in terms of two quantities which are optimized instead of the weights directly. The authors provide [a reference implementation](https://github.com/TimSalimans/weight_norm) in Python using Theano, and the functionality is available in PyTorch as a hook.

I've toyed just a tiny bit with implementing this, but I think my knowledge of Flux's internals is insufficient. I was looking at implementing it as a layer that wraps another layer, for which the `params` are the *g* and **v** parameterization of the weights of the wrapped layer. Perhaps there's a better way.

**Comment by CarloLucibello** [comment]
another attempt here https://github.com/FluxML/Flux.jl/pull/1005
