### ISSUE TITLE
Gradient on a Neural Network

### ISSUE THREAD

**Issue by jcheyns** [FluxML/Flux.jl#955]
Quite new to the field. 
I was wanting to have the gradient on the weights in my neural network.
I naively implemented this in the following way
`
m = Chain(Dense(43, 5, σ), Dense(5, 1, σ))

ps = params(m)

board = zeros(Int16,43) #just an example
	
#partial diff on the weights
gs = gradient(() -> m(board) , ps)
`
This results in 
ERROR: Output should be scalar; gradients are not defined for output Float32[0.75180054]

Can someone help me out?

**Comment by dhairyagandhi96** [comment]
Your output of the function to be differentiated is the output of the NN, an Array.

Best to do a reduction on the output for it to work, a `sum` is usually what i do.

`gradient(()-> sum(m(board)), ps)` for an example

**Comment by jcheyns** [comment]
Shoot, I totally overlooked that, even if I only have one node at the top of the NN the result is still an Array. Silly me

**Comment by dhairyagandhi96** [comment]
Happy to help, feel free to open an issue if you run into a bug
