### ISSUE TITLE
Is there a way to have layers (esp. a Conv) without biases? 

### ISSUE THREAD

**Issue by rohitsupekar** [FluxML/Flux.jl#966]
Or is there a clever way to instruct the training to not train the biases but just the weights?

**Comment by dhairyagandhi96** [comment]
#873

**Comment by bhvieira** [comment]
Sure, just don't pass the bias when you compute your gradients. If you a `Conv` layer `A` update only `A.weight` instead.

You could redefine the `Conv` struct as well, and remove the bias there.

**Comment by CarloLucibello** [comment]
duplicate of #868
