### ISSUE TITLE
Dense(in, out) -> Dense(out, in) ?

### ISSUE THREAD

**Issue by CarloLucibello** [FluxML/Flux.jl#97]
Not really an issue here, but maybe we want to reconsider the arguments order in the constructor of the dense layer. Maybe it is just my personal taste, but it feels kind of unnatural to me that `Dense(in, out)` represents an `out x in`  matrix, I'd rather have Dense(out, in). 

I'm suggesting this because breaking things now is still quite ok, and this is a badly breaking change

**Comment by jekbradbury** [comment]
`Dense(in, out)` is more consistent with the `Chain` constructor reading left-to-right (and chaining in general), and is also standard in the rest of the deep learning frameworks I'm familiar with.

**Comment by Evizero** [comment]
while I also tend to think in matrix dimensions, I'd claim that `Dense(in, out)` is more user friendly

**Comment by CarloLucibello** [comment]
>Dense(in, out) is more consistent with the Chain constructor reading left-to-right (and chaining in general), and is also standard in the rest of the deep learning frameworks I'm familiar with.

This is a strong enough argument. It's just my brain that keeps visualizing layers as function (well, actually actually are) and place the input on the right and the output on the left, as in `y=f(x)`. On the same line I prefer to write a chain as
```julia
Chain(  f,
        g,
        h)
```
which resembles the actual computation
```julia
x = f(x)
x = g(x)
x = h(x)
```
At least in julia the composition operator |> has a clear direction `x |> f |> g`, it would be nice if we could use it to form a Chain
