### ISSUE TITLE
Float32 for performance improvements (code samples)

### ISSUE THREAD

**Issue by philtomson** [FluxML/Flux.jl#971]
Under Performance Tips in the docs it says to prefer using Float32 if you want better performance. That's a good idea, but for newbies it would probably be good to include some code snippets so they can see how the conversion is done (or how to have all the numbers be Float32 so as to avoid conversions in the first place).

**Comment by Roseck16** [comment]
Your request is very general. I could give you an example I've worked on. In this [sample](https://github.com/Roseck16/Dog-or-Cat-image-classifier/blob/cf4ffa28ede3060296742233769fe5561f40311f/image_preprocessing.jl#L18), you could simply change _Float64_ to _Float32_.
