### ISSUE TITLE
Handling imbalanced data

### ISSUE THREAD

**Issue by Roseck16** [FluxML/Flux.jl#972]
I've noticed that the pull request #122 was deleted a year ago. Are there some plans in the future to add methods to handle imbalanced data? Could be interesting to add class weights like in [Tensorflow](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data#class_weights).

**Comment by bhvieira** [comment]
#122 was merged. So, yes, it's supported.

**Comment by CarloLucibello** [comment]
crossentropy support weights 
https://github.com/FluxML/Flux.jl/blob/55616afc11373a68595d61c2cc75d59d543648d1/src/layers/stateless.jl#L20
