### ISSUE TITLE
ConvTranspose produces nonsense results for 3D (aka 5D) inputs

### ISSUE THREAD

**Issue by bcdarwin** [FluxML/Flux.jl#978]
E.g.,

```
julia> ConvTranspose((2, 2, 2), stride=2, 4=>8)(rand(16, 16, 16, 4, 3))
# ERROR: DimensionMismatch("arrays could not be broadcast to a common size")
```

When the batch size is 1, the application 'succeeds' by coincidence due to broadcasting but the output is of the wrong size.

The PR (#311) that added this operation explicitly noted that only 2D support was added but `@doc` doesn't mention this and anyway an error should be signalled if the functionality is missing.

Examining [the definition](https://github.com/FluxML/Flux.jl/blob/59bb0d81b020a33155e56add14f50ef20397ceaa/src/layers/conv.jl#L128) reveals that the channel and batch dims somehow end up swapped in the 2d vs 3d case:

```
ct2 = ConvTranspose((2, 2),    4=>5, stride=2)
ct3 = ConvTranspose((2, 2, 2), 4=>5, stride=2)
mat2 = rand(    16, 16, 4, 3);
mat3 = rand(16, 16, 16, 4, 3);
∇conv_data(mat3, ct3.weight, conv_transpose_dims(ct3, mat3)) |> size
# (32, 32, 32, 3, 5)
∇conv_data(mat2, ct2.weight, conv_transpose_dims(ct2, mat2)) |> size
# (32, 32, 5, 3)
```

**Comment by bcdarwin** [comment]
On some investigation, it looks like the issue is that the 2D case [throws away the return value of the `∇conv_data` call](https://github.com/FluxML/NNlib.jl/blob/9df3631a3c1938d2c9b3b0faf100bc69d65e1749/src/conv.jl#L80) and thus misses the final transpose_swapbatch that [the 3D case undergoes](https://github.com/FluxML/NNlib.jl/blob/21d92c02d8193cedef68637b05715736e41ff027/src/impl/conv_direct.jl#L164).  However, the 2D result is the 'correct' one so I'm not immediately sure how to restructure the code to fix this ...

**Comment by bcdarwin** [comment]
Closing here since this is an `NNlib` issue.

**Comment by haampie** [comment]
Pinging @tejank10 for this issue as well, maybe he has some insights :)

**Comment by bcdarwin** [comment]
Moved [here](https://github.com/FluxML/NNlib.jl/issues/156).
